### ISSUE TITLE
'center_size' is not defined in output_utils.py

### ISSUE THREAD

**Issue by agneevguin** [dbolya/yolact#101]
The center_size function is needed when 'preserve_aspect_ratio' is set to True.
This requires the center_size in the output_utils which is not defined currently.

**Comment by dbolya** [comment]
Oh yeah huh. However, `preserve_aspect_ratio` is deprecated, so it has more problems than just that. See #51 for how to fix.

**Comment by abhigoku10** [comment]
@dbolya is this dependent on the input resolution of the custom dataset since the output resolution i want to test is on is 2K resolution

**Comment by dbolya** [comment]
oh yeah pixel scales are definitely dependent on resolution. Make sure to convert from relative coordinates to absolute coordinates (by multiplying by the image size) before calculating the area.

**Comment by dbolya** [comment]
Since this has been open so long, I'm going to close it. Feel free to reopen if you have any updates.
