### ISSUE TITLE
mask loss calculation

### ISSUE THREAD

**Issue by twangnh** [dbolya/yolact#108]
https://github.com/dbolya/yolact/blob/6e22d1b1ccbeab4001bc6acd9124f5a679083d21/layers/modules/multibox_loss.py#L524-L525
I'm wondering, since there is already sigmoid activation for the predicted mask, why you still clamp them to 0-1? thanks!

**Comment by dbolya** [comment]
See the discussion in #42. Specifically @andyhahaha's comments.
