### ISSUE TITLE
mAP mismatch when doing a small change to the code?

### ISSUE THREAD

**Issue by feiyuhuahuo** [dbolya/yolact#109]
The original result after cloning the project is:
![29_83](https://user-images.githubusercontent.com/32631344/62440889-9d0dbc80-b784-11e9-88d4-99b9fa334906.png)
Then I did a little modification to 'yolact.py' and 'eval.py'. I changed line 617  `return self.detect(pred_outs)` in 'yolact.py' to `return pred_outs`. Then I initiate the 'Detect' class in 'evaluate' function in 'eval.py'. That means I add `detect = Detect(cfg.num_classes, bkg_label=0, top_k=200, conf_thresh=0.05, nms_thresh=0.5)` in line 791. And then changed line 873 to ` prep_metrics(ap_data, detect(preds), img, gt, gt_masks, h, w, num_crowd, dataset.ids[image_idx], detections)`. Finally, the result is:
![29_72](https://user-images.githubusercontent.com/32631344/62441193-be22dd00-b785-11e9-98bf-65196976e4c3.png)
Why there's a mismatch? I just want 'yolact.py' to return prediction results whenever in training or testing.

**Comment by dbolya** [comment]
Prob cause you didn't apply this line:
https://github.com/dbolya/yolact/blob/6e22d1b1ccbeab4001bc6acd9124f5a679083d21/eval.py#L789
Sorry I needed to pass an command line arg into that strict and this was the easiest way to do it. Just do the same for your new detect object.

**Comment by feiyuhuahuo** [comment]
It's OK now. I ignored this parameter, thanks.

**Comment by dbolya** [comment]
Nice, I'll close the issue then.
