### ISSUE TITLE
The difference between the FPN in yolact and the FPN in RetinaNet?

### ISSUE THREAD

**Issue by feiyuhuahuo** [dbolya/yolact#110]
I note that the FPN structure in yolact is slightly different from the FPN in RetinaNet. In RetinaNet, P6 is obtained via a 3x3 stride-2 conv on C5 and P7 is computed by applying ReLU followed by a 3x3 stride-2 conv on P6. In yolact, P6 is directly obtained from P5, and P7 is obtained from P6 (without the ReLU before Conv). So is there any reason for why you did this?

**Comment by dbolya** [comment]
Oh? I thought Retinanet obtains P6 from P5 not C5. I don't think it really matters though, but it's probably better to get P6 from P5 considering it just gives it that extra layer of computation.

Update: I just checked the Retinanet paper and you're right. Looks like that went over my head, but no point in changing it now.

**Comment by feiyuhuahuo** [comment]
OK, got it. And I'll close this issue.
