### ISSUE TITLE
how to get masks, rois and classes array format?

### ISSUE THREAD

**Issue by et0704a** [dbolya/yolact#113]
Hello, 
Can I get the masks, rois, classes and scores array format like matterport/Mask_RCNN results?
Like this picture
![image](https://user-images.githubusercontent.com/44827324/62938124-f6b75c00-be00-11e9-821b-eaa32bad6cbc.png)
Because I want to show results in Spyder variable explorer.

**Comment by dbolya** [comment]
Yeah, you can get it as the output of postprocessing. Check out how eval.py uses them on lines 140 and 148-9.

Then check out the evaluate function for how to create det_out.

**Comment by et0704a** [comment]
Thank you for the information.
