### ISSUE TITLE
when I run eval.py , Error: raise NotImplementedError

### ISSUE THREAD

**Issue by liugaolian** [dbolya/yolact#119]
root@xiaoxiong:/home/xiaoxiong/mmdetection/temp_mount/yolact# python eval.py --config=yolact_im1024_config --trained_model=weights/yolact_im1024_23_10000.pth --score_threshold=0.3 --top_k=100 --image=/home/xiaoxiong/mmdetection/temp_mount/my_dataset/coco/val2017/IMG_20190719_091012.jpg
-------------------------------------------------------------------------------------------------------------------
Loading model... Done.
Traceback (most recent call last):
  File "eval.py", line 1020, in <module>
    evaluate(net, dataset)
  File "eval.py", line 797, in evaluate
    evalimage(net, args.image)
  File "eval.py", line 562, in evalimage
    batch = FastBaseTransform()(frame.unsqueeze(0))
  File "/root/anaconda3/envs/simple_faster_rcnn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xiaoxiong/mmdetection/temp_mount/yolact/utils/augmentations.py", line 615, in forward
    raise NotImplementedError
NotImplementedError

**Comment by dbolya** [comment]
You got a not implemented error. That means something hasn't been implemented. If you look at the line number of the error, you can see that's cfg.preserve_aspect_ratio, which I don't support. Either implement that yourself in FastBaseTransform, or in `evalimage` in `eval.py`, replace `FastBaseTransform` with `BaseTransform` (you might have to change parameters and move everything to the CPU and then back) and deal with the slower speed.

**Comment by liugaolian** [comment]
> You got a not implemented error. That means something hasn't been implemented. If you look at the line number of the error, you can see that's cfg.preserve_aspect_ratio, which I don't support. Either implement that yourself in FastBaseTransform, or in `evalimage` in `eval.py`, replace `FastBaseTransform` with `BaseTransform` (you might have to change parameters and move everything to the CPU and then back) and deal with the slower speed.

————————————————————————————————————————
thank you for your reply! According to your guidance, I have solved the problem!
You are the most serious open source author I have ever seen on github.
————————————————————————————————————————

**Comment by dbolya** [comment]
Haha thanks :^)
