### ISSUE TITLE
question about label_map

### ISSUE THREAD

**Issue by chejulien** [dbolya/yolact#120]
Hi, @dbolya , thanks for your nice work.

I read your section Custom Dataset in readme and label_map field in config.py, but I'm still not sure about how to organize Class name and label_map. Do you mean if we set 'class_names':  (apple_1, pear_2, peach_3) then we can set 'label_map': None ?
Could you please provide a simple sample? 

Thanks
Julien

**Comment by dbolya** [comment]
That's right, so if `class_names` is `("apple", "pear", "peach")`, then apple should be id 1 in your aannotations and peach id 3. Then unless you indexed the classes in your dataset differently, you can leave label map as none. That's only used if you didn't index your IDs sequentially starting from 1.

**Comment by chejulien** [comment]
OK, Thanks.
