### ISSUE TITLE
Would a box predict two classes?

### ISSUE THREAD

**Issue by feiyuhuahuo** [dbolya/yolact#121]
Since the box filtering progress is done across all classes. What if a box predicts two classes? Which means, one box has two class scores higher than the confidence threshold, so this box is kept twice with two different classes. Then in fast nms, they are all kept luckily. Then it comes with this case: the same box predicts two (or more) classes. Would this situation be possible?

**Comment by dbolya** [comment]
Yup, in theory that should be able to happen. However, in practice since the network is trained to only output 1 class with softmax, if a detection decides it wants to be 2 classes at once, both scores would be low and some other box would likely suppress it during NMS.

What's far more common and actually happens quite frequently is when two very similar detections with different classes detect the same thing and both survive, line the car / truck in this image:

![000000010700](https://user-images.githubusercontent.com/19721752/63482470-053bee00-c467-11e9-862c-44ecb68ef261.png)

**Comment by feiyuhuahuo** [comment]
>      I add this piece of code:
        box_list = np.array(boxes.cpu()).tolist()
        ss = []
        print()
        print(len(box_list))
        for aa in box_list:
            if aa in ss:
                print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
            else:
                ss.append(aa)
        print(len(ss))
to here.
https://github.com/dbolya/yolact/blob/29e809e563d0c3e6c47c5c6716b8cc81686a2b24/layers/functions/detection.py#L176-L179
Directly inspect that if there is any repeated box in `boxes`. If there are repeated boxes, this means there are boxes detecting more than one class, right? Then I found quite a lot repeated boxes.

**Comment by dbolya** [comment]
Ah yeah so see that comment up there about the second threshold? There are going to be a bunch of overlapping boxes with really low scores that are just copies of the other boxes. That's more of a bug that slightly increase mAP so I left it in than an actual phenomenon. If you set `second_threshold=True` at the top of the function then you should observe far fewer of those duplicates.

**Comment by abhigoku10** [comment]
@dbolya  by using the second_threshold=True will i always get only detection box even if my score_threshold is low

**Comment by dbolya** [comment]
@abhigoku10 That shouldn't be the case. Is that for your custom dataset?

**Comment by abhigoku10** [comment]
@dbolya yes mine custom dataset

**Comment by dbolya** [comment]
@abhigoku10 I just tested it on COCO and everything's working as expected. In your custom dataset results, do you have any high scoring detections that have no mask? Maybe that's what's causing that.

**Comment by abhigoku10** [comment]
@dbolya  wokay i shall check that one more time , but i have double mask overlapping on each other with double detection and confidence score

**Comment by dbolya** [comment]
Since this has been open so long, I'm going to close it. Feel free to reopen if you have any updates.

**Comment by pieterbl86** [comment]
> Yup, in theory that should be able to happen. However, in practice since the network is trained to only output 1 class with softmax, if a detection decides it wants to be 2 classes at once, both scores would be low and some other box would likely suppress it during NMS.
> 
> What's far more common and actually happens quite frequently is when two very similar detections with different classes detect the same thing and both survive, like the car / truck in this image:
> 
> ![000000010700](https://user-images.githubusercontent.com/19721752/63482470-053bee00-c467-11e9-862c-44ecb68ef261.png)

@dbolya is there any way (parameter setting, additional code) to suppress one of the classes in case an object has two different class detections? In your example, is there a way to only have car or only truck (decision should be made on the highest confidence score I suppose?)
