### ISSUE TITLE
Loss convergence on custom dataset

### ISSUE THREAD

**Issue by abhigoku10** [dbolya/yolact#123]
@dbolya  i have trained Resnet 18,34,50 and 101 on custom dataset for 6lakh iterations the loss for all the models is around 7-8 value the total loss . Though is increase the iterations to 8lakh or > 8 lakh the loss are not converging . Any thoughts on this

**Comment by dbolya** [comment]
Since this has been open so long, I'm going to close it. Feel free to reopen if you have any updates.
