### ISSUE TITLE
The mAP on COCO test-dev is same as on COCO minival?

### ISSUE THREAD

**Issue by feiyuhuahuo** [dbolya/yolact#129]
Note that the reported mAP in your paper is 29.8 which is tested on COCO test-dev (COCO test-dev has 20k images right?). And the mAP on COCO minival (5k) is also 29.8. But for other networks, e.g. yolov3, the mAP on minival is usually higher than that on test-dev.

Besides, I have another question here.
https://github.com/dbolya/yolact/issues/127#issuecomment-526466370
Thanks for the reply.

**Comment by dbolya** [comment]
Uhh the minival performance used to be 29.9 (like it is reported in the paper, see Table 2a YOLACT fast) idk what happened. That's the problem with constantly updating works like this : /
