### ISSUE TITLE
question about "make_priors"

### ISSUE THREAD

**Issue by shoutOutYangJie** [dbolya/yolact#130]
> self.priors = torch.Tensor(prior_data).view(-1, 4)

hello, i modify your code for my task, and running modified code failed. I notice that the above line generates a cpu tensor. So I change it to following line:

> self.priors = torch.Tensor(prior_data).view(-1, 4).cuda()

and, code runs successfully. 
But your code here doesn't use ".cuda()". why can your code work?

**Comment by dbolya** [comment]
That's because of this line in the setup:
https://github.com/dbolya/yolact/blob/605b3c8fdf283642e7753c355bc6ee02f8db1380/train.py#L90
(there's a similar line in `eval.py`)

That sets the default `torch.Tensor` to return `torch.cuda.FloatTensor`, so it's cuda by default.

**Comment by shoutOutYangJie** [comment]
> That's because of this line in the setup:
> https://github.com/dbolya/yolact/blob/605b3c8fdf283642e7753c355bc6ee02f8db1380/train.py#L90
> 
> 
> (there's a similar line in `eval.py`)
> That sets the default `torch.Tensor` to return `torch.cuda.FloatTensor`, so it's cuda by default.

thanks for your lighting reply

**Comment by dbolya** [comment]
:^)
