### ISSUE TITLE
Preview loaded masks and boxes

### ISSUE THREAD

**Issue by Aya-tan** [dbolya/yolact#134]
Hello,
How can I display the masks/boxes loaded from the annotation file ?
I would like to check if my annotations are correctly processed by visualizing it on 1 image from my training set.

**Comment by dbolya** [comment]
Uhh I don't have any tools for that, so you'll have to implement it yourself. Once you have the boxes and masks loaded though, you could copy my `prep_display` function in `eval.py` to draw them (you'll need to tear it up a little).

**Comment by Aya-tan** [comment]
I see, thank you!
