### ISSUE TITLE
Memory Error!

### ISSUE THREAD

**Issue by bond9779** [dbolya/yolact#138]
Traceback (most recent call last):
  File "train.py", line 385, in <module>
    train()
  File "train.py", line 216, in train
    for datum in data_loader:
  File "/home/aeye/Documents/YOLACTvenv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/aeye/Documents/YOLACTvenv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
MemoryError: Traceback (most recent call last):
  File "/home/aeye/Documents/YOLACTvenv/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/aeye/Documents/YOLACTvenv/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/aeye/yolact-master_Resent50_aug16/data/coco.py", line 88, in __getitem__
    im, gt, masks, h, w, num_crowds = self.pull_item(index)
  File "/home/aeye/yolact-master_Resent50_aug16/data/coco.py", line 151, in pull_item
    {'num_crowds': num_crowds, 'labels': target[:, 4]})
  File "/home/aeye/yolact-master_Resent50_aug16/utils/augmentations.py", line 661, in __call__
    return self.augment(img, masks, boxes, labels)
  File "/home/aeye/yolact-master_Resent50_aug16/utils/augmentations.py", line 54, in __call__
    img, masks, boxes, labels = t(img, masks, boxes, labels)
  File "/home/aeye/yolact-master_Resent50_aug16/utils/augmentations.py", line 380, in __call__
    current_masks = masks[mask, :, :].copy()
MemoryError

During training, i am facing the above error after 4 lakh iterations are complete. I don't seem to understand as to why this error occurs..

@dbolya Can you help me with this?

**Comment by dbolya** [comment]
It's kind of weird that you're half way through training and this is happening, but you're running out of memory.

What GPU are you using, what model, and what batch size? And are you sure that only YOLACT is using that GPU? Usually the memory used throughout training is pretty stable so idk why you're getting that error now.

**Comment by HariharanJ9779** [comment]
@dbolya I'm currently running on RTX 2080Ti,.
                Yes its using both the GPU stacks,
                 Batch size 8, Model = Resnet 50.
                No other process is using the GPU stacks

**Comment by dbolya** [comment]
Hmm okay that shouldn't be running out of memory. What version of Pytorch are you on? Pytorch 1.0.1 uses less GPU memory than the subsequent versions. See #33 for tips on how to downgrade if you have a later version.

**Comment by HariharanJ9779** [comment]
@dbolya  Python 3.6
                 pytorch 1.1.0 
                 torchvision 0.3.0

**Comment by dbolya** [comment]
Yup I recommend you downgrade. Try this command:
```
pip3 install https://download.pytorch.org/whl/cu100/torch-1.0.1-cp36-cp36m-win_amd64.whl
```

**Comment by sicarioakki** [comment]
I downgraded PyTorch version to 1.0.1 and torchvision to 0.2.0
Still i am facing the same issue..training stops  after a few iterations post 400K

**Comment by bond9779** [comment]
Even after downgrading the Pytorch to 1.0.1 and Torch to 0.2.0, i am still facing the same issue..

**Comment by dbolya** [comment]
*Waaaait* that's not a GPU memory error, that's a CPU memory error (augmentations are done on the CPU). What about your RAM? How much do you have available and is anything else using it at the moment?

**Comment by sicarioakki** [comment]
Would this occur if the training input images are of 2k or 4k resolutions??

**Comment by dbolya** [comment]
Uh maybe? If you have enough RAM, then it should be fine since the augmentation code scales it down to 550x550 anyway.

**Comment by sicarioakki** [comment]
Okay.. i reduced the batch size and it happens to be training without errors for now...i will let you know if there are any further hurdles 
Thanks for your input @dbolya

**Comment by Mozen** [comment]
I find the same error, you can change the parameter of  num_workers，the default is 4 , maye be cause memorterror,  I used 0 is ok. @dbolya

**Comment by Mozen** [comment]
I find the same error, you can change the parameter of num_workers，the default is 4 , maye be cause memoryerror, I used 0 is ok. @dbolya

**Comment by abhigoku10** [comment]
@Mozen  thanks for the advice when i used the numworks 0 i am still getting this 
ERROR: UNEXPECTED SEGMENTATION FAULT ENCOUNTERED IN WORKER
DataLoader worker (pid:2343) is killed by signal :Killed 
any thoughts on this @dbolya
