### ISSUE TITLE
RuntimeError: invalid argument 1: expected a matrix at THCTensorMathPairwise.cu:203

### ISSUE THREAD

**Issue by yl949** [dbolya/yolact#144]
First of all, thank you for your sharing code.
There is a problem I don't know how to solve when running the project.
The problem is below:
```
(yolactpy3) root@lyh12-desktop-mf4jjvl-7bfcc8c77-njpbk:~/lyh12/my_project/yolact
# python eval.py --trained_model=weights/yolact_base_54_800000.pth --score_threshold=0.3 --top_k=100 --image=my_image.jpg
```

when I run code above, the output info is:
```
Config not specified. Parsed yolact_base_config from the file name.

Loading model... Done.
Traceback (most recent call last):
  File "eval.py", line 1020, in <module>
    evaluate(net, dataset)
  File "eval.py", line 797, in evaluate
    evalimage(net, args.image)
  File "eval.py", line 563, in evalimage
    preds = net(batch)
  File "/root/lyh12/anaconda/envs/yolactpy3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/lyh12/my_project/yolact/yolact.py", line 634, in forward
    return self.detect(pred_outs)
  File "/root/lyh12/my_project/yolact/layers/functions/detection.py", line 76, in __call__
    result = self.detect(batch_idx, conf_preds, decoded_boxes, mask_data, inst_data)
  File "/root/lyh12/my_project/yolact/layers/functions/detection.py", line 103, in detect
    boxes, masks, classes, scores = self.fast_nms(boxes, masks, scores, self.nms_thresh, self.top_k)
  File "/root/lyh12/my_project/yolact/layers/functions/detection.py", line 148, in fast_nms
    iou.triu_(diagonal=1)
RuntimeError: invalid argument 1: expected a matrix at /opt/conda/conda-bld/pytorch_1544081038057/work/aten/src/THC/generic/THCTensorMathPairwise.cu:203
```

What should I do?

**Comment by dbolya** [comment]
Looks like you're not on Pytorch 1.0.1 or greater. Pytorch 1.0.1 introduced batch `triu_`, so no earlier version will work.

**Comment by yl949** [comment]
Thank you. It works after I update the Pytorch

**Comment by dbolya** [comment]
Nice!

**Comment by yl949** [comment]
Sorry to bother you again. I have one more question:
How can I just get the mask of the eval photo?

**Comment by dbolya** [comment]
Do you want to display just the masks, or get the masks as a numpy array?

For both, you'd be changing this function:
https://github.com/dbolya/yolact/blob/605b3c8fdf283642e7753c355bc6ee02f8db1380/eval.py#L128

Then for the former, multiply `image_gpu` by 0 on line 138 or something. For the latter, convert `masks` to numpy after line 149 (as done in line 149) and then you can do whatever you want with it. If you want to use this for something downstream (and thus don't want to be evaluating images), you can check out how `prep_display` and `evalimage` get to that point.
