### ISSUE TITLE
RuntimeError: DataLoader worker (pid(s) 29244) exited unexpectedly

### ISSUE THREAD

**Issue by weasonliu** [dbolya/yolact#147]
Dear Sir,

thank you for sharing code. There was a problem running the code for training.

python3 train.py --config=yolact_base_config --batch_size=5
loading annotations into memory...
Done (t=9.26s)
creating index...
index created!
loading annotations into memory...
Done (t=0.32s)
creating index...
index created!
Initializing weights...
Begin training!

2
None
6
None
7
2
None
None
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 511, in _try_get_batch
    data = self.data_queue.get(timeout=timeout)
  File "/usr/lib/python3.5/queue.py", line 173, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.5/threading.py", line 297, in wait
    gotit = waiter.acquire(True, timeout)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/signal_handling.py", line 63, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 29332) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 382, in <module>
    train()
  File "train.py", line 213, in train
    for datum in data_loader:
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 576, in __next__
    idx, batch = self._get_batch()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 543, in _get_batch
    success, data = self._try_get_batch()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 519, in _try_get_batch
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 29332, 29334) exited unexpectedly

I was follow the tips to modify the num_workers to 0, but it's not work.
What should I do ?

**Comment by dbolya** [comment]
By setting `--num_workers=0` not working, what do you mean by that? At the very least, the error message should be vastly different since when set to 0, Pytorch doesn't use multiprocessing at all.

Can you post the error message you get when you set `num_workers` to 0?

**Comment by weasonliu** [comment]
If I modify num_workers = 0,

python3 train.py --config=yolact_base_config --batch_size=5
loading annotations into memory...
Done (t=9.22s)
creating index...
index created!
loading annotations into memory...
Done (t=0.32s)
creating index...
index created!
Initializing weights...
Begin training!

2
only print a number and exit.

**Comment by dbolya** [comment]
Okay, so what was happening originally was the main process (or one of the other ones) was crashing or otherwise calling `exit()`. Since that's an early termination without cleaning up, multiprocessing complains.

It looks like you modified the code, since my code doesn't print those numbers at all. In the modified code did you also include an `exit()` or some other thing that may crash? If you don't know, try reverting to the current master branch and training from there. Or if you didn't modify YOLACT, you might have modified Pytorch, so try reinstalling that.

**Comment by weasonliu** [comment]
Thank you for your kind reply. The problem is solved. It's my mistake.

**Comment by dbolya** [comment]
Nice!

**Comment by sdimantsd** [comment]
@weasonliu I'm dealing with the same problem, how did you solve it?

**Comment by weasonliu** [comment]
@sdimantsd sorry for the late reply. 
In my case, the error is from adding the other command to the file.
Maybe you should check the file for any wrong typing command exists.
