### ISSUE TITLE
只获取mask覆盖的部分

### ISSUE THREAD

**Issue by ylsxw** [dbolya/yolact#155]
你的code实在是太棒了，请问如何单色化背景只显示mask覆盖的部分。谢谢

**Comment by dbolya** [comment]
Don't speak Mandarin, sorry. But I do have Google Translate (and so do you):

Here:
https://github.com/dbolya/yolact/blob/02074d5d943bf9f8f2b5f45b9f4a0f80bed88563/eval.py#L185
Add:
```
img_gpu = img_gpu * (masks.sum(dim=0) > 0.5).float()
```
If you want only one mask, you can go
```
img_gpu = img_gpu * masks[0]
```
The rest of that block can be commented out (down to line 202).

**Comment by ylsxw** [comment]
Thank you very much
