### ISSUE TITLE
The shapes of backbone Conv results seems mismatch  with the original Resnet?

### ISSUE THREAD

**Issue by feiyuhuahuo** [dbolya/yolact#157]
I change the code in `Bottleneck.forward` in `backbone.py` like this:
![image](https://user-images.githubusercontent.com/32631344/65405409-8db70100-de0e-11e9-988d-3d95f1994aef.png)
Then I get the result  of Resnet-50:

torch.Size([1, 64, 138, 138]) torch.Size([1, 64, 138, 138])
torch.Size([1, 64, 138, 138])
torch.Size([1, 256, 138, 138])
torch.Size([1, 256, 138, 138])
torch.Size([1, 256, 138, 138]) torch.Size([1, 64, 138, 138])
torch.Size([1, 64, 138, 138])
torch.Size([1, 256, 138, 138])
torch.Size([1, 256, 138, 138])
torch.Size([1, 256, 138, 138]) torch.Size([1, 64, 138, 138])
torch.Size([1, 64, 138, 138])
torch.Size([1, 256, 138, 138])
torch.Size([1, 256, 138, 138])
torch.Size([1, 256, 138, 138]) torch.Size([1, 128, 138, 138])
torch.Size([1, 128, 69, 69])
torch.Size([1, 512, 69, 69])
torch.Size([1, 512, 69, 69])
torch.Size([1, 512, 69, 69]) torch.Size([1, 128, 69, 69])
torch.Size([1, 128, 69, 69])
torch.Size([1, 512, 69, 69])
torch.Size([1, 512, 69, 69])
torch.Size([1, 512, 69, 69]) torch.Size([1, 128, 69, 69])
torch.Size([1, 128, 69, 69])
torch.Size([1, 512, 69, 69])
torch.Size([1, 512, 69, 69])
torch.Size([1, 512, 69, 69]) torch.Size([1, 128, 69, 69])
torch.Size([1, 128, 69, 69])
torch.Size([1, 512, 69, 69])
torch.Size([1, 512, 69, 69])
torch.Size([1, 512, 69, 69]) torch.Size([1, 256, 69, 69])
torch.Size([1, 256, 35, 35])
torch.Size([1, 1024, 35, 35])
torch.Size([1, 1024, 35, 35])
torch.Size([1, 1024, 35, 35]) torch.Size([1, 256, 35, 35])
torch.Size([1, 256, 35, 35])
torch.Size([1, 1024, 35, 35])
torch.Size([1, 1024, 35, 35])
torch.Size([1, 1024, 35, 35]) torch.Size([1, 256, 35, 35])
torch.Size([1, 256, 35, 35])
torch.Size([1, 1024, 35, 35])
torch.Size([1, 1024, 35, 35])
torch.Size([1, 1024, 35, 35]) torch.Size([1, 256, 35, 35])
torch.Size([1, 256, 35, 35])
torch.Size([1, 1024, 35, 35])
torch.Size([1, 1024, 35, 35])
torch.Size([1, 1024, 35, 35]) torch.Size([1, 256, 35, 35])
torch.Size([1, 256, 35, 35])
torch.Size([1, 1024, 35, 35])
torch.Size([1, 1024, 35, 35])
torch.Size([1, 1024, 35, 35]) torch.Size([1, 256, 35, 35])
torch.Size([1, 256, 35, 35])
torch.Size([1, 1024, 35, 35])
torch.Size([1, 1024, 35, 35])
torch.Size([1, 1024, 35, 35]) torch.Size([1, 512, 35, 35])
torch.Size([1, 512, 18, 18])
torch.Size([1, 2048, 18, 18])
torch.Size([1, 2048, 18, 18])
torch.Size([1, 2048, 18, 18]) torch.Size([1, 512, 18, 18])
torch.Size([1, 512, 18, 18])
torch.Size([1, 2048, 18, 18])
torch.Size([1, 2048, 18, 18])
torch.Size([1, 2048, 18, 18]) torch.Size([1, 512, 18, 18])
torch.Size([1, 512, 18, 18])
torch.Size([1, 2048, 18, 18])
torch.Size([1, 2048, 18, 18])

So, confused about that ` torch.Size([1, 128, 138, 138])` which I think should not occur.  Since the numbers of bottlenecks of each stage is [3, 4,6, 3], seems the last stage lacks a bottleneck.
Same phenomenon occurs in Resnet-101.

**Comment by dbolya** [comment]
Not sure what you mean by that? If you go by number of features (in the lone sizes in the right column of your list of sizes there, but you can see the same thing * 4 if you read the last size in every 4 print statements) I count:
3 blocks of 64,
4 blocks of 128,
6 blocks of 256,
and 3 blocks of 512,
which is exactly as expected.

Also, that code is literally copy-pasted from torchvision's model zoo, so take that up with them if there are issues.

**Comment by feiyuhuahuo** [comment]
OK, I made a mistake. But I'm still confused about when to use the `stride=2 Conv`. I used to thought that the  `stride=2 Conv` should be the first Conv of the first bottleneck for each stage (except the first stage). But here is the second Conv. I get puzzled by the Internet things. I'll figure it out later, Thanks.

**Comment by dbolya** [comment]
Yeah I think it's that way so the stride coincides with an increase in the number of features (bottleneck is x4, so first conv outputs s x s x f, second outputs (s / 2) x (s / 2) x (f / 4 * 2), third then goes back up 4x and outputs (s / 2) x (s / 2) x (f * 2).

I just took a glance at the original paper and it doesn't seem to specify where the stride happens.
