### ISSUE TITLE
How to use web service?

### ISSUE THREAD

**Issue by Wilbur529** [dbolya/yolact#16]
Hello, could you please show me how to use the scripts in the "root/web" subdirectory?

**Comment by dbolya** [comment]
This is a web detection viewer I made to view detections encoded in COCO's RLE format.
First, make sure you're on the latest commit to get the latest detections. Then use the viewer, navigate to the YOLACT root directory and run
```
cd web
python server.py
```
This will host a detection viewer server on port 6337 (change it in `server.py` if you want something else). Note that you have to have the COCO dataset installed in the default place for this to work.

Connect to it through a browser and you'll see a menu to view detections. I've provided 100 images of detections for each of the configs in the readme. If you want to generate your own, simply navigate back the the root directory and run
```
python eval.py --trained_model=<mymodel> --score_threshold=0.05 --max_images=100 --no_sort --output_web_json
```
This will plop a json detection file in `<yolact_root>/web/dets`. You can fiddle with this command to output detections for what you want, just keep `--output_web_json` in there.
