### ISSUE TITLE
Could I run Yolact on windows 10？

### ISSUE THREAD

**Issue by May-forever** [dbolya/yolact#161]
Dear Dbolya, Could I run Yolact on windows 10？

**Comment by dbolya** [comment]
Yeah I run it on windows 10. Just get python and follow the steps in the readme. (Pycocotools might require a little bit of extra effort to install. Let me know if you have issues).

**Comment by hjm1990818** [comment]
> Yeah I run it on windows 10. Just get python and follow the steps in the readme. (Pycocotools might require a little bit of extra effort to install. Let me know if you have issues).

Dear Dbolya,

Thank you very much for your reply.

I want to train Yolact on my custom dataset.

I have learned that train Yolact on COCO can use the following command:
1. python train.py --config=yolact_base_config
2. python train.py --config=yolact_base_config --batch_size=5
3. python train.py --config=yolact_base_config --resume=weights/yolact_base_10_32100.pth --start_iter=-1

However, I don't know what's the command should I use for training Yolact on my custom dataset, and the webpage of Yolact also does't list the corresponding commands.

Could you please give me a hand?
Thank you very much in advance.

**Comment by dbolya** [comment]
The guide for training a custom dataset is here: https://github.com/dbolya/yolact#custom-datasets

**Comment by sagarkalburgi** [comment]
> Yeah I run it on windows 10. Just get python and follow the steps in the readme. (Pycocotools might require a little bit of extra effort to install. Let me know if you have issues).

Hello,

I'm trying to train a model in windows 10 and I keep facings this issue #663. Could you help me?
