### ISSUE TITLE
why the pred could be None in eval image

### ISSUE THREAD

**Issue by luqinghit** [dbolya/yolact#162]
When I wanted to extract the mask separately, I found preds for part of the images were None,uh...,Why does this happen

**Comment by luqinghit** [comment]
Ha,  I know why...If no target is detected in this image, the pred return None. Am I right?

**Comment by luqinghit** [comment]
I have got it !Thanks for your code!!

**Comment by dbolya** [comment]
Yup, if there's no detections for an image in a batch, `Detection` will return None for that image.
