### ISSUE TITLE
TypeError: expected np.ndarray (got NoneType)

### ISSUE THREAD

**Issue by hjm1990818** [dbolya/yolact#165]
Dear Dbolya,
I use and modify your command to test a new image[python eval.py --trained_model=weights/yolact_base_54_800000.pth --score_threshold=0.3 --top_k=100 --image=my_image.png], However, it occurs error, what should I do now?    
Below is the error information, please help me.
............................................................................................................................................................................
(pytorch) C:\Users\Administrator>python D:/Pycharm/yolact-master/eval.py --trained_model=D:/Pycharm/yolact-master/weights/yolact_resnet50_54_800000.pth --score_threshold=0.3 --top_k=100 --image=C:/Users/Administrator/Anaconda3/envs/pytorch/my_image.png

Config not specified. Parsed yolact_resnet50_config from the file name.

Loading model... Done.
Traceback (most recent call last):
  File "D:/Pycharm/yolact-master/eval.py", line 1020, in <module>
    evaluate(net, dataset)
  File "D:/Pycharm/yolact-master/eval.py", line 795, in evaluate
    evalimage(net, inp, out)
  File "D:/Pycharm/yolact-master/eval.py", line 561, in evalimage
    frame = torch.from_numpy(cv2.imread(path)).cuda().float()
TypeError: expected np.ndarray (got NoneType)
................................................................................................................................................................................

**Comment by dbolya** [comment]
That means your image "my_image.png" couldn't be found. Make sure that you haven't misspelled it or put it in the wrong folder or something.

**Comment by hjm1990818** [comment]
> That means your image "my_image.png" couldn't be found. Make sure that you haven't misspelled it or put it in the wrong folder or something.

Dear Dbolya,

I re-name my image as 1.png and move it to C disk, then use the following command. However, the error still occur, what should I do now？

............................................................................................................................................................................
(pytorch) C:\Users\Administrator>python D:/Pycharm/yolact-master/eval.py --trained_model=D:/Pycharm/yolact-master/weights/yolact_resnet50_54_800000.pth --score_threshold=0.3 --top_k=100 --image=C:/1.png

Config not specified. Parsed yolact_resnet50_config from the file name.

Loading model... Done.
Traceback (most recent call last):
File "D:/Pycharm/yolact-master/eval.py", line 1020, in 
evaluate(net, dataset)
File "D:/Pycharm/yolact-master/eval.py", line 795, in evaluate
evalimage(net, inp, out)
File "D:/Pycharm/yolact-master/eval.py", line 561, in evalimage
frame = torch.from_numpy(cv2.imread(path)).cuda().float()
TypeError: expected np.ndarray (got NoneType)
................................................................................................................................................................................

**Comment by dbolya** [comment]
Can you just run python from the same folder as the image is in (so you don't have to specify a path)? I'm not sure how python handles paths in windows (perhaps you need to use back slashes).

**Comment by hjm1990818** [comment]
> Can you just run python from the same folder as the image is in (so you don't have to specify an absolute path)? I'm not sure how python handles paths in windows (perhaps you need to use back slashes).

Dear  Dbolya,

I install Pytorch in the path:  C:\Users\Administrator\Anaconda3\envs\pytorch
In the 'pytorch' file there is a python.exe, I move the 1.png to the 'pytorch' file, then I activate pytorch and run the following command. Unfortunately, the same error occur.....
................................................................................................................................................................................
(pytorch) C:\Users\Administrator>python D:/Pycharm/yolact-master/eval.py --trained_model=D:/Pycharm/yolact-master/weights/yolact_resnet50_54_800000.pth --score_threshold=0.3 --top_k=100 --image=1.png

Config not specified. Parsed yolact_resnet50_config from the file name.

Loading model... Done.
Traceback (most recent call last):
File "D:/Pycharm/yolact-master/eval.py", line 1020, in
evaluate(net, dataset)
File "D:/Pycharm/yolact-master/eval.py", line 795, in evaluate
evalimage(net, inp, out)
File "D:/Pycharm/yolact-master/eval.py", line 561, in evalimage
frame = torch.from_numpy(cv2.imread(path)).cuda().float()
TypeError: expected np.ndarray (got NoneType)
................................................................................................................................................................................
![pytorch](https://user-images.githubusercontent.com/20625075/65694814-06d18500-e0a9-11e9-9b0f-1e92fa980889.png)

**Comment by dbolya** [comment]
I mean you're in the `C:\Users\Administrator` folder when you're running this command. Instead, cd to the folder where you have the image and run the command from that directory.

if you want to leave the image there then the command would be:
```C:\Users\Administrator\Anaconda3\envs\pytorch```

**Comment by hjm1990818** [comment]
> I mean you're in the `C:\Users\Administrator` folder when you're running this command. Instead, cd to the folder where you have the image and run the command from that directory.
> 
> if you want to leave the image there then the command would be:
> `cd C:\Users\Administrator\Anaconda3\envs\pytorch`

YES！It can work now，thanks a lot.

**Comment by dbolya** [comment]
Nice!
