### ISSUE TITLE
How to choose lr and set warm up when using larger batch size?

### ISSUE THREAD

**Issue by feiyuhuahuo** [dbolya/yolact#166]
I want to use `batch_size = 24` to train yolact on one GPU. And I change the lr decay like this `lr_steps': (90000, 190000, 220000, 240000)` and run for total 250000 iterations. I slightly reduced the total iterations comparing with 800000/3 because I found in the original training schedule, 800k iterations are too much. I did not change other settings. Then at last the mAP is 1 points lower than the original one. Besides, would the performance be better if use larger batch_size compare to batch_size=8?

**Comment by dbolya** [comment]
A bigger batch size should result in higher performance, yeah, but your logic for reducing the iterations might not be correct.

There are two things required for convergence:
 1. The model has to have seen enough data.
 2. There has to be enough gradient updates.

Increasing batch size and reducing iterations fulfills (1), but you're cutting the number of gradient updates considerably, so it might not converge (or at least converge to the same minimum).

I'd try expanding the number of iterations by looking at the validation mAP before each lr decay. If the mAP before the decay looks like it could still increase, I'd give that lr more iterations.

**Comment by feiyuhuahuo** [comment]
OK， that's make sense. I did not consider (2).
