### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by hjm1990818** [dbolya/yolact#167]
Dear Dbolya,

I create a custom dataset, and I want to use Yolact to train it. But I am falling in problems, below are the steps what I'm doing:

**1.** I collect and label 508 images with 550*550pixel, and then store them in the path: 
          D:\Pycharm\yolact-master\data\train_fish_image

**2.** I use label2coco.py to create a coco style file named 'train.json', and then store it in path:
          D:\Pycharm\yolact-master\data\train_fish_json

**3.** I create a definition for my dataset under dataset_base in data/config.py :
         my_custom_dataset = dataset_base.copy({
                 'name': 'My Dataset',
                 'train_images': 'D:/Pycharm/yolact-master/data/train_fish_image',
                 'train_info':   'D:/Pycharm/yolact-master/data/train_fish_json/train.json',
                 'valid_images': 'D:/Pycharm/yolact-master/data/train_fish_image',
                 'valid_info':   'D:/Pycharm/yolact-master/data/train_fish_json/train.json',
                 'has_gt': True,
                 'class_names': ('fish')
               })

**4.**  In yolact_base_config in the same file, I change the value for 'dataset' to 'my_custom_dataset' as below:
            yolact_base_config = coco_base_config.copy({
           'name': 'yolact_base',
            # Dataset stuff
            'dataset': my_custom_dataset,
            'num_classes': len(coco2017_dataset.class_names) + 1,
            # Image Size
            'max_size': 550,
            ................................
            ...................

**5.** cd C:\Users\Administrator\Anaconda3\envs\pytorch

**6.** Run the following command:
         python D:/Pycharm/yolact-master/train.py --config=yolact_base_config --   resume=D:/Pycharm/yolact-master/weights/base/yolact_resnet50_54_800000.pth --start_iter=-1

**However, an error occur, which is shown as following:**

loading annotations into memory...
Done (t=0.07s)
creating index...
index created!
loading annotations into memory...
Done (t=0.07s)
creating index...
index created!
Resuming training, loading D:/Pycharm/yolact-master/weights/base/yolact_resnet50_54_800000.pth...
Begin training!

Traceback (most recent call last):
  File "D:/Pycharm/yolact-master/train.py", line 382, in <module>
    train()
  File "D:/Pycharm/yolact-master/train.py", line 213, in train
    for datum in data_loader:
  File "C:\Users\Administrator\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "C:\Users\Administrator\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Users\Administrator\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\Pycharm\yolact-master\data\coco.py", line 91, in __getitem__
    im, gt, masks, h, w, num_crowds = self.pull_item(index)
  File "D:\Pycharm\yolact-master\data\coco.py", line 136, in pull_item
    assert osp.exists(path), 'Image path does not exist: {}'.format(path)
AssertionError: Image path does not exist: D:/Pycharm/yolact-master/data/train_fish_image\.jpg

I think there may be some problems with my handling, but I don't know what the exact reason is.
Could you please give me a hand ? 
Looing forward to hearing from you, thank you very much in advance.

**Comment by dbolya** [comment]
I'm not 100% on this, but it might be that your image names are wrong in your json. Can you open it up and in the `image` array, check your `file_name`s. From the error message here, it looks like your file names are just `".jpg"`, which is why it can't find anything.

Also, this is tangential to that, but in your dataset definition, you have
```
'class_names': ('fish')
```
but that doesn't create a tuple (instead it's just the parenthesis operator, so it will just return 'fish'). You want
```
'class_names': ('fish',)
```
instead.

**Comment by hjm1990818** [comment]
> I'm not 100% on this, but it might be that your image names are wrong in your json. Can you open it up and in the `image` array, check your `file_name`s. From the error message here, it looks like your file names are just `".jpg"`, which is why it can't find anything.
> 
> Also, this is tangential to that, but in your dataset definition, you have
> 
> ```
> 'class_names': ('fish')
> ```
> 
> but that doesn't create a tuple (instead it's just the parenthesis operator, so it will just return 'fish'). You want
> 
> ```
> 'class_names': ('fish',)
> ```
> 
> instead.

Dear Dbolya,

Thank you very much for your reply, however, there are still some errors in my setting which are confusing me. I try my best to find out that errors, however, I failed.

I send an e-mail to your e-mail address: dbolya@ucdavis.edu

In that email, I submit two setting files in the attachment.

could you please helping to check what errors in that files?

Thank you very much in advance.

**Comment by dbolya** [comment]
Responded through email. In the mean time I'll close this issue.

**Comment by furkanulger** [comment]
I am facing the exact same issue with my dataset. Therefore, would you mind sharing the solution if you find for yourself? Thanks.
