### ISSUE TITLE
It display error when run the command  python eval.py --trained_model=weights/yolact_base_54_800000.pth

### ISSUE THREAD

**Issue by cendelian** [dbolya/yolact#178]
Dear dbolya,
I am sorry to bother you.

I run the command:
sh data/scripts/COCO_test.sh

and after that, I run the command as below:
python eval.py --trained_model=weights/yolact_base_54_800000.pth

but it display error as below:
FileNotFoundError: [Errno 2] No such file or directory: './data/coco/annotations/instances_val2017.json'

why it display error and why it miss instances_val2017.json?
in other words, what's the steps i did are wrong?
i just want to run yolact and check it's performance.

could you help me?

**Comment by dbolya** [comment]
You downloaded the test set, not the training and validation sets. The test set is for submitting to the COCO eval servers, so we don't have labels for it and you can't evaluate locally.

Simply download the correct datasets with:
```sh data/scripts/COCO.sh```

and you can run the command you ran before.

**Comment by cendelian** [comment]
> You downloaded the test set, not the training and validation sets. The test set is for submitting to the COCO eval servers, so we don't have labels for it and you can't evaluate locally.
> 
> Simply download the correct datasets with:
> `sh data/scripts/COCO.sh`
> 
> and you can run the eval command you ran before.

Dear dbolya
Thanks for your information.
I run the command
`sh data/scripts/COCO.sh`
and the run the command
`python eval.py --trained_model=weights/yolact_base_54_800000.pth`

but the error occur as below:
**RuntimeError: /pytorch/torch/csrc/jit/fuser/cuda/fused_kernel.cpp:202: a PTX JIT compilation failed**

could you help me what it is?
Thanks!

**Comment by dbolya** [comment]
What python version do you have? You likely need to reinstall pytorch, since that typically happens when something in the pytorch command is corrupt. Try uninstalling pytorch and torchvision and installing from the following commands depending on your python version:

Python 3.5:
```
pip3 install https://download.pytorch.org/whl/cu100/torch-1.0.1-cp35-cp35m-linux_x86_64.whl
pip3 install https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp35-cp35m-linux_x86_64.whl
```

Python 3.6:
```
pip3 install https://download.pytorch.org/whl/cu100/torch-1.0.1-cp36-cp36m-linux_x86_64.whl
pip3 install https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl
```

Python 3.7:
```
pip3 install https://download.pytorch.org/whl/cu100/torch-1.0.1-cp37-cp37m-linux_x86_64.whl
pip3 install https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp37-cp37m-linux_x86_64.whl
```

(note: I'm assuming you're on linux here, lmk if not).

**Comment by cendelian** [comment]
> What python version do you have? You likely need to reinstall pytorch, since that typically happens when something in the pytorch command is corrupt. Try uninstalling pytorch and torchvision and installing from the following commands depending on your python version:
> 
> Python 3.5:
> 
> ```
> pip3 install https://download.pytorch.org/whl/cu100/torch-1.0.1-cp35-cp35m-linux_x86_64.whl
> pip3 install https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp35-cp35m-linux_x86_64.whl
> ```
> 
> Python 3.6:
> 
> ```
> pip3 install https://download.pytorch.org/whl/cu100/torch-1.0.1-cp36-cp36m-linux_x86_64.whl
> pip3 install https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl
> ```
> 
> Python 3.7:
> 
> ```
> pip3 install https://download.pytorch.org/whl/cu100/torch-1.0.1-cp37-cp37m-linux_x86_64.whl
> pip3 install https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp37-cp37m-linux_x86_64.whl
> ```
> 
> (note: I'm assuming you're on linux here, lmk if not).

Dear dbolya

Thanks for your advise.
I am torch-1.1.0       torchvision-0.2.0

what are the correct version of torch and torchvision?
Does the torch version must be 1.0.1?

Thanks

**Comment by dbolya** [comment]
Pytorch 1.0.1 is just faster and more memory-efficient, so I recommend using that (but 1.3 works too). If you want to continue using 1.1 (e.g., need it for other projects), just replace the 1.0.1 in those commands with 1.1.

And I don't think torchvision version matters, so you don't need to update that.

**Comment by dbolya** [comment]
You can try setting the environment variable `PYTORCH_JIT=0` and see if it works, but usually if you get that error it's not really JIT's fault.

**Comment by cendelian** [comment]
> You can try setting the environment variable `PYTORCH_JIT=0` and see if it works, but usually if you get that error it's not really JIT's fault.

Dear dbolya

Thanks

I solved the issue
the error is caused by torchvison
when I update torchvision to 0.2.2, there is no error.
Now my correct version is torch-1.2.0, torchvision-0.2.2

By the way, when torchvision is >= 0.3 , there will be some cuda error.
Thanks fpr your enthusiastic again.

**Comment by dbolya** [comment]
Glad you were able to fix it!

**Comment by jingtingxu369** [comment]
> > 您可以尝试设置环境变量`PYTORCH_JIT=0`，看看它是否有效，但是通常，如果您收到该错误，那实际上不是JIT的错。
> 
> 亲爱的dbolya
> 
> 谢谢
> 
> 我将
> torchvision 
> 更新为0.2.2时解决了错误是由torchvison引起的问题，没有错误。
> 现在我的正确版本是torch-1.2.0，torchvision-0.2.2
> 
> 顺便说一句，当torchvision> = 0.3时，会有一些cuda错误。
> 再次感谢您对fpr的热情。

What version of the cuda are you using?

**Comment by Zhang-O** [comment]
it is env problem.
check following 3 versions, you may find some inconsistence.
 torch.version.cuda  
cat /proc/driver/nvidia/version
cat /usr/local/cuda/version.txt
