### ISSUE TITLE
comparisons with other detectors

### ISSUE THREAD

**Issue by emjay73** [dbolya/yolact#179]
Dear dbolya,

Have you tried to compare your yolact with other detectors like YOLOV2, YOLOV3 or SSD?
If so, do you have figures like AP or fps?

**Comment by dbolya** [comment]
Yup. I'm going to add this figure to our appendix later, I just haven't gotten around to updating the paper yet:

![image](https://user-images.githubusercontent.com/19721752/67019663-0a19c880-f0cb-11e9-8ecc-086e17f90b40.png)
