### ISSUE TITLE
segmented object dimensions

### ISSUE THREAD

**Issue by aacmi** [dbolya/yolact#183]
Hi,
How to measure the segmented object dimensions inside bounding box? Is it possible to include point cloud library inorder to extract 3D information?
Any idea would be appreciated.

**Comment by dbolya** [comment]
By dimensions do you mean just the height and width? If so, that's easy, just get that from the predicted boxes here:
https://github.com/dbolya/yolact/blob/bd51ec9ef42389f60178fe729dfda3ad0f370f2f/eval.py#L149

The boxes are in point form, so to get the width and height do
```python
w, h = boxes[:, 2:] - boxes[:, :2]
```

Then I have no idea what you mean by incorporating point cloud data, so you'll have to do that yourself.

**Comment by aacmi** [comment]
This width and height values are not real object size. Since this is based on 2D information, it will not provide real object size. I'm trying to measure object size it is present. Thanks for your details, i will check this soon

**Comment by dbolya** [comment]
Yeah if you need 3d dimensions of an object, then YOLACT is probably not the method for you (since it's only operating on 2d images. You could probably incorporate 3d information for everything inside of a mask to discover 3d extents, but that's a research question in its own right, so I can't help you there.

Since this is out of the scope of YOLACT, I'm going to close the issue.

**Comment by sainatarajan** [comment]
@dbolya A similar issue. How can I get the predicted masks x,y coordinates? I had gone through the code of `eval.py` and you are already generating a `mask_detection.json` and `bbox_detection.json` file of it. But, I am not able to generate this file.

**Comment by dbolya** [comment]
@sainatarajan The mask x,y coordinates are just the box detection. If you want to create those files you mention, simple run evaluation with `--output_coco_json`.

**Comment by sainatarajan** [comment]
@dbolya I tried to run `eval.py` with that argument. But it does not generate any JSON file. It returns after calling the `evalimages()` function after this line: [line](https://github.com/dbolya/yolact/blob/bd51ec9ef42389f60178fe729dfda3ad0f370f2f/eval.py#L801)

**Comment by dbolya** [comment]
@sainatarajan Oh, that command only works when using a dataset (the 'has_gt' parameter can be False though).

For the case of an image-by-image basis, you can follow the call here: https://github.com/dbolya/yolact/blob/bd51ec9ef42389f60178fe729dfda3ad0f370f2f/eval.py#L565 and modify this line: https://github.com/dbolya/yolact/blob/bd51ec9ef42389f60178fe729dfda3ad0f370f2f/eval.py#L149 to save the boxes / masks like I suggested above.

**Comment by sainatarajan** [comment]
@dbolya Yes. It's working now. I am able to get the bounding box, classes, and scores information. Is it also possible to get the points of the predicted mask rather than the bounding box? If not, do you have any idea how can I get them?

**Comment by dbolya** [comment]
@sainatarajan The masks come as binary images. Under that line I gave you, simply put
```
masks_out = masks.cpu().numpy()
```
and you have them on the cpu. If you still want to do computations to them on the GPU with torch, you can just use `masks`.

**Comment by sainatarajan** [comment]
@dbolya That's good. Thanks. I will use some OpenCV techniques to get information about its coordinates.

**Comment by piseabhijeet** [comment]
> This width and height values are not real object size. Since this is based on 2D information, it will not provide real object size. I'm trying to measure object size it is present. Thanks for your details, i will check this soon

Hi, 

you can refer to :

https://github.com/dbolya/yolact/issues/606#issuecomment-829857227
