### ISSUE TITLE
duplicated boxes between classes all with high probabilities

### ISSUE THREAD

**Issue by xiaohong1** [dbolya/yolact#188]
Hi, Yolact works great with my datasets (prediction of oesophagus cancer). Thanks. But sometimes, I encountered duplicated boxed between classes (3 classes: high-grade (blue), suspicious (green), and cancer (red)). As shown in the picture. 
![duplicated-box--sample](https://user-images.githubusercontent.com/9080503/67518481-c875b880-f69c-11e9-9214-55bb8610d54b.jpg)
Whlie threshodling might help, those 3 boxed are all above the thresholds. How to keep the one with the highest probability. Thanks again.

**Comment by dbolya** [comment]
What you want is cross-class NMS (i.e., NMS that ignores class). I had it implemented at some point but due to some refactoring changes I removed it. Since it seems like it would be useful, I can reimplement it. I'll update this thread once I do.

**Comment by xiaohong1** [comment]
Great. Thanks a million.

**Comment by abhigoku10** [comment]
@dbolya  when can we expect this cross class NMS , even i am facing this issue with the problem statement

**Comment by dbolya** [comment]
@abhigoku10 Within a week (after ICCV)

**Comment by dbolya** [comment]
Ok I added cross-class fast NMS. Simply pull the latest commit and evaluate with the flag `--cross_class_nms=True`

Let me know if this works for you and then we can close the issue.

**Comment by xiaohong1** [comment]
The 'eval.py' does not seem to be implemented '--cross-class_nms' as I got the error 'eval.py: error: unrecognized arguments: --cross_class_nms=True'.
Many thanks again.

**Comment by dbolya** [comment]
Whoops forgot to commit the actual argument. Okay now it should work if you pull the latest master.

**Comment by xiaohong1** [comment]
I used the old trained model to evaluate the data and got the same results, i.e. still overlapping. Do I need to re-train the model using the new version of code. Adjusting thresholds helps. Once again, thanks a million.

**Comment by xiaohong1** [comment]
Sorry. Made a mistake by using an old file. It now works like a charm. Thanks a million. You can close the issue.

**Comment by dbolya** [comment]
Nice!

**Comment by abhigoku10** [comment]
@dbolya  thanks for this cross nms functionality , just wanted to understand crossnms is nms function for different class but it will have nms operation for the same class as well right ?

**Comment by dbolya** [comment]
@abhigoku10 Cross nms simply just ignores class while doing NMS. So you first assign a class to every box, then you do NMS on all the boxes together ignoring that class. The surviving boxes just get whatever class they were originally assigned.
