### ISSUE TITLE
Where  is the update paper?

### ISSUE THREAD

**Issue by stigma0617** [dbolya/yolact#190]
Hi, 

I really want to read your update paper. 

Where Can I find it ? Your arxiv paper is old version and the opened iccv paper does not include appendix.

**Comment by dbolya** [comment]
Ah it looks like even though I uploaded it on Thursday, Arxiv is not making it public until Monday. In the mean time, here's a copy:
[yolact_paper_v1_1.pdf](https://github.com/dbolya/yolact/files/3774364/yolact_paper_v1_1.pdf)
