### ISSUE TITLE
Congratulations on your great job and accptance of ICCV!!!

### ISSUE THREAD

**Issue by Wilbur529** [dbolya/yolact#192]
Hi, congratulate you on accptance of ICCV! YOLACT helped me a lot in the last half year, and i was so lucky to be able to meet your work several months ago.Hope everything goes your way ^-^

**Comment by dbolya** [comment]
Thank you very much, and glad YOLACT was able to help you! Hopefully YOLACT can continue to evolve to become even better :^ )
