### ISSUE TITLE
How to view the plots and loss graphs?

### ISSUE THREAD

**Issue by sainatarajan** [dbolya/yolact#193]
Is there a way to view the plots and loss graphs in tensorboard?

**Comment by dbolya** [comment]
Currently there isn't, but I can add a script to convert the log file to tensorboard. I'll add it to the post-ICCV Todo list.

**Comment by sainatarajan** [comment]
@dbolya Can you tell me what do each of these variables `B, C, M, S, T` means? I think T corresponds to `total_loss`. I want to know about others.

`B: 5.243 | C: 14.024 | M: 5.232 | S: 2.062 | T: 26.560`

**Comment by dbolya** [comment]
@sainatarajan Box, Class, Mask, Semantic Segmentation. The full key for all losses can be found here:
https://github.com/dbolya/yolact/blob/530415ff8a3f8f97b8deb58508ea74c84ea147b2/layers/modules/multibox_loss.py#L197

**Comment by niliuxi** [comment]
Where is the Todo list?

**Comment by dbolya** [comment]
@niliuxi It was in the notes app of my phone, but now I've upgraded it to a fancy Trello board. But it only includes this and cross-class nms so...

I'll probably start on this tomorrow.

**Comment by niliuxi** [comment]
Ok,thanks a lot.

**Comment by sainatarajan** [comment]
@dbolya I have used tensorboardX to write the loss values and then view the graphs in tensorboard. I think this is very easy and can be done manually. Thanks.
