### ISSUE TITLE
Could I just train object detection by yolact?

### ISSUE THREAD

**Issue by cendelian** [dbolya/yolact#196]
Hi dbolya

yolact can use for detection and segmentation, right?
But I just want to use it for detection or segmentation.
Can this be done?

**Comment by dbolya** [comment]
So you want to either display boxes or masks, but not both? You can do that, just use the argument `--display_bboxes=False` or `--display_masks=False`. If you don't want to run the mask branch you can also use the flag `--detect`, which will not run the mask branch (so it'll be faster).

If you want to train with just boxes, you can also add `'train_masks': False,` to the config (but you need boxes to train masks).

**Comment by cendelian** [comment]
> So you want to either display boxes or masks, but not both? You can do that, just use the argument `--display_bboxes=False` or `--display_masks=False`. If you don't want to run the mask branch you can also use the flag `--detect`, which will not run the mask branch (so it'll be faster).
> 
> If you're asking about your downstream task, then yeah you can just ignore the box or the segmentation based on what you want to do.
> 
> If you want to train with just boxes, you can also add `'train_masks': False,` to the config (but you need boxes to train masks).

Thanks dbolya,
I will close this issue
