### ISSUE TITLE
Ｎo valid data 

### ISSUE THREAD

**Issue by cendelian** [dbolya/yolact#200]
hi dbolya
when I train own data, if i no have valid data,
what i shoud write as below?  

```
 'valid_images': 'path_to_validation_images',
  'valid_info':   'path_to_validation_annotation',
```

**Comment by dbolya** [comment]
You can just put your training data for validation. Obviously, it won't give you generalization performance, but it'll still let you know if your model is training.

Alternatively, you can manually hold-out some portion of the data, but that's only if you want to experiment with yolact.

**Comment by cendelian** [comment]
> You can just put your training data for validation. Obviously, it won't give you generalization performance, but it'll still let you know if your model is training.
> 
> Alternatively, you can manually hold-out some portion of the data, but that's only if you want to experiment with yolact.

OK thank you,
I also found the information in Readme.txt.

by the way,
in the **config.py**. the **yolact_base_config** is below:
`yolact_base_config = coco_base_config.copy({
    'name': 'yolact_base',

    # Dataset stuff
    'dataset': coco2017_dataset,
    'num_classes': len(coco2017_dataset.class_names) + 1,

    # Image Size
    'max_size': 550,
    
    # Training params
    'lr_steps': (280000, 600000, 700000, 750000),
    'max_iter': 800000,
    
    # Backbone Settings
    'backbone': resnet101_backbone.copy({
        'selected_layers': list(range(1, 4)),
        'use_pixel_scales': True,
        'preapply_sqrt': False,
        'use_square_anchors': True, # This is for backward compatability with a bug

        'pred_aspect_ratios': [ [[1, 1/2, 2]] ]*5,
        'pred_scales': [[24], [48], [96], [192], [384]],
    }),`

the max_size 's default value is 550,
but my train image's size is 1280 * 720,
how i modify the code?
just modify the max_size to 1280 or more?

**Comment by dbolya** [comment]
Your images will be scaled down automatically, no need to worry about that. You can just leave it as is.

**Comment by cendelian** [comment]
> Your images will be scaled down automatically, no need to worry about that. You can just leave it as is.

Thanks,

now i train my data, but there is some error.
my GPU is GTX1050 2G
and I modify the batch_size =1.
then I run the command,
`python train.py --config=yolact_base_config --batch_size=1`

but it occur cuda error :
**RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 1.95 GiB total capacity; 1.17 GiB already allocated; 17.00 MiB free; 6.66 MiB cached)**

could you help me?

**Comment by dbolya** [comment]
Oh man your GPU is way too low tier to train the full model. One batch takes more memory than your card has total (1.95 GiB).

You won't be able to train the base model with this card at all, but you can try the resnet50 version. That should use less memory (just replace `yolact_base_config` with `yolact_resnet50_config`).

**Comment by cendelian** [comment]
> Oh man your GPU is way too low tier to train the full model. One batch takes more memory than your card has total (1.95 GiB).
> 
> You won't be able to train the base model with this card at all, but you can try the resnet50 version. That should use less memory (just replace `yolact_base_config` with `yolact_resnet50_config`).

Thanks for your quick answer
But after I change config with yolact_resnet50_config.
it occur same error...
maybe i can train the model at all because my pool GPU.
thanks again.

**Comment by dbolya** [comment]
Yeah sadly it would be quite a feat for any instance segmentation method to be able to train with only 2gb of vram. Masks themselves naturally take quite a lot of memory.

It might be possible to reduce the size of everything until a single batch fit in memory, but it would probably hurt performance a lot.

You asked before if you could just train YOLACT with detection. If just boxes would be good enough to do the task you need this for, then I'd recommend training YOLOv3 instead with just boxes (since you might be able to train that with your GPU).

**Comment by cendelian** [comment]
> Yeah sadly it would be quite a feat for any instance segmentation method to be able to train with only 2gb of vram. Masks themselves naturally take quite a lot of memory.
> 
> It might be possible to reduce the size of everything until a single batch fit in memory, but it would probably hurt performance a lot.
> 
> You asked before if you could just train YOLACT with detection. If just boxes would be good enough to do the task you need this for, then I'd recommend training YOLOv3 instead with just boxes (since you might be able to train that with your GPU).

thanks for your answer
I will close this issue.
Thanks again!

**Comment by cendelian** [comment]
Hi dbolya
Sorry to bother you again
I want to comfire something
**just replace yolact_base_config with yolact_resnet50_config**
about the words above you said,
do you mean as below?
`python train.py --config=yolact_resnet50_config --batch_size=1`

last time
I change is below:
`# cfg = yolact_base_config.copy()
cfg = yolact_resnet50_config.copy() #delian`
and run command
`python train.py --config=yolact_base_config --batch_size=1`
and it have cudy meory error.
**RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 1.95 GiB total capacity; 890.21 MiB already allocated; 21.94 MiB free; 3.79 MiB cached)**

but this time i only modify and run the command:
`python train.py --config=yolact_resnet50_config --batch_size=1`

there are other error:
**Traceback (most recent call last):
  File "train.py", line 382, in <module>
    train()
  File "train.py", line 165, in train
    yolact_net.init_weights(backbone_path=args.save_folder + cfg.backbone.path)
  File "/media/cendelian/Study/machine-learning/training-camp/L2/code/自动驾驶比赛/yolact/yolact.py", line 484, in init_weights
    self.backbone.init_backbone(backbone_path)
  File "/media/cendelian/Study/machine-learning/training-camp/L2/code/自动驾驶比赛/yolact/backbone.py", line 129, in init_backbone
    state_dict = torch.load(path)
  File "/home/cendelian/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/cendelian/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 563, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow**

**Comment by cendelian** [comment]
I think the correct is run command
`python train.py --config=yolact_resnet50_config --batch_size=1`
but there are some error.
could you help me?
I am so sorry for my pool knowledge and bother you again

**Comment by dbolya** [comment]
Oh yeah I meant to run
```python train.py --config=yolact_resnet50_config --batch_size=1```
so what you're doing now is correct.

I think the error might be because you don't have the pretrained weights for resnet50? You can grab it from the readme, but for convenience I'll paste it here:
> For Resnet50, download `resnet50-19c8e357.pth` from [here](https://drive.google.com/file/d/1Jy3yCdbatgXa5YYIdTCRrSV0S9V5g1rn/view?usp=sharing).

Just put this in your `weights/` folder like you did for ResNet101.

**Comment by cendelian** [comment]
> Oh yeah I meant to run
> `python train.py --config=yolact_resnet50_config --batch_size=1`
> so what you're doing now is correct.
> 
> I think the error might be because you don't have the pretrained weights for resnet50? You can grab it from the readme, but for convenience I'll paste it here:
> 
> > For Resnet50, download `resnet50-19c8e357.pth` from [here](https://drive.google.com/file/d/1Jy3yCdbatgXa5YYIdTCRrSV0S9V5g1rn/view?usp=sharing).
> 
> Just put this in your `weights/` folder like you did for ResNet101.
Yeah, I have resnet50-19c8e357.pth in ./weights.
but I have  **resnet50-19c8e357.pth**、 **yolact_base_54_800000.pth** and **resnet101_reducedfc.pth** in ./weights

Does the error is caused by three model in ./weights?
or it only **resnet50-19c8e357.pth** in ./weights is OK?

**Comment by cendelian** [comment]
> Oh yeah I meant to run
> `python train.py --config=yolact_resnet50_config --batch_size=1`
> so what you're doing now is correct.
> 
> I think the error might be because you don't have the pretrained weights for resnet50? You can grab it from the readme, but for convenience I'll paste it here:
> 
> > For Resnet50, download `resnet50-19c8e357.pth` from [here](https://drive.google.com/file/d/1Jy3yCdbatgXa5YYIdTCRrSV0S9V5g1rn/view?usp=sharing).
> 
> Just put this in your `weights/` folder like you did for ResNet101.


Yeah, I have resnet50-19c8e357.pth in ./weights.
but I have resnet50-19c8e357.pth、 yolact_base_54_800000.pth and resnet101_reducedfc.pth in ./weights

Does the error is caused by three model in ./weights?
or it only resnet50-19c8e357.pth in ./weights is OK?

**Comment by dbolya** [comment]
Hmm in that case, try redownloading resnet50-19c8e357.pth, since yours might be corrupt. There's no reason you should get that error for a valid weights file.

And having all 3 in that folder is fine, it's only trying to load resnet50-19c8e357.pth.

**Comment by cendelian** [comment]
> Hmm in that case, try redownloading resnet50-19c8e357.pth, since yours might be corrupt. There's no reason you should get that error for a valid weights file.
> 
> And having all 3 in that folder is fine, it's only trying to load resnet50-19c8e357.pth.

Thanks for your kind help. I will redownload  it later and try.

By the way.
I see resnet50-19c8e357.pth is resnet50-19c8e357.pth.tar, it have several file .
but resnet101 just is  resnet101_reducedfc.pth.

why resnet50-19c8e357.pth is different with resnet101_reducedfc.pth.
are there any difference in type?

**Comment by dbolya** [comment]
I think it depends on the compression, but pickle (and by extension torch.load) should be able to load both types just fine. I've been using resnet50 quite extensively for testing, and I haven't encountered any issues like this.

**Comment by cendelian** [comment]
> I think it depends on the compression, but pickle (and by extension torch.load) should be able to load both types just fine. I've been using resnet50 quite extensively for testing, and I haven't encountered any issues like this.

Thanks，now I run the command :
`python train.py --config=yolact_resnet50_config --batch_size=1` is correct,
and it can run sucess.

But there are other error:
**Traceback (most recent call last):
  File "train.py", line 382, in <module>
    train()
  File "train.py", line 257, in train
    losses = criterion(out, wrapper, wrapper.make_mask())
  File "/home/cendelian/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cendelian/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/cendelian/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/cendelian/Study/machine-learning/training-camp/L2/code/自动驾驶比赛/yolact/layers/modules/multibox_loss.py", line 180, in forward
    losses['C'] = self.ohem_conf_loss(conf_data, conf_t, pos, batch_size)
  File "/media/cendelian/Study/machine-learning/training-camp/L2/code/自动驾驶比赛/yolact/layers/modules/multibox_loss.py", line 243, in ohem_conf_loss
    loss_c = log_sum_exp(batch_conf) - batch_conf[:, 0]
  File "/media/cendelian/Study/machine-learning/training-camp/L2/code/自动驾驶比赛/yolact/layers/box_utils.py", line 279, in log_sum_exp
    x_max = x.data.max()
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/THCReduceAll.cuh:327**


are there any label setting is wrong?
the config.py I have add is below:
`# -----------------------Siweichuanxin-------------------------#

SIWEI_CLASSES = (
                'red', 'green', 'yellow', 'red_left', 'red_right', 'yellow_left', 'yellow_right',
                'green_left', 'green_right', 'red_forward', 'green_forward', 'yellow_forward',
                'horizon_red', 'horizon_green', 'horizon_yellow', 'off', 'traffic_sign',
                'car', 'motor', 'bike', 'bus', 'truck', 'suv', 'express', 'person',
                )


SIWEI_LABEL_MAP = { 1:  1,  2:  2,  3:  3,  4:  4,  5:  5,  6:  6,  7:  7,  8:  8,
                   9:  9, 10: 10, 11: 11, 12: 12, 13: 13, 14: 14, 15: 15, 16: 16,
                  17: 17, 18: 18, 19: 19, 20: 20, 21: 21, 22: 22, 23: 23, 24: 24,
                  25: 25,
                    }`

`my_dataset_base = Config({
    'name': 'Base Dataset',

    # Training images and annotations
    'train_images': './data/coco/images/',
    'train_info':   'path_to_annotation_file',

    # Validation images and annotations.
    'valid_images': './data/coco/images/',
    'valid_info':   'path_to_annotation_file',

    # Whether or not to load GT. If this is False, eval.py quantitative evaluation won't work.
    'has_gt': True,

    # A list of names for each of you classes.
    'class_names': SIWEI_CLASSES,

    # COCO class ids aren't sequential, so this is a bandage fix. If your ids aren't sequential,
    # provide a map from category_id -> index in class_names + 1 (the +1 is there because it's 1-indexed).
    # If not specified, this just assumes category ids start at 1 and increase sequentially.
    'label_map': None
})`

`siwei_dataset = my_dataset_base.copy({
    'name': 'siwei_dataset',

    'train_images': './data/siweichuanxin/images',
    'train_info':   './data/siweichuanxin/annotations/instances_train.json',

    'valid_images': './data/siweichuanxin/images',
    'valid_info':   './data/siweichuanxin/annotations/instances_train.json',

    'has_gt': True,
    'class_names': SIWEI_CLASSES,
    'label_map':SIWEI_LABEL_MAP
})`

`yolact_base_config = coco_base_config.copy({
    'name': 'yolact_base',

    # Dataset stuff
    'dataset': siwei_dataset,
    'num_classes': len(siwei_dataset.class_names) + 1,
    # 'dataset': coco2017_dataset,
    # 'num_classes': len(coco2017_dataset.class_names) + 1,

    # Image Size
    'max_size': 550,`

Is there any wrong?

**Comment by cendelian** [comment]
there are some error 
**/pytorch/aten/src/THCUNN/BCECriterion.cu:57: void bce_updateOutput_no_reduce_functor<Dtype, Acctype>::operator()(const Dtype *, const Dtype *, Dtype *) [with Dtype = float, Acctype = float]: block: [13,0,0], thread: [224,0,0] Assertion `*input >= 0. && *input <= 1.` failed.
/pytorch/aten/src/THCUNN/BCECriterion.cu:57: void bce_updateOutput_no_reduce_functor<Dtype, Acctype>::operator()(const Dtype *, const Dtype *, Dtype *) [with Dtype = float, Acctype = float]: block: [13,0,0], thread: [225,0,0] Assertion `*input >= 0. && *input <= 1.` failed.
/pytorch/aten/src/THCUNN/BCECriterion.cu:57: void bce_updateOutput_no_reduce_functor<Dtype, Acctype>::operator()(const Dtype *, const Dtype *, Dtype *) [with Dtype = float, Acctype = float]: block: [13,0,0], thread: [226,0,0] Assertion `*input >= 0. && *input <= 1.` failed.
/pytorch/aten/src/THCUNN/BCECriterion.cu:57: void bce_updateOutput_no_reduce_functor<Dtype, Acctype>::operator()(const Dtype *, const Dtype *, Dtype *) [with Dtype = float, Acctype = float]: block: [13,0,0], thread: [227,0,0] Assertion `*input >= 0. && *input <= 1.` failed.
/pytorch/aten/src/THCUNN/BCECriterion.cu:57: void bce_updateOutput_no_reduce_functor<Dtype, Acctype>::operator()(const Dtype *, const Dtype *, Dtype *) [with Dtype = float, Acctype = float]: block: [13,0,0], thread: [228,0,0] Assertion `*input >= 0. && *input <= 1.` failed.
/pytorch/aten/src/THCUNN/BCECriterion.cu:57: void bce_updateOutput_no_reduce_functor<Dtype, Acctype>::operator()(const Dtype *, const Dtype *, Dtype *) [with Dtype = float, Acctype = float]: block: [13,0,0], thread: [229,0,0] Assertion `*input >= 0. && *input <= 1.` failed.**

**Comment by dbolya** [comment]
Hmm that looks like it's caused by instability during training, probably because of that batch size of 1. Maybe to the config add `'freeze_bn': True,` (though that should be done automatically), and try fine-tuning instead of training from scratch. To do that, apply the change in #36 and then run:
```
python train.py --config=yolact_resnet50_config --resume=weights/yolact_resnet50_54_800000.pth --start_iter=0
```
(and you'll need to download the resnet50 pretrained weights for this).

**Comment by cendelian** [comment]
> Hmm that looks like it's caused by instability during training, probably because of that batch size of 1. Maybe to the config add `'freeze_bn': True,` (though that should be done automatically), and try fine-tuning instead of training from scratch. To do that, apply the change in #36 and then run:
> 
> ```
> python train.py --config=yolact_resnet50_config --resume=weights/yolact_resnet50_54_800000.pth --start_iter=0
> ```
> 
> (and you'll need to download the resnet50 pretrained weights for this).

Thanks a lot.

beause my poor gpu, now I run it with colab.
after i run the command:
`!python train.py --config=yolact_base_config --batch_size=5`

it display error:
Scaling parameters by 0.62 to account for a batch size of 5.
Per-GPU batch size is less than the recommended limit for batch norm. Disabling batch norm.
loading annotations into memory...
Done (t=3.19s)
creating index...
index created!
loading annotations into memory...
Done (t=0.19s)
creating index...
index created!
Traceback (most recent call last):
  File "train.py", line 501, in <module>
    train()
  File "train.py", line 184, in train
    yolact_net = Yolact()
  File "/content/drive/My Drive/Colab/siweichuanxin/yolact/yolact.py", line 475, in __init__
    self.fpn = FPN([src_channels[i] for i in self.selected_layers])
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1386, in init_then_register
    original_init(self, *args, **kwargs)
  File "/content/drive/My Drive/Colab/siweichuanxin/yolact/yolact.py", line 360, in __init__
    self.relu_downsample_layers = cfg.fpn.relu_downsample_layers
**AttributeError: 'Config' object has no attribute 'relu_downsample_layers'**

what error it is?
could you help me?

**Comment by cendelian** [comment]
By the way,
the torch version is 1.2.0
torchvision is 0.2.2

**Comment by dbolya** [comment]
Looks like you've updated Yolact without updating the config.py file (perhaps because you overwrote it with an older version). You can fix this by adding
```
'relu_downsample_layers': False,
'relu_pred_layers': True,
```
to `fpn_base` in the config file.

**Comment by cendelian** [comment]
> Looks like you've updated Yolact without updating the config.py file (perhaps because you overwrote it with an older version). You can fix this by adding
> 
> ```
> 'relu_downsample_layers': False,
> 'relu_pred_layers': True,
> ```
> 
> to `fpn_base` in the config file.

Yeah , I fix it by add the config you sent

but there are other error:
Scaling parameters by 0.62 to account for a batch size of 5.
Per-GPU batch size is less than the recommended limit for batch norm. Disabling batch norm.
loading annotations into memory...
Done (t=0.15s)
creating index...
index created!
loading annotations into memory...
Done (t=0.19s)
creating index...
index created!
Traceback (most recent call last):
  File "train.py", line 501, in <module>
    train()
  File "train.py", line 184, in train
    yolact_net = Yolact()
  File "/content/drive/My Drive/Colab/siweichuanxin/yolact111/yolact.py", line 493, in __init__
    index         = idx)
  File "/content/drive/My Drive/Colab/siweichuanxin/yolact111/yolact.py", line 137, in __init__
    if cfg.mask_proto_split_prototypes_by_head and cfg.mask_type == mask_type.lincomb:
**AttributeError: 'Config' object has no attribute 'mask_proto_split_prototypes_by_head'**

Sorry to bother you again and again.......

**Comment by dbolya** [comment]
Wow it looks like you have a really old version of the config file. It might be faster just to overwrite all the defaults. Can you overwrite `coco_base_config` in your config.py with the one from master?

From here:
https://github.com/dbolya/yolact/blob/2d5bef153506c3a8313e2e3a043a64c939ca37ee/data/config.py#L407

**Comment by cendelian** [comment]
> Wow it looks like you have a really old version of the config file. It might be faster just to overwrite all the defaults. Can you overwrite `coco_base_config` in your config.py with the one from master?
> 
> From here:
> https://github.com/dbolya/yolact/blob/2d5bef153506c3a8313e2e3a043a64c939ca37ee/data/config.py#L407

Do you mean I should update the config.py (only update coco_base_config is ok)?
because there something is different with before?

**Comment by dbolya** [comment]
Yes, I make very frequent updates to config.py, since I need to add a default there every time I add a new feature. It should be sufficient to just update `coco_base_config` for most things, since that's where the defaults are defined.

**Comment by cendelian** [comment]
> Yes, I make very frequent updates to config.py, since I need to add a default there every time I add a new feature. It should be sufficient to just update `coco_base_config` for most things, since that's where the defaults are defined.

Hi dbolya,
sorry to reply you late.
I change the config.py and it can work normally now.
thank very much for your help!
I close this issue

thank aganin!!

best regard

**Comment by saisubramani** [comment]
hi dbolya
I had trained the model with custom data set,with 6 classes.
i had made the alteration in config.py file, which was given in the Readme, and i successfully completed the training process for 800 iteration and i got the weight files also
**yolact_base_133_800.pth**

**config.py**
` Training params

    'lr_steps': (280, 600, 700, 750),
    'max_iter': 800,` 


While Evaluating it with the script **eval.py** with the trained weight file it showing the error

> Loading model...Traceback (most recent call last):
  File "eval.py", line 1098, in <module>
    net.load_weights(args.trained_model)
  File "/home/user_reorder01/Sai_Subramani/Programs/YOLACT/yolact/yolact.py", line 490, in load_weights
    self.load_state_dict(state_dict)
  File "/home/user_reorder01/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Yolact:
	size mismatch for prediction_layers.0.conf_layer.weight: copying a param with shape torch.Size([21, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([24, 256, 3, 3]).
	size mismatch for prediction_layers.0.conf_layer.bias: copying a param with shape torch.Size([21]) from checkpoint, the shape in current model is torch.Size([24]).
	size mismatch for semantic_seg_conv.weight: copying a param with shape torch.Size([6, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([7, 256, 1, 1]).
	size mismatch for semantic_seg_conv.bias: copying a param with shape torch.Size([6]) from checkpoint, the shape in current model is torch.Size([7]).

**Comment by Dhathri19** [comment]
Hello.

# Move up to the top level directory
%cd /content

# Delete any previous output_images folder (in case we're running this more than once)
!rm /content/output_images -r

# Create a new directory for output images
!mkdir -p /content/output_images

# Run inference using our pre-trained weights on all images in the directory
!python ./yolact/eval.py --trained_model=./yolact/weights/yolact_plus_resnet50_54_800000.pth --config=yolact_plus_resnet50_config --score_threshold=0.15 --top_k=15 --images=test_images:output_images

When I tried training yolact on google colab, I got the following error message. Kindy help me out.

/content
Loading model...Traceback (most recent call last):
  File "./yolact/eval.py", line 1098, in <module>
    net.load_weights(args.trained_model)
  File "/content/yolact/yolact.py", line 479, in load_weights
    state_dict = torch.load(path)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 525, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './yolact/weights/yolact_resnet50_54_800000.pth'

I would be really grateful.

**Comment by Dhathri19** [comment]
This is the error message that I got.

/content
Loading model...Traceback (most recent call last):
  File "./yolact/eval.py", line 1098, in <module>
    net.load_weights(args.trained_model)
  File "/content/yolact/yolact.py", line 479, in load_weights
    state_dict = torch.load(path)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 692, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
