### ISSUE TITLE
link for the COCO-style annotations is wrong

### ISSUE THREAD

**Issue by weberhen** [dbolya/yolact#203]
Hello,

I was trying to download the COCO-style annotations here: https://github.com/dbolya/yolact#pascal-sbd) but instead it points to yolact_resnet50_pascal_112_120000.pth. Could you please provide the correct link?

Thanks!

**Comment by dbolya** [comment]
Wow I didn't get an email for this issue, weird. I've since fixed it though so you should be good to go.
