### ISSUE TITLE
Why recognized as __ignore__:1.00

### ISSUE THREAD

**Issue by EchizenG** [dbolya/yolact#206]
Hello I just followed the steps(https://github.com/dbolya/yolact/issues/70#issuecomment-504283008) and training customers dataset guide. And then I got the objects were recognized as "__ignore__: 1.00" althrough I labeled them as box(some has 1 box some has multiple boxes).
And I can not delete the __ignore__ label in label.txt file.
Can you help me with this?
Thank you

**Comment by EchizenG** [comment]
And the overlap objects were recognized as a whole object.

**Comment by dbolya** [comment]
I'm not familiar with the labelme process whatsoever, so can you explain your problem in more detail? What are the steps you have done so far (e.g., is this after training or what), and what's the issue you want to fix (i.e., is this ignore a class that you created that you want to remove or what)?

**Comment by EchizenG** [comment]
> 我对标签过程一点都不熟悉，因此您可以更详细地说明问题吗？到目前为止，您已经执行了哪些步骤（例如，经过培训之后是什么？什么？），以及要解决的问题是什么（即，这是否忽略了您要删除的类？

Thank you

**Comment by EchizenG** [comment]
> I'm not familiar with the labelme process whatsoever, so can you explain your problem in more detail? What are the steps you have done so far (e.g., is this after training or what), and what's the issue you want to fix (i.e., is this ignore a class that you created that you want to remove or what)?

Thank you for your reply!
1. I followed the step (https://github.com/dbolya/yolact/issues/70#issuecomment-504283008) to label the image. But I didn't label the same class object as box-1, box-2 and etc. I just labeled it as box. 
2. fed the labeled dataset to train.py with batch_size=8. It's 48 images in 640*480 and I have one GPU (Tesla V100) on super computer. I could use 2 but just tried one. By the way, the ETA is almost same on RTX 2070.
3. The ETA was 7 days when epochs was 800,000. I adjusted it to 8000 and ETA is 2 hous.
4. After above training, I used the eval.py to load the .pth file. The prediction is like the title: recognized as __ignore__: 1.00.

Therefore, there are three problems:
1. What is the least epochs do we need generally? I guess 800,000 is much enough while the time is too long. This question might be case by case. But could you tell me your data that used in generally?
2. I labeled the object as box (only this class). And the labels.txt is only 3 labels: __ignore__, _background_ and box. But the inference is __ignore__ instead of box. I am doubting that it should be labeled as box-1, box-2, and etc. I will give the result when I finish the trying.
3. The output file's (.pth file) name is yolact_base_1333_2666.pth even I set the epoch as 8000. It should be yolact_base_8000_8000.pth, right?
Some questions might looks silly. Thank you for your patient!
>

**Comment by EchizenG** [comment]
![whole](https://user-images.githubusercontent.com/19619807/68617735-d9dd0400-0495-11ea-928b-6cc2cf5c65b0.png)
![instance](https://user-images.githubusercontent.com/19619807/68617736-d9dd0400-0495-11ea-891c-8a1df246d859.png)

**Comment by dbolya** [comment]
Could it just be that your class names are configured incorrectly? It looks like it's attempting to detect the boxes in the second image. Is there any image where this __ignore__ detection is supposed to be used? If not, then you can just rename whatever you have now as __ignore__ to box.

What does your dataset's "class_names" property look like?

Side note: it looks like box-1, box-2, box-3 is the way to go. Others were confused about that, so it's good to know.

**Comment by dbolya** [comment]
I. Can you share what your dataset config object looks like? (the one you defined in config.py). I think the problem might lie there and not with labelme, since my code can't output anything that's not defined in that object.

---

III. That's interesting. I'm not entirely sure how that's possible, but 1333 epochs is plenty anyway, so you probably don't have to worry about it.

**Comment by EchizenG** [comment]
I.
OMG! I realize it when I submit the config.py to github. When I see labels.txt I just copy it to 'class_name' which means it value is {'__ignore__', '_background_', 'box'}. I just find other class name doesn't include this 'useless' name. I'm retraining it right now. It should work!

Thank you anyway!
If it works, I will report it here and close it.

**Comment by dbolya** [comment]
Sounds good!

**Comment by EchizenG** [comment]
No, it doesn't work. My config.py is [here](https://github.com/EchizenG/yolact/blob/master/data/config.py)

Thank you

**Comment by dbolya** [comment]
Looks like you fell for a common Python pitfall! `('box')` doesn't create a tuple with one element, it's just parenthesis around a string so it's the string itself. Thus your classes will be `['b', 'o', 'x']`. To fix this change class names to `('box,')`.

I should probably change this to a list since many people are making the same mistake.

**Comment by EchizenG** [comment]
It worked!
Thank you a lot!!!

**Comment by hande6688** [comment]
@EchizenG 


How to label a single category with labelme? After looking at the user-defined data set, there is no annotation naming method. For example, there is only one category in a graph: cat, cat, cat or cat1, cat2, Cat3 or cat-0, cat-1, cat-2

**Comment by EchizenG** [comment]
> @EchizenG
> 
> How to label a single category with labelme? After looking at the user-defined data set, there is no annotation naming method. For example, there is only one category in a graph: cat, cat, cat or cat1, cat2, Cat3 or cat-0, cat-1, cat-2

Labelme has exhaustive steps to lead you label. What you mentioned "cat, cat, cat or cat1, cat2, Cat3" is not single category, it is 3 categories. However, according to the labelme rules, "cat-0, cat-1, cat-2" represents three objects in one category. you can try this one.

**Comment by hande6688** [comment]
@EchizenG 
I only have a single category. For example, if the name of the category is cat and the label is cat-0, cat-1, cat-2, is there any basis or difference?

**Comment by EchizenG** [comment]
> @EchizenG
> I only have a single category. For example, if the name of the category is cat and the label is cat-0, cat-1, cat-2, is there any basis or difference?

What do you mean basis or difference.
