### ISSUE TITLE
Parameter to reduce Non-Maximum Suppression?

### ISSUE THREAD

**Issue by sainatarajan** [dbolya/yolact#207]
Hi, Daniel. I have trained Yolact for my custom model and while the predictions are very accurate, there are redundant masks that are being generated. Suppose, I have 7 objects in an image, the no. of predictions are sometimes 7 or 8 or 9 i.e. two masks overlap for a single object. Is there any parameter in Yolact that I could use to remove the non-maximum suppression.

**Comment by dbolya** [comment]
Yup, you can. There are 3 config settings that control NMS:
```
    # Top_k examples to consider for NMS
    'nms_top_k': 200,
    # Examples with confidence less than this are not considered by NMS
    'nms_conf_thresh': 0.05,
    # Boxes with IoU overlap greater than this threshold will be culled during NMS
    'nms_thresh': 0.5,
```
You can try changing `nms_thresh` to something lower that suits your data.

**Comment by sainatarajan** [comment]
@dbolya Thanks for this. I will try it out and see. One more question. Is it possible to parallelize the prediction process instead of sequentially reading the images one by one and then performing prediction?

**Comment by dbolya** [comment]
There is, but it's complicated. See `evalvideo` in eval.py for details. It's for video, but you could replace the cv2 vid object with something that returns images from disks, and replace the cv2.imshow with saving the image to the disk.

**Comment by sainatarajan** [comment]
@dbolya Thanks, Daniel. I will check that out. As you said, the `evalvideo()` looks complicated indeed. I am closing this issue now.
