### ISSUE TITLE
no ScatterWrapper() in train.py

### ISSUE THREAD

**Issue by wb315** [dbolya/yolact#209]
why no ScatterWrapper() function in train.py

**Comment by dbolya** [comment]
Huh? I replaced ScatterWrapper with a custom implementation of DataParallel that does what scatterwrapper did better and faster. Have you updated all files to the latest master?

**Comment by HuangLian126** [comment]
@dbolya  I have the same question. In the 146-th line of train.py, I find the function scatter( ). Do you replace ScatterWrapper with scatter ? and how to use scatter? Thanks.

**Comment by dbolya** [comment]
I switched from pytorch's implementation to my own which is more efficient for what I'm using it for. ScatterWrapper was a hack to get pytorch's implementation to work properly with my data, but in the end it was better and more efficient to write my own scatter.
