### ISSUE TITLE
B and M loss remain zero

### ISSUE THREAD

**Issue by agneevguin** [dbolya/yolact#219]
@dbolya I am using a custom dataset reduced to the max_size 550.
The B: Box Localization Loss and M: Mask Loss seem to remain constant at 0. The other losses are varying. There could be several reasons for this. Maybe you can guide me a bit.
Is this an explainable error, or does it sound like a bug in my dataset generation?

**Comment by dbolya** [comment]
Did you update your boxes and masks to match your new 550x550 images?

**Comment by agneevguin** [comment]
Yes I have. Here's the reference for others help.
`# Jsons listed in an txt file
# Looped on each line of Json filename

# Check if file size is > 0
if (os.stat(line.strip()).st_size) > 0:
    # Read the Json
    result = json.load(open(line.strip(), 'r'))
    # Read all details
    dataset['info'] = result['info']
    dataset['licenses'] = result['licenses']
    items_annotations = []
    for annos in result['annotations']:
        try:
            if annos:
                for anno in annos:
                    if anno:
                        ### Modifications for rescaled images
                        img_height = result['images']['height']
                        img_width = result['images']['width']
                        sw, sh = (550 / img_width, 550 / img_height)
                        x, y, w, h = anno['bbox']
                        anno['bbox'] = [(int) (sw * x), (int) (sh * y), (int) (sw * w), (int) (sh * h)]
                        anno['segmentation'] = [[(int)((sw, sh)[idx % 2] * x) for idx, x in enumerate(p)]
                                                for p in anno['segmentation']]
                        anno['area'] = (int)((int)(sw * w)*(int)(sh * h))
                        items_annotations.append(anno)
        # If any exception
        except Exception as exc:
            print(traceback.format_exc())               
            print(exc)
    # Fix other details
    dataset['images'] = result['images']
    fix_filename = result['images']['file_name']
    if '.jpg' in fix_filename:
        fix_filename = fix_filename.replace('.jpg', '_550.jpg')
    if '.png' in fix_filename:
        fix_filename = fix_filename.replace('.png', '_550.png')
    dataset['images']['file_name'] = fix_filename
    dataset['images']['height'] = 550
    dataset['images']['width'] = 550
    dataset['annotations'] = items_annotations
    dataset['categories'] = result['categories']

    # Print time status.
    print('Done (t={:0.2f}s)'.format(time.time() - tic))

    # Save the Json files as individual Json files.
    with open(line_new, 'w') as outfile:
        json.dump(dataset, outfile)`

**Comment by dbolya** [comment]
Thanks for the script!

Have you verified that the output is correct? You have a lot of casts to int there, so there my be a point where you accidentally cast something < 1 to an int.

**Comment by agneevguin** [comment]
You're right. My bbox and segmentation range was from 0 to 550 instead of 1 to 550.
The training seems to work for now. I am closing the ticket until there is a new blockage.

**Comment by bhuvanofc** [comment]
@agneevguin @dbolya I have images of 600 * 800. should I have to resize my images to 550 * 500 and also labels according to that before training or the network will take care of it?
