### ISSUE TITLE
Training on Coco sub-classes

### ISSUE THREAD

**Issue by TBondat** [dbolya/yolact#221]
Hi,
First, thanks for the amazing work you have done! This is very valuable work.

I would like to reduce the classes predicted to  only some of them, to avoid unnecessary objects. I would like to keep basically like 6,7 classes from COCO original classes. So i will update the config file as you recommend in the readme and issue #36 to do fine-tuning. But i have two questions before:
- To get the same results accuracy as it is now o nthe classes im interested, is it ok to just run like one or two epochs for the training? if i restart from the last weights, it should be enough right?
- Did you stop the training at 800k iterations because after it was overfitting? If i continue the training for my subset during thousand iter, can i expect improving the results for my 7 classes?

thanks in advance for the help!

**Comment by dbolya** [comment]
If you want to reduce the number of classes still using COCO, you have 2 options:
1. Simply remove the COCO annotations in the annotation JSON that aren't part of the classes you want. In this case, the number of classes will still be 80, just most of them won't have examples so they shouldn't be predicted. This has the benefit in that you can restart from the pretrained weights immediately and train just another 2 epochs like you said, but there's an off chance it predicts something outside of the 6-7. Of course, you could just ignore those detections.
2. Reduce the number of classes total to 6-7. This would require retraining the last layer (you can see how to do fine tuning here: #36), and it requires you to modify the label map to map the 90ish COCO category ids down 1-6 or 7. So in general more effort and requires retraining the last layer, but the network cannot predict outside of the subset.

Since you're just using the COCO classes anyway I recommend 1 (which sounds like what you wanted to do anyway).

As for why 800k, because of data augmentation we never overfit. After 800k though we saw no benefit from extra training (just remained the same performance), so you should be good to train a couple more epochs.

**Comment by TBondat** [comment]
i started with option 1, but as you say, it get some unwanted classes of course. i did filter for the bbox display but for mask it is more tricky as you did some optimization on this par tof the code.
So, i'm trying the option 2 instead to have a more proper solution. 

I try training with this call:
python3.6 train.py --config=yolact_base_config --resume=weights/yolact_base_54_800000.pth --start_iter=-1 --batch_size=3

I don't fully understand how is set the max_iter. couple of time the training doesn't start and give directly the evaluation results. I wanted to do for instance 10iterations only. So i guess one epoch at least is mandatory?
But even by setting 200000 max iter is doing the same thing whereas it is more than one epoch.
max_iter 400k seems ok. How is done the threshold to do or not the training exactly?

thanks for the support

**Comment by TBondat** [comment]
ok, with my custom coco, it brings an error that sizes doesn't fit, when i resume:
Original exception was:
Traceback (most recent call last):
  File "train.py", line 503, in <module>
    train()
  File "train.py", line 206, in train
    yolact_net.load_weights(args.resume)
  File "/home/re44417/THIERRY_PROJETS/AA_RIG_FILES/ndt/ros/src/camera_publisher/scripts/yolact.py", line 527, in load_weights
    self.load_state_dict(state_dict)
  File "/home/re44417/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Yolact:
	size mismatch for prediction_layers.0.conf_layer.weight: copying a param with shape torch.Size([243, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([27, 256, 3, 3]).
	size mismatch for prediction_layers.0.conf_layer.bias: copying a param with shape torch.Size([243]) from checkpoint, the shape in current model is torch.Size([27]).
	size mismatch for semantic_seg_conv.weight: copying a param with shape torch.Size([80, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([8, 256, 1, 1]).
	size mismatch for semantic_seg_conv.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([8]).

in config,py, here is what i did:
sub classes and sub label:
COCO_CLASSES_sub = ('person', 'bicycle', 'car', 'motorcycle', 'bus',
                'truck', 'traffic light','stop sign')
COCO_LABEL_MAP_sub = { 1:  1,  2:  2,  3:  3,  4:  4,  6:  5,  8:  6, 10: 7,  13: 8}
then, sub dataset:
coco2017_dataset_sub = dataset_base.copy({
    'name': 'COCO 2017',
    
    'train_info': './data/coco/annotations/instances_train2017_sub.json',
    'valid_info': './data/coco/annotations/instances_val2017_sub.json',

    'label_map': COCO_LABEL_MAP_sub,
    'class_names': COCO_CLASSES_sub
})

then, hijacked the yolact_base_config:
yolact_base_config = coco_base_config.copy({
    'name': 'yolact_base',

    # Dataset stuff - coco2017_dataset_sub.class_names
    'dataset': coco2017_dataset_sub,
    'num_classes': len(coco2017_dataset_sub.label_map) + 1,

    # Image Size
    'max_size': 550,
    
    # Training params
    'lr_steps': (280000, 600000, 700000, 750000),
    'max_iter': 400000,
    etc.....

If i run a training from scratch, so without the resume option, it is running. but of course, if i can avoid days of training it would be the best :D 
Any idea?

**Comment by dbolya** [comment]
For the resume option, you want `--start_iter=0` which starts counting from 0. What was happening was the model was instead picking up from where it left off, which is at iteration 800k and thus it thought it was already finished.

As for the error, that's expected. See #36 to what to add so that it just ignores that error (the size mismatch is because, well there's a size mismatch, apply the code in the issue to get it to ignore that mismatch and you should be good to go for training).

Your config looks good, but I would recommend dividing every step in lr_steps by 2 to accommodate the fewer number of iterations.

**Comment by TBondat** [comment]
yes of course!! i focused on the config.py file and then forgot the basic try/catch error :(
Thanks for support, it is running now!

i don't know if it is normal, but it doesn't restart at the same loss level as you had (~ 601240 || B: 1.362 | C: 1.919 | M: 2.314 | S: 0.396 | T: 5.991 from what i saw in another github issue).
it restarted at higher loss level. after 500iterations, i'm at B: 3.123 | C: 3.131 | M: 4.290 | S: 0.430 | T: 10.973 level.
Now maybe the comparison is not fair as it is not the complete COCO data i'm training on (~71k images).
i divided the learning rates by 2 as you advised.

what do you think?

**Comment by dbolya** [comment]
Because of data augmentation and random shuffling, the loss can be very different from iteration to iteration, though the fact that you end with the loss 2x higher is a little worrying. Did everything work out in the end?

**Comment by TBondat** [comment]
no, i have tested fine tuning and from scratch. i usually finish to 7-8 total loss (map mask ~21). im testing now just with one class, car also but it seems doing the same. I check the data with pycocotools and they are ok.

In my case, i can only afford buffer size of 3, and it displays that the batch norm is disable because of that. Could it come from that?

**Comment by dbolya** [comment]
Batch size of 3 is pretty small, but disabling batch norm should only result in a ~1 mAP loss, not ruin the method entirely. If the loss is increasing from the pretrained weights that drastically, there might be an issue with your configuration.

**Comment by TBondat** [comment]
what could i adjust except the learning rate? i didn't change anything else from the default config yolact.
Actually about the lr, there are 4 coefficients. How are spread these lr over the network layers? It is to know if it is better to tune just some of the lr maybe?

I will try to run the training on a workstation where i could train on better graphical card, so i can compare then if i get same behavior!

**Comment by dbolya** [comment]
I'd just adjust the steps to be the same proportion to how many iterations you're training. So if you're training with 200k iterations, then 280,000 would become 280000/800000*200000.

I'd do a sanity check first of 1.) Try training the original config with no modifications, and 2.) Try training a config with only 1 class removed to check if there's similar performance.

**Comment by TBondat** [comment]
yes i will try to do that!

**Comment by TBondat** [comment]
ok, @dbolya , so i finally ran yolact on a workstation with 4 TitanX. It works much better, i didn't get any problem. So it seems that having a very low batch size (3 in my case) and/or the batch_norm layer disabled brings some troubles in the training.
on the workstation i used the 4 gpus with total 32 batch size, and i got good results with yolact_base, doing fine-tuning
Calculating mAP...

       |  all  |  .50  |  .55  |  .60  |  .65  |  .70  |  .75  |  .80  |  .85  |  .90  |  .95  |
-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
   box | 33.76 | 54.49 | 52.07 | 49.09 | 45.49 | 41.35 | 36.21 | 28.87 | 20.00 |  9.07 |  0.96 |
  mask | 30.86 | 49.86 | 47.52 | 44.37 | 41.09 | 37.03 | 32.24 | 26.50 | 18.84 |  9.48 |  1.67 |
-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+

[ 61]  223510 || B: 1.362 | C: 1.811 | M: 2.344 | S: 0.320 | T: 5.837 || ETA: 0:31:20 || timer: 0.931
actually it gave slightly higher MaP than the default file right? 30.8 instead of 29.8. or am I wrong?

Then, doing training with my subcoco dataset (8 classes) gave reasonable good results too, from what i see for now.

**Comment by dbolya** [comment]
Yup that's higher than what's reported in the paper. I've noticed that training with more gpus ends up performing better overall (though this effect is slight), so your results make sense. Since everything seems to be working now, I'll close the issue, but if something else comes up, feel free to reopen.

**Comment by hyunas1996** [comment]
I'm sorry for interrupting in here, but @TBondat  do you remember how long did it take for learning till 220000 iterations with 4 Titanx?

**Comment by TBondat** [comment]
hi, sorry @hyunas1996 , as i haven't retrained it since december, i don't remember how long took the training! maybe one or two days. It is going quite fast with 4 titanx ^^

**Comment by hyunas1996** [comment]
Thanks for your answer! 
I have one more question.😂
If you can remember the training process, does the mAP grows from small numbers like 1 or 2?
I hope to get numbers like what you got above😂

**Comment by TBondat** [comment]
not if you start from the trained model, and so just do fine-tuning i guess. From scratch, i don't remember, but if it was starting at 1-2 mAP, it should increases quickly at the beginning!

**Comment by hyunas1996** [comment]
python train.py --config='my config' --dataset='my dataset' --resume=weights/yolact_plus_resnet50_54_800000.pth --start_iter=0 --batch_size=32 --num_workers=4 --batch_alloc=8,8,8,8

my command was this. Then I think this means fine tuning job.
Am I right? Thanks for answering so much!

**Comment by TBondat** [comment]
yes, you start training from the weights you give as input, with the --resume keyword!
