### ISSUE TITLE
Train from resnet101_reducedfc.pth, something was wrong

### ISSUE THREAD

**Issue by ljjyxz123** [dbolya/yolact#225]
If I train yolact from yolact_base_54_800000.pth on, when I visualize the instance masks, they are shown as below:
![pred_masks_32](https://user-images.githubusercontent.com/2631417/69793202-edf96300-1202-11ea-9de5-6ddc104cb9ae.jpg)
![pred_masks_24](https://user-images.githubusercontent.com/2631417/69793209-f18cea00-1202-11ea-8038-3f47d6f3eef7.jpg)

It's fine.

-----
But if I was training yolact from resnet101_reducedfc.pth on, using the command:

CUDA_VISIBLE_DEVICES=0 python train.py --config=yolact_base_config

After 31210 iterations, I got the instance visualization result as almost all gray:

![pred_masks_40](https://user-images.githubusercontent.com/2631417/69793327-2dc04a80-1203-11ea-84c7-59695ddb46d6.jpg)
![pred_masks_34](https://user-images.githubusercontent.com/2631417/69793330-2ef17780-1203-11ea-9fdf-2d25caeb91af.jpg)
![pred_masks_93](https://user-images.githubusercontent.com/2631417/69793337-3153d180-1203-11ea-93b9-3f7df3be1e5e.jpg)

Does anyone know why?
Thanks!

**Comment by dbolya** [comment]
How much data do you have, and did the loss explode when training from `resnet101_reducedfc.pth`? YOLACT is typically trained for 800k iterations which is a lot more than 31k, but that does look way off from what it should be at 31k.

**Comment by ljjyxz123** [comment]
> How much data do you have, and did the loss explode when training from `resnet101_reducedfc.pth`? YOLACT is typically trained for 800k iterations which is a lot more than 31k, but that does look way off from what it should be at 31k.

@dbolya  I used COCO dataset to train yolact, and you are right, if I train from `resnet101_reducedfc.pth', the loss will explode after several hours. 

If I train yolact from `yolact_resnet50_800000.pht', the loss will not explode.

My training environment is :
1. GPUs: 8 GPUs, each is a RTX 2080Ti;
2. training command: python train.py --config=yolact_base_config (this command is using `resnet101_reducedfc.pth' in default)

Is there anything I need to pay attention if I want to train yolact from scratch?
Thank you very much!

**Comment by dbolya** [comment]
Oh you should be multiplying your batch size by the number of GPUs: try training with `--batch_size 64`.

**Comment by ljjyxz123** [comment]
> Oh you should be multiplying your batch size by the number of GPUs (8 for 1 gpu, so 64 for 8 gpus): try training with `--batch_size 64`.

@dbolya 
I tried it on our server, but when I use batch_size as 8, the average GPU usage is 2GB.
So for RTX 2080Ti, I can maximumly use 4 * 8 = 32 as my maximum batch_size.

Why does batch_size influence the loss explosion so much?
Thank you.

**Comment by dbolya** [comment]
I'll responded to this (since it's basically the same underlying issue) in your other thread (#234).

**Comment by ljjyxz123** [comment]
> I'll responded to this (since it's basically the same underlying issue) in your other thread (#234).

@dbolya 
Okay, thank you very much!

**Comment by hana9090** [comment]
Hi @ljjyxz123  What do you mean by 

> yolact_resnet50_800000.pth? 
Did you use the backbone as > yolact_resnet50_800000.pth model?
