### ISSUE TITLE
How to open camera?

### ISSUE THREAD

**Issue by Merofine** [dbolya/yolact#23]

**Comment by Merofine** [comment]
Is there a command which can open camera please?

**Comment by Merofine** [comment]
Why it is too slow~ 
python eval.py --trained_model=weights/yolact_im700_54_800000.pth --score_threshold=0.3 --top_k=100 --video=Bear.mp4:output_video.mp4
Config not specified. Parsed yolact_im700_config from the file name.

Loading model... Done.
Processing Frames  ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░      3 /     45 ( 6.67%)    14Processing Frames  ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░      4 /     45 ( 8.89%)    14Processing Frames  ███░░░░░░░░░░░░░░░░░░░░░░░░░░░      5 /     45 (11.11%)    14Processing Frames  ████░░░░░░░░░░░░░░░░░░░░░░░░░░      6 /     45 (13.33%)    13Processing Frames  ████░░░░░░░░░░░░░░░░░░░░░░░░░░      7 /     45 (15.56%)    14Processing Frames  █████░░░░░░░░░░░░░░░░░░░░░░░░░      8 /     45 (17.78%)    14Processing Frames  ██████░░░░░░░░░░░░░░░░░░░░░░░░      9 /     45 (20.00%)    14Processing Frames  ██████░░░░░░░░░░░░░░░░░░░░░░░░     10 /     45 (22.22%)    14Processing Frames  ███████░░░░░░░░░░░░░░░░░░░░░░░     11 /     45 (24.44%)    14Processing Frames  ████████░░░░░░░░░░░░░░░░░░░░░░     12 /     45 (26.67%)    14Processing Frames  ████████░░░░░░░░░░░░░░░░░░░░░░     13 /     45 (28.89%)    14Processing Frames  █████████░░░░░░░░░░░░░░░░░░░░░     14 /     45 (31.11%)    14Processing Frames  ██████████░░░░░░░░░░░░░░░░░░░░     15 /     45 (33.33%)    14Processing Frames  ██████████░░░░░░░░░░░░░░░░░░░░     16 /     45 (35.56%)    14Processing Frames  ███████████░░░░░░░░░░░░░░░░░░░     17 /     45 (37.78%)    14Processing Frames  ████████████░░░░░░░░░░░░░░░░░░     18 /     45 (40.00%)    14Processing Frames  ████████████░░░░░░░░░░░░░░░░░░     19 /     45 (42.22%)    14Processing Frames  █████████████░░░░░░░░░░░░░░░░░     20 /     45 (44.44%)    14Processing Frames  ██████████████░░░░░░░░░░░░░░░░     21 /     45 (46.67%)    14Processing Frames  ██████████████░░░░░░░░░░░░░░░░     22 /     45 (48.89%)    14Processing Frames  ███████████████░░░░░░░░░░░░░░░     23 /     45 (51.11%)    14Processing Frames  ████████████████░░░░░░░░░░░░░░     24 /     45 (53.33%)    14Processing Frames  ████████████████░░░░░░░░░░░░░░     25 /     45 (55.56%)    14Processing Frames  █████████████████░░░░░░░░░░░░░     26 /     45 (57.78%)    14Processing Frames  ██████████████████░░░░░░░░░░░░     27 /     45 (60.00%)    14Processing Frames  ██████████████████░░░░░░░░░░░░     28 /     45 (62.22%)    14Processing Frames  ███████████████████░░░░░░░░░░░     29 /     45 (64.44%)    14Processing Frames  ████████████████████░░░░░░░░░░     30 /     45 (66.67%)    14Processing Frames  ████████████████████░░░░░░░░░░     31 /     45 (68.89%)    14Processing Frames  █████████████████████░░░░░░░░░     32 /     45 (71.11%)    14Processing Frames  ██████████████████████░░░░░░░░     33 /     45 (73.33%)    14Processing Frames  ██████████████████████░░░░░░░░     34 /     45 (75.56%)    14Processing Frames  ███████████████████████░░░░░░░     35 /     45 (77.78%)    14Processing Frames  ████████████████████████░░░░░░     36 /     45 (80.00%)    14Processing Frames  ████████████████████████░░░░░░     37 /     45 (82.22%)    14Processing Frames  █████████████████████████░░░░░     38 /     45 (84.44%)    14Processing Frames  ██████████████████████████░░░░     39 /     45 (86.67%)    14Processing Frames  ██████████████████████████░░░░     40 /     45 (88.89%)    14Processing Frames  ███████████████████████████░░░     41 /     45 (91.11%)    14Processing Frames  ████████████████████████████░░     42 /     45 (93.33%)    14Processing Frames  ████████████████████████████░░     43 /     45 (95.56%)    14Processing Frames  █████████████████████████████░     44 /     45 (97.78%)    14Processing Frames  ██████████████████████████████     45 /     45 (100.00%)    14.15 fps

**Comment by Wilbur529** [comment]
`vid = cv2.VideoCapture(0)`
Use opencv-python. Just like this~

**Comment by dbolya** [comment]
Thanks for the suggestion. In the latest commit, use `--video=0` to use a webcam. If you have multiple, replace `0` by the index of the webcam you want to use.

**Comment by harrybolingot** [comment]
Is there a way to set the webcam input resolution to a certain number? :)
I want to test the performance on 1920x1080 webcam video (for testing the real-time performance).

**Comment by dbolya** [comment]
You can set the resolution of the webcam after this line:
https://github.com/dbolya/yolact/blob/6e22d1b1ccbeab4001bc6acd9124f5a679083d21/eval.py#L606
Add:
```
    vid.set(cv2.CAP_PROP_FRAME_WIDTH, 1920)
    vid.set(cv2.CAP_PROP_FRAME_HEIGHT, 1080)
```
I haven't tested this though so it might not be correct. Some people online say that you need to use some absurd resolution to get your webcam's maximum, so if that doesn't give you 1920p then try 10000 x 10000 or something. For more [see this post](https://stackoverflow.com/questions/19448078/python-opencv-access-webcam-maximum-resolution)

**Comment by JianJingGao** [comment]
but i try set be camera path is rtsp , process not read frame,please help look look
