### ISSUE TITLE
Output COCO-style JSON Annotation for single images in eval.py

### ISSUE THREAD

**Issue by AlexanderMelde** [dbolya/yolact#230]
Hi @dbolya, 
thank you for this great piece of software. I already used it, to generate images with drawn masks using the inference script `eval.py` on single images and folders. This worked fine. Now after getting the images, i wanted to programmatically use the inference results, which is why i would need a coco style json file instead of an png as an output.

I already saw there is the `args.output_coco_json` parameter, but looking at the code, it seems to only work when evaluating whole datasets (with ground truth available?) and not for single images or folders of single images, without annotations.

What i would like to do, is calling eval.py similar to this:

```
--config=yolact_base_config
--trained_model=weights/yolact_base_54_800000.pth
--output_coco_json
--bbox_det_file=myimage.bbox.json
--mask_det_file=myimage.mask.json
--score_threshold=0.2 --top_k=15
--image=myimage.png:myimage_out.png
```

(with only `myimage.png`, `yolact_base_config` and `weights/yolact_base_54_800000.pth` already existing.) 

i also tried putting the following additional parameters into the arguments:

```
--mask_proto_debug
--dataset=coco2017_testdev_dataset
```

but they did not help, as the coco style dumping function in eval.py (https://github.com/dbolya/yolact/blob/02bde378e98cd7e2831639ff782c1f5a5046771a/eval.py#L960) does not get executed when `--image` is set (see https://github.com/dbolya/yolact/blob/02bde378e98cd7e2831639ff782c1f5a5046771a/eval.py#L855).

Is there any other way i can use arguments to reveice a coco style json file with annotations for a single image or a folder of images?
If not, please regard this as a feature request :)
Kind Regards
Alexander

**Comment by dbolya** [comment]
The way `--output_coco_json` works right now is it operates on a dataset (which doesn't need to have ground truth). So you need to give a `--dataset` parameter instead of an `--image` parameter. The dataset you use doesn't need annotations, simply create a COCO dataset with just images and an empty annotation array and follow the dataset definition of `coco2017_testdev_dataset`.

For single images, this is kind of cumbersome, but for large batches it probably works fine? This feature was intended for submission to the COCO eval servers so that's why it's so roundabout. Let me know if this is indeed too cumbersome, and I can add `--output_coco_json` support to `--image`.

**Comment by AlexanderMelde** [comment]
Thank you very much! 
I will try and get back to you. 
Will take a while though as i now have found a workaround for my usecase, so i will close this for now :)

**Comment by ritesh2212** [comment]
> Thank you very much!
> I will try and get back to you.
> Will take a while though as i now have found a workaround for my usecase, so i will close this for now :)

Hi,
Did you tried --dataset parameter. As I'm getting the same error as you have mentioned. If yes, can you share the code?

**Comment by AlexanderMelde** [comment]
> > Thank you very much!
> > I will try and get back to you.
> > Will take a while though as i now have found a workaround for my usecase, so i will close this for now :)
> 
> Hi,
> Did you tried --dataset parameter. As I'm getting the same error as you have mentioned. If yes, can you share the code?

Hi Ritesh,

i have not tried it yet, there was a change of priorities in our project and i think we won't need this anymore. Sorry I can't help you.

Kind Regards
Alexander

**Comment by Harut0726** [comment]
> The way `--output_coco_json` works right now is it operates on a dataset (which doesn't need to have ground truth). So you need to give a `--dataset` parameter instead of an `--image` parameter. The dataset you use doesn't need annotations, simply create a COCO dataset with just images and an empty annotation array and follow the dataset definition of `coco2017_testdev_dataset`.
> 
> For single images, this is kind of cumbersome, but for large batches it probably works fine? This feature was intended for submission to the COCO eval servers so that's why it's so roundabout. Let me know if this is indeed too cumbersome, and I can add `--output_coco_json` support to `--image`.

Sorry, could you clarify how should define the dataset in this case?
I am trying the following:
```javascript
my_dataset = coco2017_testdev_dataset.copy({
    'name': 'My  Dataset',
    'train_images':  'folder_to_coco',
    'train_info': None,

    'valid_images': 'folder_to_coco',
    'valid_info': None,

    'has_gt': True,
    'class_names': my_cat_array,
    'label_map': None
})
```

But I get error:
```python
Loading model... Done.
Traceback (most recent call last):
  File "eval.py", line 1131, in <module>
    evaluate(net, dataset)
  File "eval.py", line 923, in evaluate
    progress_bar = ProgressBar(30, dataset_size)
  File "./utils/functions.py", line 60, in __init__
    self._update_str()
  File "./utils/functions.py", line 76, in _update_str
    num_bars = int(self.length * (self.cur_val / self.max_val))
ZeroDivisionError: division by zero
```

**Comment by downhiller** [comment]
> The way `--output_coco_json` works right now is it operates on a dataset (which doesn't need to have ground truth). So you need to give a `--dataset` parameter instead of an `--image` parameter. The dataset you use doesn't need annotations, simply create a COCO dataset with just images and an empty annotation array and follow the dataset definition of `coco2017_testdev_dataset`.
> 
> For single images, this is kind of cumbersome, but for large batches it probably works fine? This feature was intended for submission to the COCO eval servers so that's why it's so roundabout. Let me know if this is indeed too cumbersome, and I can add `--output_coco_json` support to `--image`.

It's too cumbersome, please add json output to --image use ;)

(I've created my own dataset, but cv2.imgread seems to be failing for some reason.  I've verified that the path is correct, yet I get `'NoneType' object has no attribute 'shape'` :-(

**Comment by linyingyingkarina** [comment]
> > The way `--output_coco_json` works right now is it operates on a dataset (which doesn't need to have ground truth). So you need to give a `--dataset` parameter instead of an `--image` parameter. The dataset you use doesn't need annotations, simply create a COCO dataset with just images and an empty annotation array and follow the dataset definition of `coco2017_testdev_dataset`.
> > For single images, this is kind of cumbersome, but for large batches it probably works fine? This feature was intended for submission to the COCO eval servers so that's why it's so roundabout. Let me know if this is indeed too cumbersome, and I can add `--output_coco_json` support to `--image`.
> 
> It's too cumbersome, please add `json` output to `--image` use ;)
> 
> (I've created my own dataset, but ` if target.shape[0] == 0:` is failing, as target = `[]`. What am I doing wrong?)

hey, I also failed in 'ig target.shape[0]==0', how can fix? thanks
