### ISSUE TITLE
A problem in traditional NMS.

### ISSUE THREAD

**Issue by Wilbur529** [dbolya/yolact#24]
https://github.com/dbolya/yolact/blob/d8ddaa1a157f8d162db54751a7ff4373614515b5/layers/functions/detection.py#L189

I thought there is a mistake in the implementation of traditional_nms. When NMS finished, did the boxes  need to be rescaled into [0, 1]?

**Comment by dbolya** [comment]
Oh huh yeah you're right, thanks for pointing that out. Maybe I should have tested that function more...
Pushed a fix.
