### ISSUE TITLE
Yolact freezes after first prediction in eval.py 

### ISSUE THREAD

**Issue by dipinoch** [dbolya/yolact#240]
I am running Yolact using video feed from a Realsense 415 camera (np array from color image data). Yolact freezes with our an error after the third frame. It only shows one frame and one prediction and then nothing.  
The video feed is streamed though a socket into yolact. 

Any clue what might cause the issue

**Comment by dbolya** [comment]
Does it spit out an error message? Also are you using multiple GPUs? If so try running `export CUDA_VISIBLE_DEVICES=0` (or whichever gpu you want to use) first.

**Comment by dipinoch** [comment]
Actually I got it working , I am using an http server to stream to yolact the video feed and depth data to an open gl app (using an Intel Realsense camera). Now , the problem is that the frame rate starts really good and over time the frame rate decreases a lot. after 10 seconds it starts reducing the fps (28 at the beginning ) to a really bad 5 fps. I am using a dual 1080ti config.

**Comment by dbolya** [comment]
Are you running this on one of your GPUs (with `CUDA_VISIBLE_DEVICES=0`) or both? Video output is not well optimized for multiple GPUs (especially for live footage), so maybe that's the issue?

**Comment by lukasld** [comment]
Hi there,
thank you first of all for yolact, we are trying to implement it using it for pointcloud segmentation. 
I am working with dipinoch on the same project. 
We tried to update the CUDA_VISIBLE_DEVICES environment variable to use only one card, unfortunately however the results were the same. Setting jit to True in yolact.py did not change that eigher. As mentioned,  we use an http server that streams rgb and poincloud data. When opening the port on the browser, we experience little to no lag when rendering from the stream. 
In yolact, using opencv however, the framerate drops after 5 seconds and the frames in the buffer also deplete completely. We are simply not quite sure, whether this is simply a cv2 problem or an issue on how yolact hanldes the streamed frames. Any hint or suggestion is appreciated, thank you!

**Comment by lukasld** [comment]
I found a hacky - rather inefficient workaround for now.
If someone else runs into the same issue - it has to do on how cv2 deals with video-streams. It seemingly is very bad at handling its own buffer. 
I open a new connection each time in get_next_frame, then I close it. So the code looks like this:

``
def get_next_frame(vid):
    ...
    vid = cv2.VIdeocapture('URL')
    frame = vid.read[1]
    vid.release()
``

**Comment by dbolya** [comment]
Yeah I've had problems with opencv in the past. It seems to be very inefficient at a lot of things, which is kind of why I want to switch that code to use OpenGL but that has the issue of not being compatible with everyone's environments.

Sorry I wasn't able to offer much help, but since this seems to be an opencv issue I'll close it. Feel free to reopen if something else comes up.

**Comment by areebsyed** [comment]
@dipinoch how did you get it running after the first issue? I am also stuck where the saved video of live stream saves nothing after the first prediction. It shows the prediction on next frames when being played live but it doesnt save anything after the first frame
