### ISSUE TITLE
Export all the bboxes of images

### ISSUE THREAD

**Issue by cendelian** [dbolya/yolact#244]
hi, dbolya

I want to test my own datasets and export the bboxes and class's score of every test image,
Is there any script can do it?

Thanks!

**Comment by dbolya** [comment]
See #230

**Comment by bayraktare** [comment]
Hi, I have the same request. 
I have also checked the #230 but it didn't work for me.
I want to save this line with the read images [https://github.com/dbolya/yolact/blob/f38e14b2953c32eede479a9fa68997604769f3ed/eval.py#L156](url)
Please can you explain more explicitly giving the examples, how to save the outputs of this line with the --images case with the images names? For example, a couple of lines of .txt file would seem: 
/path/to/image1.jpg class1 score1 bb1 bb2 bb3 bb4
/path/to/image1.jpg class2 score2 bb5 bb6 bb7 bb8
as long as the same image can have more than one detected objects.

**Comment by dbolya** [comment]
Good question about the image path. Honestly, your best bet without tearing up the code too much is to write the path into a global variable in `evalimage` (`--image` handler) and then do what you were doing before in `prep_display`. The exact same thing would work with `evalvideo` (`--video` handler) since it also uses `prep_display`.

**Comment by bayraktare** [comment]
I think I found some other solution as follows:
added a variable, let's say '_imgpath_', into `evalimage` and modified `img_numpy = ...` to be as `img_numpy = prep_display(preds, frame, **imgpath**, ...)`. Afterwards, added this '_imgpath_' to `prep_display` as the third input.

So I have all the things with me at `prep_display`. Then I added the following lines to get the txt or some other format as I wanted before: 
`for i in range(boxes):
 print('%s %s %f %d %d %d %d' % (imgpath, class, score, bb1, bb2, bb3, bb4), file=f)`

But, I couldn't figure out how can I do this for the live stream from the webcam?
Can you please give some hints and suggestions?

**Comment by dbolya** [comment]
Sounds reasonable. The webcam stream uses `evalvideo`. In there is a function that runs `prep_display`. There's a bunch of multithreaded shenanigans going on there but if you have `--video_multiframe=1` only one thread will be running `prep_display` at a time so there shouldn't be any race conditions.
