### ISSUE TITLE
Did YOLACT use FP16? FP32?  INT8?

### ISSUE THREAD

**Issue by sdimantsd** [dbolya/yolact#247]
How can i change it?

**Comment by sdimantsd** [comment]
I get it. FP32 :-)

**Comment by leemengwei** [comment]
> I get it. FP32 :-)

@sdimantsd  , where did u find it ? THANKS

**Comment by sdimantsd** [comment]
@leemengwei 
Search in the code for 
`torch.set_default_tensor_type`
Also you can use [yolact_edge](https://github.com/haotian-liu/yolact_edge) if you want to speed up the network (about 3 - 4 times faster)

**Comment by leemengwei** [comment]
> torch.set_default_tensor_type

thanks
