### ISSUE TITLE
fpn structure

### ISSUE THREAD

**Issue by dlllll-q** [dbolya/yolact#250]
Hi, firstly thank you for your wonderful work. I have a question about model structure, 
![yolact_resnet50_54_800000 pth (1)](https://user-images.githubusercontent.com/58542898/70968556-7e291a80-20d4-11ea-9b19-8a5fc01af089.png)
[Digraph.gv.pdf](https://github.com/dbolya/yolact/files/3971638/Digraph.gv.pdf)
![1](https://user-images.githubusercontent.com/58542898/70968797-32c33c00-20d5-11ea-976d-29b859c3abdc.png)
![2](https://user-images.githubusercontent.com/58542898/70968809-38b91d00-20d5-11ea-9c72-0e9affe207ec.png)

I use two tools to view the structure which backbone is resnet50, in the first one which is constructed by the code(sorry, i forget the name of tool), and the second one is constructed by netron using  yolact_resnet50_54_800000.pth. And the other two are the part of the picture. My doubt is that there are two fpn.downsample_layers in Digraph while there are three fpn.downsample_layers in yolact_resnet50_54. Why they are different? (I did not modify the parameters in config)

**Comment by dbolya** [comment]
Ah yeah good catch. That's because our original architecture had 3 downsample layers but we found the final downsample layer to be doing absolutely nothing (removing it after training didn't affect the mAP but increased the speed slightly), so we removed it. If you train a new network from scratch it won't have this extra downsample in the state dict, so that's just there as a remnant of older code.

**Comment by dlllll-q** [comment]
oh, thank you for your reply!

**Comment by abhigoku10** [comment]
@dlllll-q  can you please share the name of the tool used to view this model architecture , this would be helpful . THanks in advance

**Comment by xuchengggg** [comment]
The first tool to use the pytorch code to construct the architecture is called pytorchviz, and the second one use the weights to view the architecture is called netron. Hope it will be helpful for you.

**Comment by lbq779660843** [comment]
> @abhigoku10 The first tool to use the pytorch code to construct the architecture is called pytorchviz, and the second one use the weights to view the architecture is called netron. Hope it will be helpful for you.

Hi, your works are excellent. Can you tell us the way how to use pytorchviz to visualise the structure or just share the code？So many thanks!

**Comment by abhigoku10** [comment]
@lbq779660843  i did not use pytrochviz , i used pyan to obtain the graph . you can check it out https://github.com/davidfraser/pyan

**Comment by lbq779660843** [comment]
@abhigoku10 
Hi, I've loaded an onnx model by using the model of [https://github.com/Ma-Dan/yolact](url) in netron succefully.
I found that we seem have the same goal according to your judgements in other issues, so can u add me in your social network to discuss some problems?
Thanx！

**Comment by abhigoku10** [comment]
@lbq779660843 sure please share your wechat number  i shall get connected to u

**Comment by lbq779660843** [comment]
@abhigoku10 
My wechat:
lbq920506

**Comment by abhigoku10** [comment]
> @abhigoku10
> My wechat:
> lbq920506

i am not able to find you on wechat can you please check the number

**Comment by lbq779660843** [comment]
@abhigoku10 
QQ: 779660843

**Comment by lbq779660843** [comment]
@abhigoku10 
I'm sure of it, plz check it again!

**Comment by abhigoku10** [comment]
@lbq779660843 hi i have sent a request to you yesterday only !! do accept it
