### ISSUE TITLE
About the deformable convolution in YOLACT++?

### ISSUE THREAD

**Issue by feiyuhuahuo** [dbolya/yolact#255]
In table 5, is the deformable conv for yolact-resnet50 also 'interval=3'? 
![image](https://user-images.githubusercontent.com/32631344/71067939-79399900-21b0-11ea-9449-031fe49301a3.png)
If so, I noticed that the AP gain for yolact-resnet101 after doing DCN is 1.6, but for yolact-resnet50, it's 2.8. Then, it can be supposed that DCN can help to improve the weights utilization rate. That is, DCN made the network use weights more efficiently.  For deeper resnet101, it can just use more weights to compensate the inflexibility of traditional conv, so the AP gain brought from DCN is not so obvious. Do you agree with this?

**Comment by dbolya** [comment]
The resnet version uses an interval of 1, so I'm not sure if they're directly comparable like that.
