### ISSUE TITLE
Calling Yolact from another Python file

### ISSUE THREAD

**Issue by bayraktare** [dbolya/yolact#256]
Hi @dbolya,
Thanks again for such a useful model.
I am trying to use yolact inside another file and I will use its outputs in terms of masks, bounding-boxes, confidence rates and classes. 
But it gives errors when I `import yolact.eval` --> `ImportError: cannot import name 'Yolact'`
If I `import yolact`, there is no error. If I `from yolact import eval` --> `ImportError: cannot import name 'Yolact'`, it gives the same error. 
After `import yolact` without no errors, I type `yolact` and it gives ` <module 'yolact' (namespace)>`. But if I import another lib, it shows the path to that.
How can I call eval.py from another python file and use its outputs?
By the way my config is python 3.6, pytorch 1.0.1, cuda 9.0...

**Comment by abhigoku10** [comment]
@bayraktare hi this is good thought , just wanted to understand are you trying to import yolact in another pipeline of python or are you calling it for c++

**Comment by dbolya** [comment]
What does your final structure look like? It sounds like you're importing `yolact.py` not importing from the yolact directory. Though that's actually what you want (importing yolact.py, that is).

Here's the rough procedure:
```python
import torch
import cv2 # Optional, see below

from yolact import Yolact
from data import set_cfg
from utils.augmentations import FastBaseTransform
from layers.output_utils import postprocess

##### Setup #####

# CUDA setup, I should really just replace all Tensor initializations but I'm in too deep at this point
torch.backends.cudnn.fastest = True
torch.set_default_tensor_type('torch.cuda.FloatTensor')

# Use whichever config you want here.
set_cfg('yolact_base_config')

net = Yolact().cuda()
net.load_weights('path/to/weight/file')
net.eval()

transform = FastBaseTransform()

##### Now to use ######

# Get your image from somewhere (BGR format, [0, 255], numpy)
img = cv2.imread('path/to/image')
h, w, _ = img.shape

batch = transform(torch.from_numpy(img).cuda().float()[None, ...])
preds = net(batch)

# You can modify the score threshold to your liking
classes, scores, boxes, masks = postprocess(preds , w, h, score_threshold=0.15)
```

Sorry for the number of lines of code necessary to do this. I should probably make an example script and put it on the readme or something. (Also this code is untested, if there are any bugs lmk).

**Comment by bayraktare** [comment]
hi @abhigoku10 yes i am trying to import it in another python pipeline.
and thanks for the reply @dbolya i will let you know right after testing this.

**Comment by bayraktare** [comment]
Hey @dbolya,  I have run the code and the first thing I figured out is that only `yolact_base_54_800000 and yolact_im700_54_800000` are running without errors as weights.
The second thing with this code appears at the line `preds = net(batch)` as you can see in the following i am copy-pasting:
`Traceback (most recent call last):
  File "demo.py", line 45, in <module>
    preds = net(batch)
  File "/home/bayraktare/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File ".../yolact/yolact.py", line 705, in forward
    return self.detect(pred_outs)
  File ".../yolact/layers/functions/detection.py", line 71, in __call__
    result = self.detect(batch_idx, conf_preds, decoded_boxes, mask_data, inst_data)
  File ".../yolact/layers/functions/detection.py", line 103, in detect
    boxes, masks, classes, scores = self.traditional_nms(boxes, masks, scores, self.nms_thresh, self.conf_thresh)
  File ".../yolact/layers/functions/detection.py", line 208, in traditional_nms
    preds = torch.cat([boxes[conf_mask], cls_scores[:, None]], dim=1).cpu().numpy()
RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.`

**Comment by bayraktare** [comment]
In addition to above recommendation of @dbolya and my last edit, adding necessary paths and appending them to current directory you try run the python file solved my problem.

**Comment by Ira236** [comment]
@bayraktare would you share your demo-file? I have the same problems and don't know what to do.. :(

**Comment by melaanya** [comment]
I'm using Pytorch 1.3.1 and for me it worked to do the following.

You can avoid explicit calling when calling the model to eval from another Python file
`torch.set_default_tensor_type('torch.cuda.FloatTensor')` 
if you fix the following lines.

In layers/functions/detection.py, line 210
it was `keep = torch.Tensor(keep, device=boxes.device).long()`
and it became `keep = torch.Tensor(keep).to(boxes.device).long()`

In yolact.py, line 248
it was `self.priors = torch.Tensor(prior_data, device=device).view(-1, 4).detach()`
and it became `self.priors = torch.Tensor(prior_data).view(-1, 4).to(device).detach()`

Now I can predict with the yolact model without setting the default tensor type as `torch.cuda.FloatTensor` as it hurts other parts of my script.

**Comment by Auth0rM0rgan** [comment]
Hey @bayraktare, 
I'm trying to use Yolact in another python file and I'm facing this error  
> AttributeError: 'Config' object has no attribute 'mask_proto_debug'
How did you solve this error?

Thanks!

**Comment by Auth0rM0rgan** [comment]
Hey @dbolya, I'm getting this error `Config' object has no attribute 'mask_proto_debug` same as @bayraktare. Do you know how can I solve it? Thanks.

**Comment by Auth0rM0rgan** [comment]
Hey @dbolya, 
I'm able to call yolact from another python file and everything is working perfectly. I want to know how can I set the `top_k` in my new python file? Thanks

**Comment by dbolya** [comment]
@Auth0rM0rgan You can use the same snippet `eval.py` uses:
```
idx = t[1].argsort(0, descending=True)[:top_k]
classes, scores, boxes, masks = [x[idx] for x in t]
```
Though this is something that should natively be in the API once we make one.

**Comment by zyxdb** [comment]
> In addition to above recommendation of @dbolya and my last edit, adding necessary paths and appending them to current directory you try run the python file solved my problem.

Hey, I have a similar problem:
AttributeError: 'Config' object has no attribute 'mask_proto_debug'

I want to know what you said "necessary paths" and "current directory",I only see two places in the code where I need to fill the path,(weights and img)

**Comment by Kacperk6** [comment]
@zyxdb 
> Hey, I have a similar problem:
> AttributeError: 'Config' object has no attribute 'mask_proto_debug'
> 
> I want to know what you said "necessary paths" and "current directory",I only see two places in the code where I need to fill the path,(weights and img)

For a lack of better solution (or rather inability to find one), I just commented calling `mask_proto_debug` out in `output_utils.py` line 63:
```
#if cfg.mask_proto_debug:
        #    np.save('scripts/proto.npy', proto_data.cpu().numpy())
```
"Fixed" the problem without any devastating consequences (for now)

**Comment by MahmoudKounyahli** [comment]
this is my script, to recognize objecte in an image, someone can help me
```python
from yolact import Yolact
import cv2
from layers.output_utils import postprocess
from data import cfg, set_cfg, set_dataset
import torch
import os
from utils.augmentations import BaseTransform, FastBaseTransform, Resize


def main():

    torch.backends.cudnn.fastest = True
    torch.set_default_tensor_type('torch.cuda.FloatTensor')


ROOT_DIR = os.path.dirname(os.path.abspath(__file__)).replace("\\", "/")
WEIGHT_DIR = ROOT_DIR + "/weights/"

if __name__ == '__main__':
    main()

    print('Loading model...', end='')

    net = Yolact().cuda()
    cfg = "yolact_plus_resnet50" + '_config'
    set_cfg(cfg)
    net.load_weights(WEIGHT_DIR + "yolact_plus_resnet50_54_800000.pth")

    net.eval()
    print(' Done.')
    transform = FastBaseTransform()

    img_path = ROOT_DIR + "/test_images/123.jpg"

    img = cv2.imread(img_path)
    h, w, _ = img.shape
    scale_percernt = 20
    width = int(w * scale_percernt / 100)
    height = int(h * scale_percernt / 100)
    dim = (width, height)
    resized_img = cv2.resize(img, dim, interpolation=cv2.INTER_AREA)
   
    batch = transform(torch.from_numpy(resized_img).cuda().float()[None, ...])
    preds = net(batch)

    with torch.no_grad():
        classes, scores, boxes, masks = postprocess(preds, width, height, score_threshold=0.15)
        print(classes)
    cv2.destroyAllWindows()
```
but I always get the tensor empty
`oading model... Done.
tensor([])`

**Comment by Mahmoudi1993** [comment]
Hi @dbolya
It is possible to crop and save the detected images in the YOLACT++.

**Comment by Mahmoudi1993** [comment]
Hi @dbolya 
It is possible to crop and save the detected images in the YOLACT++.

**Comment by Mahmoudi1993** [comment]
Hi @bayraktare
It is possible to crop and save the detected images in the YOLACT++.

**Comment by Mahmoudi1993** [comment]
Hi

Please answer this question
😌😌😌
It is possible to crop and save the detected images in the YOLACT++.?
