### ISSUE TITLE
 method 'bailout' is called recursively. Recursive calls are not supported.

### ISSUE THREAD

**Issue by jinfagang** [dbolya/yolact#261]
Eval on video got error:

```
 method 'bailout' is called recursively. Recursive calls are not supported.

```

**Comment by dbolya** [comment]
No idea why that would happen, but a quick google search says that it might have something to do with JIT? You might want to try disabling pytorch JIT.

Regardless, it doesn't seem to be a YOLACT-specific error, so I'll close this issue.
