### ISSUE TITLE
How does same class different instances distinguished?

### ISSUE THREAD

**Issue by jinfagang** [dbolya/yolact#262]
![image](https://user-images.githubusercontent.com/21303438/71316692-cf5b5480-24ae-11ea-99c7-6436c20ad2e5.png)

I logged out sizes of output:

```
INFO 12.22 11:31:34 demo.py:65: boxes: (15, 4)
INFO 12.22 11:31:34 demo.py:66: masks: torch.Size([15, 720, 1280])
INFO 12.22 11:31:34 demo.py:67: scores: (15,)
```

Seems every mask contains more than one instance.

This got a situation that, some mask didn't have mask related with it:

![image](https://user-images.githubusercontent.com/21303438/71316700-2d883780-24af-11ea-9748-a6f11126088b.png)

how to remove those separate masks that does instance or does have box related with it?

**Comment by abhigoku10** [comment]
@jinfagang  hi did u run these inference in the cpu or in the gpu ?? since i also used to face this issue when i run the eval.py in the cpu settings

**Comment by jinfagang** [comment]
I think nothing to do with cpu or GPU.

predictions on mask is not instance level since there were a lot of spots that not have a box bounding it.

**Comment by Naturalvolume** [comment]
Hello, how do you output only the mask. Can it be output directly？

**Comment by jinfagang** [comment]
@Naturalvolume  aas you can see the mask shape:

```
masks: torch.Size([15, 720, 1280])
```

I am only visualized channel by channel

**Comment by Ira236** [comment]
@jinfagang did you solve the issue with the overlapping masks? I'm facing the same issue :( don't understand what's wrong, because I get almost perfect bboxes..

**Comment by dbolya** [comment]
This is the kind of output you get when you don't crop the resulting masks. The model is trained with cropping, so it leverages that fact and doesn't bother segmenting out instances that are on the other side of the image for instance.

What it's learned is that it only needs to supress instance boundaries when boxes overlap, which is exactly what you're seeing in that image (notice the masks of different colors stop at the boundaries between objects). Essentially, the model doing as little instance segmentation as it can get away with and it lets cropping do the rest. Naturally, there will be errors but that's life ¯\\\_(ツ)\_/¯

Make sure you crop before you visualize.

**Comment by jinfagang** [comment]
@dbolya thanks for your reply. May I ask what do mean by crop? if I am not crop, the boundry that model does care will output masks while doesn't have box coordinate with it? As I can see, even in the middle part of image, there were masks that without a box bounding it.

**Comment by dbolya** [comment]
@jinfagang The model produces boxes and masks together. It doesn't produce one mask for the entire image and then cut it up, it produces individual masks custom tailored each bounding boxes, so you can't have one without the other: notice how there are 15 mask channels and 15 boxes.

If you see something there in a mask but there's no box associated with it, then it's just leakage from another box. However, there's a possibility that there's another box associated with that car in the middle. You can try decreasing the score threshold or increasing the top_k (I'm assuming you set top_k to 15 here).

**Comment by basit26374** [comment]
@jinfagang can you please share me specifically that you can create a binary mask?
I would like to crop white/ segmented object save into database.

**Comment by dbolya** [comment]
@basit26374 See #286

**Comment by hande6688** [comment]
@dbolya 

How to label a single category with labelme? After looking at the user-defined data set, there is no annotation naming method. For example, there is only one category in a graph: cat, cat, cat or CAT1, cat2, Cat3 or cat-0, cat-1, cat
