### ISSUE TITLE
Mask Generation and Transfer learning

### ISSUE THREAD

**Issue by abhigoku10** [dbolya/yolact#264]
@dbolya  hi i have trained a model with the new repo i.e yolact on a custom dataset and i am having few issues with the model 
1. the Mask mAP is very low around 0.64 while box mAP is 26.4
2. Visually i am getting only the bounding boxes but only smal section of the mask or no section of the mask 
3. The training is performed from scratch with image net weight on BDD100K dataset
4.Can i give the COCO pretrained weight and resume the training for BDD100K data

THanks in advance

**Comment by dbolya** [comment]
Is this with the YOLACT++ model or the original YOLACT model. The original YOLACT model shouldn't have changed at all with this update, so that would be worrying if there's a problem.

For 4., yes that should work as long as you do the fine tuning change in #36.

**Comment by abhigoku10** [comment]
@dbolya  this is for yolact and i debugged it and was able to solve the issue there was an bug when i converted my annotation from labelme to coco format , in which the height and width has be interchanged . shall close this issues

**Comment by ankitsharma07** [comment]
@abhigoku10 How did you convert the annotation from LabelMe to COCO format?

**Comment by abhigoku10** [comment]
@ankitsharma07  using pycoco tools default
