### ISSUE TITLE
A solution for TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by XXSL980102** [dbolya/yolact#266]
When I evaluate this model on my own video, I found that here exists an error if your inputs don't have any object:
 
`Traceback (most recent call last):
  File "eval.py", line 1107, in <module>
    evaluate(net, dataset)
  File "eval.py", line 892, in evaluate
    evalvideo(net, inp, out)
  File "eval.py", line 804, in evalvideo
    active_frames = [{'value': extract_frame(first_batch, i), 'idx': 0} for i in range(len(first_batch[0]))]
  File "eval.py", line 804, in <listcomp>
    active_frames = [{'value': extract_frame(first_batch, i), 'idx': 0} for i in range(len(first_batch[0]))]
  File "eval.py", line 793, in <lambda>
    extract_frame = lambda x, i: (x[0][i] if x[1][i] is None else x[0][i].to(x[1][i]['detection']['box'].device), [x[1][i]])    # ['detection']
TypeError: 'NoneType' object is not subscriptable
`

To solve this problem, you need to add **['detection']** after x[1][i]:
> extract_frame = lambda x, i: (x[0][i] if x[1][i] is None else x[0][i].to(x[1][i]['detection']['box'].device), [x[1][i]])
> extract_frame = lambda x, i: (x[0][i] if x[1][i]['detection'] is None else x[0][i].to(x[1][i]['detection']['box'].device), [x[1][i]])

**Comment by dbolya** [comment]
Whoops! That's quite a silly error to make. I'll commit that fix shortly, thanks!
