### ISSUE TITLE
Save/Visualise mask separately for image and also calculate perfomance on GPU.

### ISSUE THREAD

**Issue by vatsalkansara2** [dbolya/yolact#268]
Hi,
I found your work interesting and works best as per my knowledge of any instance segmentation algorithm.But I want to store mask separately for image so I wanted to know that how will i be able to do that.

I have done changes to line 203 to 211 and changed some code for img_gpu and set it to masks color summened.it shows output correctly but I wanted to know that is it correct way?

Also, I wanted to calculate running time for single input image 
I tried using python time.time() for timestamping before and after line 602 ( **preds = net(batch)** )in **eval.py**
but it outputs ~300ms on my Nvidia 1080Ti with 11Gb Graphics.

**Comment by dbolya** [comment]
You can potentially save masks in COCO's RLE format using --output_coco_json during a normal eval, but you need to set up a dataset for that. There's no standard way to just plug in an image and get masks out yet. What you did is probably the hacky solution I would have suggested anyway, but a better solution might be to use the code in #256 to run YOLACT without any of the rest of the fluff and just directly save the output.

For your second question, pytorch initializes everything on the first pass through, so you have to run the model at least once for it to initialize, then you can start timing the next frame.

**Comment by vatsalkansara2** [comment]
Thank You for reply! model runs faster after running the first frame.
