### ISSUE TITLE
How can i export coordinates of bbox and segmented pixel?

### ISSUE THREAD

**Issue by onoderay** [dbolya/yolact#276]
Hello I'm very naive about this deep learning field but we appreciate really nice work.
we want to custom your script and here is question, how can i export coordinates of bbox and segmented pixel?? we want to export txt or csv format of each instants bbox and segmented pixel coordinates frame by frame
Thank you in advance.

**Comment by bayraktare** [comment]
In the `eval.py` there are these following lines:
`masks = t[3][idx]`
`classes, scores, boxes = [x[idx].cpu().numpy() for x in t[:3]]` at 159 and 160th rows.
These are the the things you are looking for. You can save them to any file format.

**Comment by dbolya** [comment]
Yup, exactly that ^
