### ISSUE TITLE
environment.yml for convenient conda install 

### ISSUE THREAD

**Issue by breznak** [dbolya/yolact#277]
Hi all, 

just heads up, would you accept a PR that adds `environment.yml` for a convenient setup of this repo for Anaconda python? It can pull all the dependencies listed in Readme. 

Result: 
`conda env create -f environment.yml`
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file

**Comment by abhigoku10** [comment]
@breznak  is it possible to have similar functionality like docker

**Comment by breznak** [comment]
> to have similar functionality like docker 

that's also an idea, to make a Docker image with the network up and running. Although afaik Docker images are typically static, and in many usecases people would re-train the net here on a custom dataset.
