### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by zhuliqian** [dbolya/yolact#28]
memory is 12G,only used 8G

python train.py --config=yolact_base_config --batch_size=5
loading annotations into memory...
Done (t=0.06s)
creating index...
index created!
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
Initializing weights...
Begin training!

[  0]       0 || B: 8.264 | C: 14.452 | M: 14.870 | S: 3.010 | T: 40.595 || ETA: 0:00:00 || timer: 12.147
[  0]      10 || B: 9.251 | C: 9.149 | M: 7.010 | S: 2.204 | T: 27.615 || ETA: 0:57:52 || timer: 0.445
[  0]      20 || B: 8.156 | C: 7.494 | M: 6.613 | S: 1.537 | T: 23.800 || ETA: 1:00:17 || timer: 0.441
[  0]      30 || B: 8.053 | C: 6.515 | M: 6.317 | S: 1.206 | T: 22.091 || ETA: 1:08:55 || timer: 0.437
[  0]      40 || B: 7.631 | C: 5.865 | M: 6.203 | S: 0.981 | T: 20.680 || ETA: 1:22:37 || timer: 0.428
[  0]      50 || B: 7.558 | C: 5.397 | M: 6.149 | S: 0.845 | T: 19.949 || ETA: 1:20:02 || timer: 0.432
Traceback (most recent call last):
  File "train.py", line 374, in <module>
    train()
  File "train.py", line 211, in train
    for datum in data_loader:
  File "/home/chase/anaconda3/envs/maskrcnn_benchmark1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/chase/anaconda3/envs/maskrcnn_benchmark1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
MemoryError: Traceback (most recent call last):
  File "/home/chase/anaconda3/envs/maskrcnn_benchmark1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/chase/anaconda3/envs/maskrcnn_benchmark1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/chase/yolact/data/coco.py", line 88, in __getitem__
    im, gt, masks, h, w, num_crowds = self.pull_item(index)
  File "/home/chase/yolact/data/coco.py", line 151, in pull_item
    {'num_crowds': num_crowds, 'labels': target[:, 4]})
  File "/home/chase/yolact/utils/augmentations.py", line 658, in __call__
    return self.augment(img, masks, boxes, labels)
  File "/home/chase/yolact/utils/augmentations.py", line 54, in __call__
    img, masks, boxes, labels = t(img, masks, boxes, labels)
  File "/home/chase/yolact/utils/augmentations.py", line 380, in __call__
    current_masks = masks[mask, :, :].copy()
MemoryError

**Comment by dbolya** [comment]
I need more information than this. What GPU are you using? are you running other things on that GPU?

If you don't have enough VRAM to train the base model with batch size 8, I recommend using Resnet50 instead because batch norm gets worse as you lower the batch size.

**Comment by zhuliqian** [comment]
TITAN X (Pascal)
I didn't run other things
I use anaconda3
when the batchsize=1
![Screenshot from 2019-05-07 15-46-00](https://user-images.githubusercontent.com/17901084/57282271-4807cf00-70df-11e9-8a8f-62679efc0cd6.png)

**Comment by dbolya** [comment]
That's weird. I'm able to train `--config=yolact_base_config --batch_size=5` with my 1080 ti on Windows, which has a known bug limiting vram (so effectively 8-9gb of vram total). Could this be a PyTorch issue? What version of Pytorch are you on?

Also does it fit into memory if you try training the Resnet50 version?

**Comment by dbolya** [comment]
I just checked and those settings use 6790 MiB total on my 1080 ti, so it looks like it might be an issue with your environment?

**Comment by dbolya** [comment]
Do you happen to be on Pytorch 1.1.0? It looks like that version uses more vram. See #33

**Comment by stuafu** [comment]
i move the project to another PC (centos7, two 1080ti)， now it has  run for 12 hours.
i want to press ctrl+c  to save a  an *_interrupt.pth file for test .  but it seems not work,
And i wonder if i can eval though the  *_interrupt.pth file(just check some pictures)?

**Comment by dbolya** [comment]
You have to wait a while after pressing ctrl+c once. And unless I screwed anything up if you have an interrupt file in the weights directory, you can just go `python eval.py --trained_model=interrupt` (just tested it, seems to work for me).

Also warning that saving an interrupt will overwrite the last interrupt saved, so if you want to keep the interrupt, remove the `_interrupt` part and load it in `eval.py` normally.

**Comment by stuafu** [comment]
sorry,  i make a mistake .   now,  i  see  the interrupt file and  the auto save file every 10000 epoch.  Thx a lot .
