### ISSUE TITLE
Can't obtain same accuracy claimed by readme when directly evaluating the released model.

### ISSUE THREAD

**Issue by huangh12** [dbolya/yolact#290]
Hello, 
    Thanks for the great work. I directly eval the model of `yolact_plus_resnet50_54_800000.pth`. It's claimed the accuracy is 34.1mAP as below.
![图片](https://user-images.githubusercontent.com/18748036/72660997-58af6980-3a10-11ea-8950-1c5fb5e3601c.png)

 But I got 33.69, here is my evaluating log（I made no change of the code）:
> Multiple GPUs detected! Turning off JIT.
> Config not specified. Parsed yolact_plus_resnet50_config from the file name.
> 
> loading annotations into memory...
> Done (t=0.62s)
> creating index...
> index created!
> Loading model... Done.
> 
> Processing Images  ██████████████████████████████   4952 /   4952 (100.00%)    10.61 fps
> Saving data...
> Calculating mAP...
> 
>        |  all  |  .50  |  .55  |  .60  |  .65  |  .70  |  .75  |  .80  |  .85  |  .90  |  .95  |
> -------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
>    box | 34.94 | 55.41 | 53.17 | 50.49 | 47.40 | 43.20 | 37.83 | 30.48 | 20.95 |  9.30 |  1.15 |
>   mask | 33.69 | 52.72 | 50.23 | 47.29 | 44.45 | 40.50 | 35.59 | 29.91 | 21.88 | 11.93 |  2.43 |
> -------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+

**Comment by huangh12** [comment]
Closed due to misunderstanding.
The mAP you given is on test-dev, while I report a 5000val mAP.

**Comment by abhigoku10** [comment]
@huangh12  hwo r u getting the mask mAP when ever i try to calaculate i am getting it as zero  but i am getting the box mAP correcty ??
