### ISSUE TITLE
YOLACT++  DCNv2 build error

### ISSUE THREAD

**Issue by opentld** [dbolya/yolact#291]
system:windows10,Anaconda
when building DCNv2,error occurs:

D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\torch\lib "/LIBPATH:D:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib/x64" /LIBPATH:D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\libs /LIBPATH:D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\PCbuild\amd64 "/LIBPATH:D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x64" "/LIBPATH:D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.17763.0\ucrt\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.17763.0\um\x64" cudart.lib c10.lib c10_cuda.lib torch.lib torch_python.lib _C.lib /EXPORT:PyInit__ext build\temp.win-amd64-3.6\Release\SourceCodes\tensorflow\objectDetection\yolact-master\external\DCNv2\src\vision.obj build\temp.win-amd64-3.6\Release\SourceCodes\tensorflow\objectDetection\yolact-master\external\DCNv2\src\cpu\dcn_v2_cpu.obj build\temp.win-amd64-3.6\Release\SourceCodes\tensorflow\objectDetection\yolact-master\external\DCNv2\src\cuda\dcn_v2_cuda.obj build\temp.win-amd64-3.6\Release\SourceCodes\tensorflow\objectDetection\yolact-master\external\DCNv2\src\cuda\dcn_v2_im2col_cuda.obj build\temp.win-amd64-3.6\Release\SourceCodes\tensorflow\objectDetection\yolact-master\external\DCNv2\src\cuda\dcn_v2_psroi_pooling_cuda.obj /OUT:build\lib.win-amd64-3.6\_ext.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\SourceCodes\tensorflow\objectDetection\yolact-master\external\DCNv2\src\_ext.cp36-win_amd64.lib
  正在创建库 build\temp.win-amd64-3.6\Release\SourceCodes\tensorflow\objectDetection\yolact-master\external\DCNv2\src\_ext.cp36-win_amd64.lib 和对象 build\temp.win-amd64-3.6\Release\SourceCodes\tensorflow\objectDetection\yolact-master\external\DCNv2\src\_ext.cp36-win_amd64.exp
dcn_v2_cuda.obj : error LNK2001: 无法解析的外部符号 "struct THCState * state" (?state@@3PEAUTHCState@@EA)
build\lib.win-amd64-3.6\_ext.cp36-win_amd64.pyd : fatal error LNK1120: 1 个无法解析的外部命令
error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120

**Comment by opentld** [comment]
![image](https://user-images.githubusercontent.com/21096515/72663436-bb632e00-3a2d-11ea-99c3-0116bca3cac5.png)

is this code error ?

**Comment by opentld** [comment]
![image](https://user-images.githubusercontent.com/21096515/72663937-f451d180-3a32-11ea-8ea5-cd8741e4112d.png)

fixed! 

in version.cpp , add these codes :)

**Comment by trobro** [comment]
Thanks for sharing, the fix worked for me too! This is the file I changed:

`yolact\external\DCNv2\src\vision.cpp`

My system:

Windows 7
Visual Studio 2017
Anaconda Python 3.7
Cuda 10.0
PyTorch 1.4

**Comment by trobro** [comment]
Correction: @opentld your fix made it possible for me to build DCNv2, but not to run it. The fix caused a null-pointer error when running. I reverted the change and instead did this, now I can both build and run Yolact++:

```
--- a/external/DCNv2/src/cuda/dcn_v2_cuda.cu
+++ b/external/DCNv2/src/cuda/dcn_v2_cuda.cu
@@ -8,7 +8,7 @@
 #include <THC/THCAtomics.cuh>
 #include <THC/THCDeviceUtils.cuh>

-extern THCState *state;
+THCState *state = at::globalContext().lazyInitCUDA();

 // author: Charles Shang
 // https://github.com/torch/cunn/blob/master/lib/THCUNN/generic/SpatialConvolut
ionMM.cu
```

**Comment by Pixeptron-Vision** [comment]
If you are facing this issue with PyTorch version 1.11, check the [latest DCN version](https://github.com/jinfagang/DCNv2_latest).
