### ISSUE TITLE
KeyError: '_constants_set'

### ISSUE THREAD

**Issue by yview-develop** [dbolya/yolact#292]
when i began to train, i got fellow error:
"
Initializing weights...
Traceback (most recent call last):
  File "train.py", line 502, in <module>
    train()
  File "train.py", line 211, in train
    yolact_net.init_weights(backbone_path=args.save_folder + cfg.backbone.path)
  File "/home/yview/work/ai/outside/pytorch/yolact/yolact.py", line 512, in init_weights
    and all_in(module.__dict__['_constants_set'], conv_constants) \
KeyError: '_constants_set'
"
>>> import torch
>>> torch.__version__
'1.4.0'

dataset is using "coco"

cmd: python train.py --config=yolact_base_config --batch_size=5

**Comment by trobro** [comment]
I have the same problem, also running PyTorch 1.4. It seems that @dbolya anticipated this problem.

    # Note that this might break with future pytorch updates, so let me know if it does
    is_script_conv = 'Script' in type(module).__name__ \
        and all_in(module.__dict__['_constants_set'], conv_constants) \
        and all_in(conv_constants, module.__dict__['_constants_set'])

**Comment by trobro** [comment]
I added a check for `'_constants_set'` so that I can run training. I don't know if it's a good solution. Maybe I'll know when I see the results of the training.

```
             is_script_conv = 'Script' in type(module).__name__ \
+                and '_constants_set' in module.__dict__ \
                 and all_in(module.__dict__['_constants_set'], conv_constants) \
                 and all_in(conv_constants, module.__dict__['_constants_set'])
```

**Comment by saisubramani** [comment]
Initializing weights...
Traceback (most recent call last):
  File "train.py", line 502, in <module>
    train()
  File "train.py", line 211, in train
    yolact_net.init_weights(backbone_path=args.save_folder + cfg.backbone.path)
  File "/home/user_reorder01/Sai_Subramani/Programs/YOLOACT/yolact/yolact.py", line 512, in init_weights
    and all_in(module.__dict__['_constants_set'], conv_constants) \
KeyError: '_constants_set'

same error facing, any proper solution?


> I added a check for `'_constants_set'` so that I can run training. I don't know if it's a good solution. Maybe I'll know when I see the results of the training.
> 
> ```
>              is_script_conv = 'Script' in type(module).__name__ \
> +                and '_constants_set' in module.__dict__ \
>                  and all_in(module.__dict__['_constants_set'], conv_constants) \
>                  and all_in(conv_constants, module.__dict__['_constants_set'])
> ```

cant able to clear the error

**Comment by saisubramani** [comment]
> Initializing weights...
> Traceback (most recent call last):
> File "train.py", line 502, in
> train()
> File "train.py", line 211, in train
> yolact_net.init_weights(backbone_path=args.save_folder + cfg.backbone.path)
> File "/home/user_reorder01/Sai_Subramani/Programs/YOLOACT/yolact/yolact.py", line 512, in init_weights
> and all_in(module.**dict**['_constants_set'], conv_constants)
> KeyError: '_constants_set'
> 
> same error facing, any proper solution?
> 
> > I added a check for `'_constants_set'` so that I can run training. I don't know if it's a good solution. Maybe I'll know when I see the results of the training.
> > ```
> >              is_script_conv = 'Script' in type(module).__name__ \
> > +                and '_constants_set' in module.__dict__ \
> >                  and all_in(module.__dict__['_constants_set'], conv_constants) \
> >                  and all_in(conv_constants, module.__dict__['_constants_set'])
> > ```
> 
> cant able to clear the error

ya its running thanks @trobro

**Comment by yview-develop** [comment]
> I added a check for `'_constants_set'` so that I can run training. I don't know if it's a good solution. Maybe I'll know when I see the results of the training.
> 
> ```
>              is_script_conv = 'Script' in type(module).__name__ \
> +                and '_constants_set' in module.__dict__ \
>                  and all_in(module.__dict__['_constants_set'], conv_constants) \
>                  and all_in(conv_constants, module.__dict__['_constants_set'])
> ```

yes, it maybe work, waiting for result. thanks!

**Comment by dbolya** [comment]
uhg why do they keep changing this

Simply checking whether or not that set exists will circumvent the error, but not fix it. What's happening is I'm initializing the conv layers with xavier (different from their standard initialization) and some of those modules are JIT script modules that replaced Conv2D modules. The problem with checking for those script modules is they seem to change the way they handle them every damn version.

Whatever, I'll fix it one sec.

**Comment by dbolya** [comment]
wtf is a RecursiveScriptModule

first there was ScriptModule in 1.0, then there was WeakProxyScriptModule in 1.2, now it's RecursiveScriptModule in 1.4

where does it enddd?

**Comment by trobro** [comment]
Thanks for fixing! I agree, I wish the frameworks were more stable.
