### ISSUE TITLE
How I can seperate object by object

### ISSUE THREAD

**Issue by moresore** [dbolya/yolact#294]
I try to use YOLACT to count stacked pallet in the storage but the result was not as I hope. How I can improve my data set to separate object out one by one not consecutive. 

config.py

DPE_dataset = dataset_base.copy({
    'name': 'DPE',
    'train_images': './data/dataTrain/',
    'valid_images': './data/dataVal/',
    'train_info': './data/dataTrain/annotations.json',
    'valid_info': './data/dataVal/annotations.json',
    'has_gt': True,
    'class_names': DPE_CLASSES,
    'label_map': DPE_LABEL_MAP
})

DPE_config = yolact_base_config.copy({
    'name': 'DPE',
    'dataset': DPE_dataset,
    'num_classes': 5 + 1,
    'max_size': 640,
    'backbone': yolact_base_config.backbone.copy({
        'pred_scales': [[int(x[0] / yolact_base_config.max_size * 640)] for x in yolact_base_config.backbone.pred_scales],
    }),
})

Command training
       python train.py --config=DPE_config --batch_size=5 --dataset=DPE_dataset

I have trained 480,000 iterations
Thank you in advance

**Comment by moresore** [comment]
It's my mistake, close issue

**Comment by PrajwalCogniac** [comment]
Hey @moresore 
Can you please provide any insights or the mistakes you had made , I am struggling with the same issue
