### ISSUE TITLE
Duplicate Objects

### ISSUE THREAD

**Issue by thimabru1010** [dbolya/yolact#295]
Hi,

I filtered only persons after inference and after looking at the classes number in an image I figured out there were so many people counted into an image. Then after inspecting the bounding boxes and masks, I found out there were duplicate objects detected. Did someone find the same problem? Is there Non-Maximum Suppression Algorithm implemented?

Edit: I found the fast NMS and the cross-class fast NMS implemented. The fast NMS is the actual running into the main code when you evaluate images. The cross-class version wipes out the closest objects also (in my case closest people). 

How do I avoid that? Maybe using a traditional NMS algorithm?

**Comment by liminn** [comment]
Hi, you mean: there is an extra prediction box between two correct prediction bounding box, right?
