### ISSUE TITLE
Yolact++ train warning

### ISSUE THREAD

**Issue by enhany** [dbolya/yolact#303]
When I try to train yolact++ I get warning (training continue):
[  0]     160 || B: 4.344 | C: 2.996 | M: 6.362 | S: 0.069 | I: 0.824 | T: 14.595 || ETA: 9 days, 15:07:10 || timer: 0.615
Z:\files\yolact\layers\modules\multibox_loss.py:691: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  loss_i = F.smooth_l1_loss(maskiou_p, maskiou_t, reduction='sum')

May be it's connected to fix of #302

**Comment by dbolya** [comment]
I am not able to reproduce this. I'm assuming you're using the fix of #302, right? Does this happen frequently, or very rarely?

If possible and this happens frequently, can you print both maskiou_p and maskiou_t before that line to check which one is empty?

**Comment by enhany** [comment]
This error happens frequently (every time I run train).

maskiou_p:  tensor(0.2326, grad_fn=<SqueezeBackward0>)
maskiou_t:  tensor([0.5226])
Z:\files\yolact\layers\modules\multibox_loss.py:694: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.

**Comment by dbolya** [comment]
Ohhh, I see. That warning shouldn't affect training but I'll fix it so it doesn't yell at you.
