### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by remindchobits** [dbolya/yolact#31]
Hello!
I trained this model with own dataset, but it fails in the mAP evaluation phase, does anyone have the same problem?

(tensorflow) root@gpuserver:/home/gpuserver/models/yolact# python train.py --config=yolact_base_config
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Initializing weights...
Begin training!

/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/torch/nn/parallel/_functions.py:61: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
[  0]       0 || B: 5.480 | C: 23.075 | M: 5.976 | S: 67.004 | T: 101.536 || ETA: 0:00:00 || timer: 23.377
[  0]      10 || B: 4.757 | C: 18.774 | M: 5.625 | S: 47.000 | T: 76.155 || ETA: 11 days, 7:25:02 || timer: 1.176
[  0]      20 || B: 4.587 | C: 15.804 | M: 5.362 | S: 29.147 | T: 54.900 || ETA: 11 days, 7:50:00 || timer: 1.180
[  0]      30 || B: 4.582 | C: 13.355 | M: 5.309 | S: 19.954 | T: 43.199 || ETA: 11 days, 6:14:29 || timer: 1.272
[  0]      40 || B: 4.553 | C: 11.175 | M: 5.306 | S: 15.150 | T: 36.183 || ETA: 11 days, 6:35:18 || timer: 1.266
[  0]      50 || B: 4.497 | C: 9.617 | M: 5.303 | S: 12.227 | T: 31.645 || ETA: 11 days, 6:12:37 || timer: 1.120
[  0]      60 || B: 4.433 | C: 8.514 | M: 5.290 | S: 10.265 | T: 28.503 || ETA: 11 days, 4:48:22 || timer: 1.166
[  1]      70 || B: 4.383 | C: 7.700 | M: 5.304 | S: 8.850 | T: 26.237 || ETA: 11 days, 7:53:19 || timer: 1.236
[  1]      80 || B: 4.339 | C: 7.073 | M: 5.269 | S: 7.781 | T: 24.464 || ETA: 11 days, 6:55:00 || timer: 1.173
[  1]      90 || B: 4.294 | C: 6.585 | M: 5.250 | S: 6.945 | T: 23.074 || ETA: 11 days, 6:22:39 || timer: 1.217
[  1]     100 || B: 4.235 | C: 6.015 | M: 5.230 | S: 5.666 | T: 21.147 || ETA: 11 days, 5:30:35 || timer: 1.259
[  1]     110 || B: 4.131 | C: 4.426 | M: 5.184 | S: 1.178 | T: 14.920 || ETA: 11 days, 4:57:38 || timer: 1.177
[  1]     120 || B: 4.045 | C: 3.427 | M: 5.202 | S: 0.242 | T: 12.915 || ETA: 11 days, 4:43:12 || timer: 1.214
[  2]     130 || B: 3.926 | C: 2.860 | M: 5.195 | S: 0.192 | T: 12.174 || ETA: 11 days, 5:57:53 || timer: 2.714
[  2]     140 || B: 3.817 | C: 2.654 | M: 5.138 | S: 0.180 | T: 11.789 || ETA: 11 days, 5:43:35 || timer: 1.230
[  2]     150 || B: 3.694 | C: 2.571 | M: 5.045 | S: 0.170 | T: 11.480 || ETA: 11 days, 5:23:29 || timer: 1.217
[  2]     160 || B: 3.617 | C: 2.516 | M: 4.966 | S: 0.158 | T: 11.256 || ETA: 11 days, 5:37:45 || timer: 1.277
[  2]     170 || B: 3.540 | C: 2.467 | M: 4.876 | S: 0.149 | T: 11.031 || ETA: 11 days, 5:16:56 || timer: 1.222
[  2]     180 || B: 3.440 | C: 2.419 | M: 4.831 | S: 0.141 | T: 10.831 || ETA: 11 days, 4:54:42 || timer: 1.176
[  2]     190 || B: 3.342 | C: 2.364 | M: 4.716 | S: 0.135 | T: 10.558 || ETA: 11 days, 4:41:58 || timer: 1.187

Computing validation mAP (this may take a while)...

Traceback (most recent call last):
  File "train.py", line 374, in <module>
    train()
  File "train.py", line 303, in train
    compute_validation_map(yolact_net, val_dataset)
  File "train.py", line 367, in compute_validation_map
    eval_script.evaluate(yolact_net, dataset, train_mode=True)
  File "/home/gpuserver/models/yolact/eval.py", line 791, in evaluate
    prep_metrics(ap_data, preds, img, gt, gt_masks, h, w, num_crowd, dataset.ids[image_idx], detections)
  File "/home/gpuserver/models/yolact/eval.py", line 401, in prep_metrics
    ap_obj = ap_data[iou_type][iouIdx][_class]
IndexError: list index out of range

**Comment by dbolya** [comment]
Can you share your dataset config object and annotation file?

Also, are you on the latest commit?

**Comment by remindchobits** [comment]
Thanks a lot for your reply!

Here is my config object:
my_custom_dataset = dataset_base.copy({
    'name': 'My Dataset',

    'train_images': '../data/cocolike/coco/images/train2017/',
    'train_info':   '../data/cocolike/coco/annotations/instances_train2017.json',

    'valid_images': '../data/cocolike/coco/images/val2017/',
    'valid_info':   '../data/cocolike/coco/annotations/instances_val2017.json',

    'has_gt': True,
    'class_names': MY_CLASSES,
    'label_map': MY_LABEL_MAP
})

and MY_CLASSES and MY_LABEL_MAP are:

MY_CLASSES = ('person')
MY_LABEL_MAP = { 1:  1 }

Here is my last annotation object:
  {
   "id": 163,
   "image_id": 58,
   "category_id": 1,
   "segmentation": [
    [
     436,
     344,
     467,
     333,
     495,
     321,
     534,
     308,
     561,
     306,
     561,
     318,
     557,
     349,
     561,
     395,
     563,
     422,
     554,
     435,
     522,
     440,
     501,
     442,
     474,
     441,
     451,
     424,
     439,
     402,
     427,
     376
    ]
   ],
   "bbox": [
    427,
    306,
    136,
    136
   ],
   "iscrowd": 0,
   "area": 1.0
  }
 ],
 "categories": [
  {
   "id": 1,
   "name": "person"
  }
 ]
}

After searching for the solution, I find that the problem is the class name, shall I change the class name from "person" to "person_person" in the annotation file or ?
THX!

**Comment by dbolya** [comment]
I don't think it's the name of the classes, since I don't actually use those anywhere except for displaying purposes. Are you sure that every `category_id` in your annotation is a 1? Looking at the error more in depth, it looks like it could be caused by a `category_id` that is not 1.

**Comment by remindchobits** [comment]
Hi, 
Thanks for your reply!
You are right, something wrong with the converter of the labelme2coco, after retrying converting again the problem is now solved
Thanks a lot!
I rly love this model!

**Comment by dbolya** [comment]
Glad to see that worked!

**Comment by Gowtham2305** [comment]
@remindchobits I am facing same kind of issues , did you change anything in lableme2coco.py file?

**Comment by areebsyed** [comment]
> cocolike

@remindchobits Hi I have a question about this annotation file. Did you use the already given .json file (instances_train2017.json) or you made your own custom? because the last annotation object you posted I dont know how to make my own annotation file. I just want to predict persons only in the image.

**Comment by areebsyed** [comment]
> Thanks a lot for your reply!
> 
> Here is my config object:
> 
> ```
> my_custom_dataset = dataset_base.copy({
>     'name': 'My Dataset',
> 
>     'train_images': '../data/cocolike/coco/images/train2017/',
>     'train_info':   '../data/cocolike/coco/annotations/instances_train2017.json',
> 
>     'valid_images': '../data/cocolike/coco/images/val2017/',
>     'valid_info':   '../data/cocolike/coco/annotations/instances_val2017.json',
> 
>     'has_gt': True,
>     'class_names': MY_CLASSES,
>     'label_map': MY_LABEL_MAP
> })
> ```
> 
> and MY_CLASSES and MY_LABEL_MAP are:
> 
> ```
> MY_CLASSES = ('person')
> MY_LABEL_MAP = { 1:  1 }
> ```
> 
> Here is my last annotation object:
> 
> ```
>   {
>    "id": 163,
>    "image_id": 58,
>    "category_id": 1,
>    "segmentation": [
>     [
>      436,
>      344,
>      467,
>      333,
>      495,
>      321,
>      534,
>      308,
>      561,
>      306,
>      561,
>      318,
>      557,
>      349,
>      561,
>      395,
>      563,
>      422,
>      554,
>      435,
>      522,
>      440,
>      501,
>      442,
>      474,
>      441,
>      451,
>      424,
>      439,
>      402,
>      427,
>      376
>     ]
>    ],
>    "bbox": [
>     427,
>     306,
>     136,
>     136
>    ],
>    "iscrowd": 0,
>    "area": 1.0
>   }
>  ],
>  "categories": [
>   {
>    "id": 1,
>    "name": "person"
>   }
>  ]
> }
> ```
> 
> After searching for the solution, I find that the problem is the class name, shall I change the class name from "person" to "person_person" in the annotation file or ?
> THX!

@remindchobits 
Hi I have a question about this annotation file. Did you use the already given .json file (instances_train2017.json) or you made your own custom? because the last annotation object you posted I dont know how to make my own annotation file. I just want to predict persons only in the image.

**Comment by ybk66** [comment]
how did you deal with the1 problem?please!
