### ISSUE TITLE
size mismatch for prediction_layers.0.conf_layer.weight

### ISSUE THREAD

**Issue by saisubramani** [dbolya/yolact#310]
hi dbolya
I had trained the model with custom data set,with 6 classes.
i had made the alteration in config.py file, which was given in the Readme, and i successfully completed the training process for 800 iteration and i got the weight files also
**yolact_base_133_800.pth**

**config.py**
` Training params

    'lr_steps': (280, 600, 700, 750),
    'max_iter': 800,` 

While Evaluating it with the script **eval.py** with the trained weight file it showing the error

> Loading model...Traceback (most recent call last):
  File "eval.py", line 1098, in <module>
    net.load_weights(args.trained_model)
  File "/home/user_reorder01/Sai_Subramani/Programs/YOLACT/yolact/yolact.py", line 490, in load_weights
    self.load_state_dict(state_dict)
  File "/home/user_reorder01/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Yolact:
	size mismatch for prediction_layers.0.conf_layer.weight: copying a param with shape torch.Size([21, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([24, 256, 3, 3]).
	size mismatch for prediction_layers.0.conf_layer.bias: copying a param with shape torch.Size([21]) from checkpoint, the shape in current model is torch.Size([24]).
	size mismatch for semantic_seg_conv.weight: copying a param with shape torch.Size([6, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([7, 256, 1, 1]).
	size mismatch for semantic_seg_conv.bias: copying a param with shape torch.Size([6]) from checkpoint, the shape in current model is torch.Size([7]).

_Originally posted by @saisubramani in https://github.com/dbolya/yolact/issues/200#issuecomment-579623536_

**Comment by dbolya** [comment]
Have you added a class after training or something? It looks like you originally had 6 (+1) classes and now you have 7 (+1). (+1s for the extra background class)

**Comment by saisubramani** [comment]
No i too had that doubt, but i cross checked with that and it has only 6 classes

**Comment by saisubramani** [comment]
One More doubt how to check the input size of the layer . i mean the first layer shape.
Example:([1,3,500,500])
because i need to convert the torch model to tflite model

**Comment by saisubramani** [comment]
> Have you added a class after training or something? It looks like you originally had 6 (+1) classes and now you have 7 (+1). (+1s for the extra background class)

thanks for the reply

**Comment by saisubramani** [comment]
ya in config file the labels are not added. thanks for the reply @dbolya
