### ISSUE TITLE
How to speed up the training?

### ISSUE THREAD

**Issue by PulkitMishra** [dbolya/yolact#314]
I worked on a similar project at university and used Mask RCNN. I wanted to compare its performance with yolact. 

I have followed the steps and have prepared the dataset accordingly and made changes to the config file. You can find my code on the fork here (https://github.com/PulkitMishra/yolact)

Also, right now, I just have 2 training and 1 validation image (batch size is 2)

I am trying to run it on colab. Any help/tips @dbolya on how I can speed up the time?
Would really be grateful!

**Comment by dbolya** [comment]
If you have that few images, you can drastically reduce the number of iterations here:
https://github.com/PulkitMishra/yolact/blob/db81124874817895db69f2dc443f5c24e0e3f491/data/config.py#L667-L668

Divide all of those numbers by at least 1000. (Also I don't think you pushed your config changes to your fork).

**Comment by PulkitMishra** [comment]
@dbolya thanks a lot for the response. I actually have 500 images with 2 classes. Also extremely sorry, you are right, I forgot to push the changes. Can you please take a look at the config file if you find time.

**Comment by dbolya** [comment]
From a cursory look, that looks fine to me. So yeah, just change these two lines:
https://github.com/PulkitMishra/yolact/blob/ca854db70b9641bb2e51e92d1a5bf099f3f78337/data/config.py#L682-L683
to 
```py
    'lr_steps': (280, 600, 700, 750),
    'max_iter': 800,
```
and it should train super fast. Not sure how good results you will get with that few images though. Perhaps you want to use the resnet50 version since it's shallower.

**Comment by PulkitMishra** [comment]
@dbolya I have around 600 images now but when I train it on colab it gives me
RuntimeError: CUDA out of memory. Tried to allocate 15.59 GiB (GPU 0; 15.90 GiB total capacity; 916.56 MiB already allocated; 5.29 GiB free; 9.90 GiB reserved in total by PyTorch)

Please note that I have not made any validation split.

**Comment by PulkitMishra** [comment]
@dbolya I tried the same on AWS wth a much higher memory. But still same thing happened.

**Comment by JavierClearImageAI** [comment]
it gives me this error when doing your changes:

```python train.py --config=yolact_plus_base_config --batch_size=5 --dataset logs_dataset --resume=weights/yolact_plus_base_54_800000.pth --start_iter=-1
Scaling parameters by 0.62 to account for a batch size of 5.
Per-GPU batch size is less than the recommended limit for batch norm. Disabling batch norm.
loading annotations into memory...
Done (t=0.09s)
creating index...
index created!
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
Resuming training, loading weights/yolact_plus_base_54_800000.pth...
cfg.max_iter:  1280.0
cfg.lr_steps [448.0, 960.0, 1120.0, 1200.0]
Begin training!


Computing validation mAP (this may take a while)...

Traceback (most recent call last):
  File "train.py", line 506, in <module>
    train()
  File "train.py", line 376, in train
    compute_validation_map(epoch, iteration, yolact_net, val_dataset, log if args.log else None)
  File "train.py", line 494, in compute_validation_map
    val_info = eval_script.evaluate(yolact_net, dataset, train_mode=True)
  File "/home/ubuntu/yolact/eval.py", line 956, in evaluate
    prep_metrics(ap_data, preds, img, gt, gt_masks, h, w, num_crowd, dataset.ids[image_idx], detections)
  File "/home/ubuntu/yolact/eval.py", line 468, in prep_metrics
    ap_obj = ap_data[iou_type][iouIdx][_class]
IndexError: list index out of range
```

**Comment by PulkitMishra** [comment]
Fixed this by creating a train-validation split.
