### ISSUE TITLE
Question: Is there any future integration plan for Win10? Thanks!

### ISSUE THREAD

**Issue by majinshaoyuindustry** [dbolya/yolact#320]

**Comment by dbolya** [comment]
YOLACT already supports Win10 (in fact my computer at home is Win10 so I developed most of it on Windows...).

Are you having problems running it?

**Comment by majinshaoyuindustry** [comment]
> YOLACT already supports Win10 (in fact my computer at home is Win10 so I developed most of it on Windows...).
> 
> Are you having problems running it?

Hello dbolya,

Thank you for getting back to me. I am not very good in programming but it seems lines such as, "sh data/scripts/COCO.sh" are for Linux script file? Is there any way that I can learn to make it happen in Win10?

**Comment by enhany** [comment]
@majinshaoyuindustry you can try http://www.mingw.org/
All (most of them) unix scripts will work.

**Comment by majinshaoyuindustry** [comment]
> @majinshaoyuindustry you can try http://www.mingw.org/
> All (most of them) unix scripts will work.

Thanks a lot. I will give it a try today.

**Comment by dbolya** [comment]
Oh yeah, I forgot about that. I use mingw on Windows to run those scripts, yeah.

Though the scripts themselves are really simple (just download files and extract them), so if you wanted to you could execute the steps manually fairly easily.

**Comment by majinshaoyuindustry** [comment]
> Oh yeah, I forgot about that. I use mingw on Windows to run those scripts, yeah.
> 
> Though the scripts themselves are really simple (just download files and extract them), so if you wanted to you could execute the steps manually fairly easily.

Could you tell me how to get pycocotools installed in conda cmd? I ran the environment.yml file but it seems pycocotools doesn't work on win10? Can mingw solve this? Thank you and I am sorry for asking entry-level questions.

**Comment by enhany** [comment]
@majinshaoyuindustry officially pycocotools doesn't support windows. You need to install it manually (via mingw or directly).

**Comment by majinshaoyuindustry** [comment]
> @majinshaoyuindustry officially pycocotools doesn't support windows. You need to install it manually (via mingw or directly).

I got the mingw part, but how may I use mingw to install pycocotools into the virtual environment in anaconda? Please advise. 

Also, would this works? https://github.com/philferriere/cocoapi#egg=pycocotools^&subdirectory=PythonAPI

**Comment by majinshaoyuindustry** [comment]
> > @majinshaoyuindustry officially pycocotools doesn't support windows. You need to install it manually (via mingw or directly).
> 
> I got the mingw part, but how may I use mingw to install pycocotools into the virtual environment in anaconda? Please advise.
> 
> Also, would this works? [https://github.com/philferriere/cocoapi#egg=pycocotools^&subdirectory=PythonAPI](https://github.com/philferriere/cocoapi#egg=pycocotools%5E&subdirectory=PythonAPI)

It does work this way. Thank you all

**Comment by dbolya** [comment]
Nice, feel free to reopen the issue if you find any more Win10-specific issues.
