### ISSUE TITLE
Class names - Full name not showing up?

### ISSUE THREAD

**Issue by scaledinferance** [dbolya/yolact#321]
I thought I updated all the locations for class names but when I go an eval on my weights I get the following:

    'has_gt': True,
    'class_names': ("lesion")
})

but only l:0.5 shows up? I was expecting lesion:0.5. Do I need to point to a new labels in the eval.py

Thanks!

**Comment by VinniaKemala** [comment]
Hi @scaledinferance 
You should change `'class_names': ("lesion")` to `'class_names': ("lesion,")`

**Comment by scaledinferance** [comment]
Thanks @VinniaKemala here is the info int he config.py file. 

lesion = Config({
    'name': 'lesion',

    # Training images and annotations
    'train_images': '/home/yolact/dataset/train_out/',
    'train_info':   '/home/yolact/dataset/train_out/annotations.json',

    # Validation images and annotations.
    'valid_images': '/home/yolact/dataset/val_out/',
    'valid_info':   '/home/yolact/dataset/val_out/annotations.json',

    # Whether or not to load GT. If this is False, eval.py quantitative evaluation won't work.
    'has_gt': True,

    # A list of names for each of you classes.
    'class_names': ("lesion,"),

    # COCO class ids aren't sequential, so this is a bandage fix. If your ids aren't sequential,
    # provide a map from category_id -> index in class_names + 1 (the +1 is there because it's 1-indexed).
    # If not specified, this just assumes category ids start at 1 and increase sequentially.
    'label_map': None
})


this is my labels.txt

__ignore__
_background_
lesion

For some reason its still showing up as l:05. Is there any other place I might to change this?  Thank you!

**Comment by VinniaKemala** [comment]
@scaledinferance 
Ah my mistake, it should be
`'class_names': ("lesion",)` instead of `'class_names': ("lesion,")`
You need to train your model again since the number of classes is changing.

When you use `'class_names': ("lesion")`, the classes become "l", "e", "s", "i", "o", & "n" rather than "lesion".

**Comment by scaledinferance** [comment]
Thanks @VinniaKemala! That did it!
