### ISSUE TITLE
mAP Calculation results 0

### ISSUE THREAD

**Issue by Akash-Bhiwgade** [dbolya/yolact#328]
Hi Team,

Greetings of the day..!! I hope you are doing great.

This is in regards to an error while training. Need your suggestions on the same please.

I am training the yolact model on a custom dataset with custom dataset of size 20K.

While training the model, I get the warning and mAP calculation as zero. ( Please see attached screenshot).

For training the model, I am using the command as below:
CUDA_VISIBLE_DEVICES=0 python3 train.py --config=yolact_base_config --batch_size=2

And for inferencing the model, I am using the command as below:
python eval.py --trained_model=weights/yolact_base_45_450000.pth --score_threshold=0.15 --top_k=15 --image=1.jpg:1.png

When inferenced the model, I get no segmentation.

Please share some hints and suggestions to help me fix this.

Best Regards,
Akash bhiwgade
![Screenshot from 2020-02-10 11-06-19](https://user-images.githubusercontent.com/32064265/74125015-36b59b00-4bfa-11ea-9ed6-d65199e6866f.png)

**Comment by enhany** [comment]
@Akash-Bhiwgade  how many classes? whats size of train/val images? whats size of box/mask in images?

**Comment by Akash-Bhiwgade** [comment]
Hi @enhany,

number of classes = 150
train images = 20000
validation images = 2000

**Comment by dbolya** [comment]
That's odd. And your mask loss is huuuge. How small are your objects compared to your image size typically?

**Comment by Akash-Bhiwgade** [comment]
Hi Dan,

Greetings of the day..!! Hope you're great.

As of now I am working on room images and need to identify every objects in a room. Every room objects vary in size as per the image and object size.

Please help me with some ideas on fixing this.

Best Regards,
Akash Bhiwgade

**Comment by Akash-Bhiwgade** [comment]
Hi Team,

I am able to run the code and the map calculcations have been rectified. I had to recheck the json file post which I am able to get such mAP calculation (please find attached).

Do share your feedback on the current stats of the training.


Best Regards,
Akash Bhiwgade

**Comment by Akash-Bhiwgade** [comment]
Hi Team,

I am able to run the code and the map calculcations have been rectified. I had to recheck the json file post which I am able to get such mAP calculation (please find attached).

Do share your feedback on the current stats of the training.


Best Regards,
Akash Bhiwgade
![Screenshot from 2020-02-13 19-30-00](https://user-images.githubusercontent.com/32064265/74442573-bd3ad880-4e97-11ea-8781-6294cb56af1c.png)

**Comment by enhany** [comment]
@Akash-Bhiwgade 
you not gave any information to make conclusions.
You did something and now your "total loss" is better then was. Do the same things in this direction.

In my opinion, something is wrong with your dataset. Check size of your objects after picture resize. Check if categories are correct marked.

**Comment by abhigoku10** [comment]
@Akash-Bhiwgade  can you recheck your annotation and json files , since your box and mask map there is huge difference

**Comment by Sarveshsh8** [comment]
iam getting map as 0 , does anyone know why

**Comment by Sarveshsh8** [comment]
i trained on my custom dataset with 1 class, yolactedge map value is 0.
