### ISSUE TITLE
OverflowError: signed integer is less than minimum

### ISSUE THREAD

**Issue by Zhang-O** [dbolya/yolact#329]
when I run eval.py with my own img and model trained with yolact_base_config,  the info printed as follows:

Traceback (most recent call last):
  File "eval_custom.py", line 1107, in <module>
    evaluate(net, dataset)
  File "eval_custom.py", line 887, in evaluate
    evalimages(net, inp, out)
  File "eval_custom.py", line 626, in evalimages
    evalimage(net, path, out_path)
  File "eval_custom.py", line 603, in evalimage
    img_numpy = prep_display(preds, frame, None, None, undo_transform=False)
  File "eval_custom.py", line 246, in prep_display
    cv2.rectangle(img_numpy, (x1, y1), (x2, y2), color, 1)
OverflowError: signed integer is less than minimum

I checked some training log, found that it seems than the training process is a liitle weird:
[1016]  830880 || B: 15000549522543161677282561227675926528.000 | C: 17793.001 | M: 66.328 | S: 1.117 | T: 15000549522543161677282561227675926528.000 || ETA: 15 days, 14:32:35 || timer: 0.305
Warning: Moving average ignored a value of inf

Computing validation mAP (this may take a while)...

Warning: Augmentation output an example with no ground truth. Resampling...

Calculating mAP...

       |  all  |  .50  |  .55  |  .60  |  .65  |  .70  |  .75  |  .80  |  .85  |  .90  |  .95  |
-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
   box |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |
  mask |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |
-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+

[1017]  831140 || B: 14386591134195462406891206246221742080.000 | C: 17793.001 | M: 66.321 | S: 1.120 | T: 14386591134195462406891206246221742080.000 || ETA: 25 days, 17:03:19 || timer: 2.696
Warning: Moving average ignored a value of inf

[1017]  831150 || B: 14386591134195462406891206246221742080.000 | C: 17793.001 | M: 68.646 | S: 1.116 | T: 14386591134195462406891206246221742080.000 || ETA: 25 days, 16:33:23 || timer: 0.304

I guess the loss had diverged to infinite.
Am I right?

**Comment by dbolya** [comment]
Yeah, your loss diverged. What does your training setup look like?

**Comment by breznak** [comment]
> Yeah, your loss diverged.

can we assert on that and crash? Anything is going bonkers probably anyway then..

**Comment by dbolya** [comment]
@breznak Yeah an assert checking for a couple iterations in a row of nonfinite loss makes a lot more sense and would probably help people understand what's going on.

**Comment by Zhang-O** [comment]
> Yeah, your loss diverged. What does your training setup look like?

en , in the recent epochs before 110, the model evals successfully in pictures, and the results are OK. the models saved after 110 epoch all have the problem mentioned above. my data is kind of that a instance have many pieces in an img which all the pieces are not connected  in an insatance. I gusess it is the problem of my data.

**Comment by breznak** [comment]
Should we consider reopening to track the "if diverged, stop", which is currently not implemented?

**Comment by Zhang-O** [comment]
> Should we consider reopening to track the "if diverged, stop", which is currently not implemented?

I have apply yolact to train some models. they all works well. If you saved your training log, it is easy to find divergence from log. You can pay more attention to more important aspects.
