### ISSUE TITLE
overlay of icons on mask 

### ISSUE THREAD

**Issue by abhigoku10** [dbolya/yolact#330]
@dbolya hi just wanted to knw is it possible to better represent the output in a more creative way for example 
1.can we represent something like this 
![image](https://user-images.githubusercontent.com/22094053/74166688-021eff00-4c4d-11ea-8076-8d47f5dc3aac.png)
2. can we overlay images on the masks of the maintaining the prespective of the image like arrows / lines or icons of the detected objects

**Comment by dbolya** [comment]
Haha, that's cute. It would definitely be possible, but I'm not sure that fits in this Repo, since that seems like it would only be for a very specific use case.

**Comment by abhigoku10** [comment]
@dbolya for the second point , if i have to do like the image shown below 
![image](https://user-images.githubusercontent.com/22094053/74218673-9e3e1a00-4cd0-11ea-8f4c-95003a294f46.png)
should we need 3D object detection is it no possible with 2D by using homography

**Comment by dbolya** [comment]
That should probably be okay with just 2D, since really that's just road segmentation which is prretty flat.

**Comment by abhigoku10** [comment]
@dbolya for the perspective to maintain how to plot it on the image , we can use opencv features

**Comment by dbolya** [comment]
Oh that's what you mean. Yeah that should be easy with very simple computer vision methods--detect the perspective, then just draw the icons with that perspective. Not sure what that has to do with this project though.

**Comment by abhigoku10** [comment]
@dbolya this was just for beautification of the output , its not related entirely but good just wanted to knw the possibilites as usual thanks for your responses !!!
