### ISSUE TITLE
How to label the same object in the picture?

### ISSUE THREAD

**Issue by wlsonia** [dbolya/yolact#34]
For example, if there are multiple people in a picture, they are labeled as person 1,person2,person3?

**Comment by dbolya** [comment]
You'll have to add that yourself, but I can get you started. You want to modify this line to include the index of the person:

https://github.com/dbolya/yolact/blob/d50616f36002c48eda0a1e34a75eac12ef70aae0/eval.py#L187

Use some data structure to keep track of how many of each class have been detected beforehand and just put that number in the string next to the class. If you want to do a quick and dirty solution you can just replace that with `text_str = '%s %d' % (_class, j)` but that's not exactly what you want.

**Comment by wlsonia** [comment]
I'm sorry, I didn't make it clear, but I'm asking how do I label the same kinds of objects when I make my own data set.

**Comment by dbolya** [comment]
Oh, just create an annotation object for each of them with the same image ID. So if "person" is category id 1, and this label is for image id 1234, you'd have both
```
{
"id" : someIDForPerson1,
"image_id" : 1234,
"category_id" : 1,
"segmentation" : ...
},
{
"id" : someIDForPerson2,
"image_id" : 1234,
"category_id" : 1,
"segmentation" : ...
}, ...
```
You can look at the annotation files that COCO provides for reference.

**Comment by wlsonia** [comment]
Thank you so much!
