### ISSUE TITLE
yolov3-tiny as a backbone

### ISSUE THREAD

**Issue by sdimantsd** [dbolya/yolact#344]
Hi, 
Im try to implemence yolov3-tiny as a backbone.
It's a stupid question... I need the pth weights. how can i generate them?

thx!

**Comment by abhigoku10** [comment]
@sdimantsd  you can use darknet.pth weights only as pre trained weight and train right , what is the thought process on using yolov3 as backbone ?

**Comment by sdimantsd** [comment]
Im not shure i get you right. 
Do you mean to take the darknet53 weights to my new backbone?
darknet53 is the backbone of yolov3, it's not the same as yolov3-tiny
I want to use the backbone of yolov3-tiny, it's a smaller network thus the fps is bigger.

**Comment by sdimantsd** [comment]
OK, i did it :-D
It was simple then i expected... this is the code.
I loaded my model and then save the "empty" weights (what is the official name to "empty weights"?)

> import backbone
> import torch
> model = backbone.Yolov3tinyBackbone
> torch.save(model, 'yolov3-tiny.pth')

One question i still not shure, what are the initial weights? it is random around the zero or somthing else? couldn't find answer with google...

**Comment by abhigoku10** [comment]
@sdimantsd  ur training the model from scratch so the weight values intialization will be random and it will take long time to train . I was thinking about using tiny yolo darknet weight but wehn i googled did not find any pytorch model

**Comment by sdimantsd** [comment]
Yes, i know...
But since I couldn't find pre trained weights I have no choice...

**Comment by dbolya** [comment]
You'd need to convert the yolov3-tiny imagenet pretrained weights to pytorch's format yourself if you want to avoid training from scratch, since from a quick google I didn't see any pytorch implementation having it.

**Comment by sdimantsd** [comment]
Thx.

**Comment by sdimantsd** [comment]
Update: 
I used this repo:
https://github.com/ultralytics/yolov3
To convert from ".weights" to ".pth".
I'm start to train now and i will update.

**Comment by IbrahimBond** [comment]
hey friend, do you have any updates on this? if you succeeded, what steps did you take?
thanks

**Comment by sdimantsd** [comment]
I tried it, but the results were bad.
I did not have time to try again, but I could definitely have made a mistake in building the backbon
