### ISSUE TITLE
Error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

### ISSUE THREAD

**Issue by basit26374** [dbolya/yolact#346]
When I compile deformable convolutional layers 

`cd external/DCNv2
python setup.py build develop`

I got this error 

> error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

Environment info:
Ubuntu 18.04
CUDA 9.0
python 3.6
torch== 1.1.0
torchvision=== 0.2.0

**Comment by dbolya** [comment]
Did the error message print anything else out? That just means compilation failed. I can't really help without knowing where it failed.

**Comment by basit26374** [comment]
@dbolya thanks for your reply. I solved this problem. Actually problems with gcc and g++ version.
I have installed gcc and g++ 6.5.0 version but this is not compatible with CUDA 9.0.
see this 
https://github.com/facebookresearch/maskrcnn-benchmark/issues/25#issuecomment-433310980

Environment info:
Ubuntu 18.04
CUDA 9.0
python 3.6
torch== 1.1.0
torchvision=== 0.2.0
gcc and g++ version 6.5.0

Step to solve this problem:
1. `sudo apt-get install gcc-5 g++-5`

2. link from gcc 6 g++ 6 to gcc 5 g++ 5
`sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50 --slave /usr/bin/g++ g++ /usr/bin/g++-5 --slave /usr/bin/gcov gcov /usr/bin/gcov-5`

`sudo update-alternatives --config gcc`

and select gcc 5 version

see this blog post 
[https://linuxize.com/post/how-to-install-gcc-compiler-on-ubuntu-18-04/](url)

3. compile deformable convolutional layers
`cd external/DCNv2
python setup.py build develop`

and Done !!!
