### ISSUE TITLE
Custom Data Set Unable to Add New Images To Training Set

### ISSUE THREAD

**Issue by kogans1107** [dbolya/yolact#349]
Hello, 

I have been training yolact on a customized data set and I wanted to add more annotated images and continue to train from the interrupted weight file. When I try to continue training I get a error weight error. Is it possible to add images to the training set mid training.

**Comment by abhigoku10** [comment]
@kogans1107  we yolact has the option of resuming training we can do it from the last save weight file where it was interrupted

**Comment by dbolya** [comment]
Are you adding new classes? If you're just adding new images, what @abhigoku10 would work, but it sounds like you're adding new classes if you're getting an error.

If you want to add classes you can use fine tuning: #36.

**Comment by kogans1107** [comment]
Thank you that worked for me. Can I use that same code but make the star iter =-1?

**Comment by dbolya** [comment]
Yes, that should work.
