### ISSUE TITLE
How to crop segmented objects 

### ISSUE THREAD

**Issue by basit26374** [dbolya/yolact#350]
I want to crop segmented objects and save into directory. I am a bit confused about how to acquire masks of objects. I know these lines have relevant info but how separate them?
`masks = t[3][idx]`
`classes, scores, boxes = [x[idx].cpu().numpy() for x in t[:3]]`

I would crop objects like this 
https://www.pyimagesearch.com/wp-content/uploads/2018/11/mask_rcnn_roi_mask_segmented.jpg

**Comment by sainatarajan** [comment]
@basit26374 What do you mean by how to separate them?

Just do `masks.cpu().numpy()` and you'll get an array of binary masks. After that, iterate over them and save them to the disk as an image.

**Comment by dbolya** [comment]
Also, you might benefit from #286
