### ISSUE TITLE
train.py have a SyntaxError

### ISSUE THREAD

**Issue by ivanwu0404** [dbolya/yolact#351]
when i start to train the model, i use the command:
"python train.py --config=yolact_base_config" you provided,
but it has an error:
File "train.py", line 138
    def __init__(self, net:Yolact, criterion:MultiBoxLoss):
                                             ^
SyntaxError: invalid syntax

i dont know how to fix it, can you help me to fix it?
Thanks.

im using python3.6 and my pytorch version is higher than 1.01

![2020-02-21 23-45-31 的螢幕擷圖](https://user-images.githubusercontent.com/61323661/75049061-82bee480-5504-11ea-9a87-b9c9e6216ba2.png)

**Comment by jasonkena** [comment]
Can you screenshot or copy the relevant section from `train.py`, near lines 138?

**Comment by ivanwu0404** [comment]
![1582347806192](https://user-images.githubusercontent.com/61323661/75086852-bd139a80-5573-11ea-951e-3c54df8e4544.jpg)

**Comment by ivanwu0404** [comment]
Im training the default model(COCO)

**Comment by jasonkena** [comment]
What's your Python version, the output of `python --version`

**Comment by jasonkena** [comment]
Just make sure that your Python version is higher than 3.5, or else the type annotations will break. If that isn't the cause for the SyntaxError, I'm not sure what caused it, the code seems to be fine.

**Comment by ivanwu0404** [comment]
Thanks for help,I already fixed the problem.

**Comment by ThanhPham1987** [comment]
@ivanwu0404 Would you like to tell me how to solve issue?
