### ISSUE TITLE
How to output the log in the training process like the recall, mAP

### ISSUE THREAD

**Issue by jonguo111** [dbolya/yolact#358]
I want to see the loss graph for the training process. Is there some ways to visualize it?
Thanks

**Comment by dbolya** [comment]
See https://github.com/dbolya/yolact/issues/78#issuecomment-582152293

**Comment by jonguo111** [comment]
hi. thanks for your help. i plotted the mAP graph, however, would you please tell me how to draw the average recall (AR) graph? or is it necessary to draw the AR graph to evaluate the training model on my custom data?

**Comment by dbolya** [comment]
We don't evaluate the AR internally. You'll have to use external tools (like COCOEval) for that.

**Comment by jonguo111** [comment]
thanks!
