### ISSUE TITLE
Can't Find The Image

### ISSUE THREAD

**Issue by ivanwu0404** [dbolya/yolact#365]
Dear Dbolya,
I used your command to test an image, and I got an error below
---------------------------------------------------------------------------------------------------
ivanwu0404@ivanwu0404:~/yolact$ python eval.py --trained_model=weights/yolact_base_54_1066666.pth --score_threshold=0.15 --top_k=15 --image=25.png
Config not specified. Parsed yolact_base_config from the file name.

Loading model... Done.
Traceback (most recent call last):
  File "eval.py", line 1105, in <module>
    evaluate(net, dataset)
  File "eval.py", line 881, in evaluate
    evalimage(net, args.image)
  File "eval.py", line 596, in evalimage
    frame = torch.from_numpy(cv2.imread(path)).cuda().float()
TypeError: expected np.ndarray (got NoneType)
-------------------------------------------------------------------------------------------------------
I know this error occured when it can't find the image(25.png)
so I put the image in the folder(~/yolact)) where I run the command ,
But it still has the same error,
What should I do..?
![2020-03-02 21-20-42 的螢幕擷圖](https://user-images.githubusercontent.com/61323661/75680063-b3a0d580-5ccb-11ea-99ba-e593dee4431f.png)

**Comment by dbolya** [comment]
That is a `.jpg` not a `.png` >.>

Use `--image=25.jpg`

**Comment by ivanwu0404** [comment]
Oh that a stupid mistake I made, thank you😂
