### ISSUE TITLE
how to choose which gpu to use 

### ISSUE THREAD

**Issue by XufengCh** [dbolya/yolact#369]
Hi dbolya

I am trying to run eval.py on a server that has 4 gpus. 

I have set CUDA_VISIBLE_DEVICES=0, but actually, the program is always trying to use gpu 2, which is used by anther user at the same time. So, someting went wrong like this:

```
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
```

Setting CUDA_VISIBLE_DEVICES just seems not work. I want to know why. 

Thanks.

**Comment by Auth0rM0rgan** [comment]
try `export CUDA_VISIBLE_DEVICES=0,1,2,3`

**Comment by dbolya** [comment]
Depending on your configuration of GPUs, the indices in CUDA_VISIBLE_DEVICES can not line up with the indices of nvidia-smi. See [this Stackoverflow post](https://stackoverflow.com/questions/26123252/inconsistency-of-ids-between-nvidia-smi-l-and-cudevicegetname) for more details.

Try using `export CUDA_VISIBLE_DEVICES=<indices other than 0>`. I think you can fix this mismatch by setting the CUDA_DEVICE_ORDER to PCI_BUS_ID as in [here](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars).

**Comment by XufengCh** [comment]
Thx a lot! It works！
