### ISSUE TITLE
How you produce 'maskcoefficients'

### ISSUE THREAD

**Issue by muomi** [dbolya/yolact#37]
Hi,Thanks a lot for your fantastic work!But,i found that in your paper ,you produce 'mask coefficients'
by using fc layers.but in your code, i found you produce  'mask coefficients' by using conv layer.Can you tell me which kind of layer you use for   producing  'mask coefficients'?Thanks for your reply!

**Comment by dbolya** [comment]
A 1x1 kernel conv layer is just a fc layer applied individually to each pixel in the image. That's what I meant by saying "as the product of an fc layer". One conv layer is producing mask coefficient for every pixel in the conv out individually--doing it with a conv is just way more efficient.

**Comment by abhigoku10** [comment]
@dbolya  from the paper it seems that the mask coefficients are linear , is their any way we can make the coefficients non linear . If so how could we approach .

**Comment by dbolya** [comment]
@abhigoku10 It's not exactly linear depending on which place you look. The coefficients themselves go through a tanh, so they're all from -1 to 1. Then once they get multiplied with the prototypes (which are ReLU'd so they go from 0 to inf), that whole thing goes through a sigmoid. You could add some coefficients that get multiplied into a square prototype or something like that (similar to geometric [nonlinear] regression).

**Comment by abhigoku10** [comment]
@dbolya  i wanted to improve the accuracy for person detection in mscoco and custom data for that when i visualisation the protomask i am getting the features but the mask coefficients is low so increase that

**Comment by xuchengggg** [comment]
> 
> 
> A 1x1 kernel conv layer is just a fc layer applied individually to each pixel in the image. That's what I meant by saying "as the product of an fc layer". One conv layer is producing mask coefficient for every pixel in the conv out individually--doing it with a conv is just way more efficient.

Hi, in the PredictionModule notes, you said 'this is slightly different to the module in the paper', is this meanings change the extra_head_net kernel size from 1*1 to 3*3,  and is this original 1*1 the fc layers mentioned in your paper? And now there is no fc layer in prediction of mask_coefficients?
