### ISSUE TITLE
Bug in COCOAnnotationTransform?

### ISSUE THREAD

**Issue by huangh12** [dbolya/yolact#370]
Hi，could anybody explain why there must be a **minus one** in line 42?  The label_idx is actually used as **label** in later training. So the **minus one** makes the coco label zero-based, i.e., the person label turns into 0 instead of 1. This confused me.

![图片](https://user-images.githubusercontent.com/18748036/76047362-66f41d80-5f9d-11ea-9b38-89be7b31d4cb.png)

**Comment by dbolya** [comment]
The label used in training is the index into the class confidence vector. 0 is the first element in the vector while 79 would be the last.
