### ISSUE TITLE
feature map question on p3

### ISSUE THREAD

**Issue by jonguo111** [dbolya/yolact#371]
Hi. Thanks for your excellent work. I trained my custom data successfully. I am just wondering about the feature map on P3. I don't know if my understanding is correct... I am pretty new to this area. If my input image size is 512*512 if the feature map on P3 is 64\*64\*256? Thank you so much. Also, in my training process, I tried to change the anchor scales from [24, 48, 96, 192, 384] to  [12 24, 48, 96, 192]. It can work well during training but the problem is I need to change it back for evaluation otherwise it will report errors...

Thank you so much for your time.

**Comment by arunmp2004** [comment]
Hi, 
I am also new, and just like you wanted to train my model from scratch.
Can you share which tools have you used to train a new model?

Thanks,
Arun

**Comment by jonguo111** [comment]
> Hi,
> I am also new, and just like you wanted to train my model from scratch.
> Can you share which tools have you used to train a new model?
> 
> Thanks,
> Arun
Hi.
Please use the following link https://github.com/wkentaro/labelme to make annotations for your custom data set. transfer the data to coco format. Detailed info is attached to https://github.com/wkentaro/labelme/tree/master/examples/instance_segmentation. After that you can change the files in the yolact/data/config.py. line 111 to line 117. Pls. do not forget to change your class numbers on line 661.

**Comment by arunmp2004** [comment]
Thank you for sharing.

**Comment by dbolya** [comment]
@jonguo111 That P3 size is correct, and make sure you're loading the right config for evaluation if your filename doesn't have the config name in it (using `--config=...` in eval).
