### ISSUE TITLE
latency for realtime evaluation

### ISSUE THREAD

**Issue by Nyam10aa** [dbolya/yolact#378]
Thank your for your great work. I'm using Yolact for realtime semantic segmentation task. Fps is approximately 30fps and that is no problem, but there is latency around 0.5sec(~15frames). Do you have any quantitive results on latency and please give me some advice or recommendation to reduce that.

**Comment by Auth0rM0rgan** [comment]
Set `--video_multiframe` to 1.

**Comment by dbolya** [comment]
Yeah, the webcam pipeline works on parts of frames in parallel (to decrease GPU idle time) so there's lag. The best you can do without rewriting it is `--video_multiframe=1`.
