### ISSUE TITLE
Problems encountered while training my own dataset

### ISSUE THREAD

**Issue by wlsonia** [dbolya/yolact#38]
Hi,
In order to solve the stacking problem of the same object, I have trained my data set as required, but there are some masks that cannot completely cover the object, only part of them can be covered. Do you know what this is about? Do you have any Suggestions for modification?
Looking forward to your reply,thank you.

**Comment by dbolya** [comment]
What do you mean by "stacking problem"? Do you mean multiple detections for the same object? Box-based NMS isn't perfect, sadly so those will persists. The best way to deal with that is to find an appropriate score threshold that cuts out most of the duplicate detections. Or you can play with the NMS threshold on this line:
https://github.com/dbolya/yolact/blob/a70b68dd70aac5a1f41789771a66fb33adba2809/yolact.py#L453

And can you give examples of your new problem with objects not being fully covered (as well as some examples of your training data)?

**Comment by wlsonia** [comment]
The stacking problem is when two identical objects are stacked on top of each other, identifying the objects above and drawing a mask

**Comment by dbolya** [comment]
Can you give me an example of your training data, and an example of how YOLACT is failing?

**Comment by wlsonia** [comment]
![32](https://user-images.githubusercontent.com/35325607/57603552-9233f900-7594-11e9-97ad-5fc8eaf97754.png)
![103](https://user-images.githubusercontent.com/35325607/57603571-9e1fbb00-7594-11e9-945c-65426abcb167.png)

**Comment by dbolya** [comment]
Hmm that's weird, it seems to be a clean line down the intersection between the objects. Usually YOLACT errors are the other way around (the object is fully masked out except for the intersection). Are you sure your training data is correct?

If you verified that it is, maybe you can try fine tuning instead of training from scratch? See #36.

**Comment by wlsonia** [comment]
ok,I'll try,thank you
