### ISSUE TITLE
How to set window width, height size when using webcam?

### ISSUE THREAD

**Issue by sjlee1125** [dbolya/yolact#380]
I have tried to detect object using webcam.
I followed Readme file and I want to Full size of window.
But I can't find option of width, height And there wasn't maximize button..
Here is shell script to use webcam
```
python3 eval.py --trained_model=weights/yolact_base_54_800000.pth --score_threshold=0.15 --top_k=15 --video_multiframe=4 --video=0
```

And I tried 
```
mng = plt.get_current_fig_manager()
mng.frame.Maximize(True)
```
It doesnt work...
How to set window width, height size when using webcam?
Please help me...

My OS is Ubuntu 16.04 Desktop

**Comment by sjlee1125** [comment]
My OS is Ubuntu 16.04 Desktop

**Comment by dbolya** [comment]
Here:
https://github.com/dbolya/yolact/blob/b97e82d809e5e69dc628930070a44442fd23617a/eval.py#L644

Add:
```
vid.set(cv2.CAP_PROP_FRAME_WIDTH, <diesired_width>)
vid.set(cv2.CAP_PROP_FRAME_HEIGHT, <diesired_height>)
```
