### ISSUE TITLE
scripts/cluster_bbox_sizes.py bug

### ISSUE THREAD

**Issue by northeastsquare** [dbolya/yolact#381]
```
def to_relative(bboxes):
	return bboxes[:, 2:4] / bboxes[:, :2]
```

I think it should be : return bboxes[:, 4:6] / bboxes[:, :2]
because in bboxes: [image_w, image_h, x, y, w,h]
so the following function can get box w,h in max_size scale
```
def process(bboxes):
	return to_relative(bboxes) * max_size
```

**Comment by dbolya** [comment]
It probably should be `bboxes[:, 2:] / bboxes[:, :2]` but ¯\\\_(ツ)\_/¯ idk I haven't touched that code in a long time and it's not supported.
