### ISSUE TITLE
small object detection is not good compared to detectron2 maskrcnn

### ISSUE THREAD

**Issue by northeastsquare** [dbolya/yolact#384]
this is yolact ++ result:
![ch17_20191230040323 (029204)2020-01-14-00-06-21](https://user-images.githubusercontent.com/3086078/76694674-c09ccc00-66b0-11ea-9cf8-24f29c46d7d5.png)
while following is maskrcnn's result:
![screenshot](https://user-images.githubusercontent.com/3086078/76694706-3dc84100-66b1-11ea-83de-a39b37410ecc.png)

**Comment by DINOUS11** [comment]
Like they said in the paper this will not be a problem, trade off for speed

**Comment by dbolya** [comment]
If you don't care about the time taken, YOLACT's not really relevant. Use Mask R-CNN (or better yet, HTC) instead.
