### ISSUE TITLE
Train 4 days with batchsize 14 but no loss decrase or mAP increase

### ISSUE THREAD

**Issue by DINOUS11** [dbolya/yolact#390]
![image](https://user-images.githubusercontent.com/62002655/77053579-e3611480-6a11-11ea-9870-3d140bd844f1.png)
I wonder if the annotations label have to follow order like the id, all the class 1 have to be in id [0,10] and other class have to be [11,...] because my id follow image, image have 10 objects with 10 class will be [0,1] not same class.

Train dataset is 4300 images, val/test set is 1440 but training didnt go on, can you pls check if same class objects have to follow id?

**Comment by dbolya** [comment]
The annotation ID doesn't need to have any relationship with the category ID. The image IDs just need to be linked up correctly with the IDs in the `'image'` list.
