### ISSUE TITLE
I have 6GB memory GPU, can I still do the training ? 

### ISSUE THREAD

**Issue by jediofgever** [dbolya/yolact#391]
Hi , thanks for contributing  to open source community.

I have created a dateset in format of COCO now I would like to proceed to the training, but I got stuck at cuda out of memory error, I have reduced to batch_size to even 1 but it will still not run the training.

Can my GPU still be used ?

**Comment by pzs7602** [comment]
try to reduce the max_size in config, this is the max size of the image

**Comment by jediofgever** [comment]
ok, but my training images are with `1280x720` size, so what will happen to images if i set max_size to lets say 550 ?

**Comment by pzs7602** [comment]
yes

**Comment by dbolya** [comment]
Yeah you should not change `max_size`. Changing it to `1280` was probably why you were running out of memory.
