### ISSUE TITLE
error during training

### ISSUE THREAD

**Issue by sabine1993** [dbolya/yolact#392]
Hi,
I am using my own dataset and transformed it to the coco dataset.
When I try to run the train.py script I get an error.
In yolact.py line 514:
is_script_conv = 'Script' in type(module).__name__ \
                and all_in(module.__dict__['_constants_set'], conv_constants) \
                and all_in(conv_constants, module.__dict__['_constants_set'])

I get an Keyerror for the key '_constants_set'
Does anyone have the same problem or anyone has a solution?
Thanks for the help.

**Comment by forJiankeLiuend** [comment]
hi, i meet the same problem，so, how do you fix it?
