### ISSUE TITLE
training only for object detection

### ISSUE THREAD

**Issue by sabine1993** [dbolya/yolact#395]
Hi does anyone know if yolact can be used for only object detection and not for detection and segmentation?
thanks a lot

**Comment by jasonkena** [comment]
Yes you could, by removing all of the instance-segmentation predictors, such as `mask_layer` and `proto_net`, and their respective losses.

But may I ask why you would do that? YOLACT was built specifically for instance segmentation by introducing these mask coefficients. If you do not need them, I would recommend you to look at [SSD](https://github.com/amdegroot/ssd.pytorch) or [Faster-RCNN](https://github.com/chenyuntc/simple-faster-rcnn-pytorch).
