### ISSUE TITLE
size mismatch 

### ISSUE THREAD

**Issue by Auth0rM0rgan** [dbolya/yolact#400]
Hey @dbolya, 

I'm trying to use ResNet34 as a backbone but the mismatch error shows up. Could you please tell me how to solve it?
```
RuntimeError: Error(s) in loading state_dict for ResNetBackbone:
        size mismatch for layers.0.0.conv1.weight: copying a param with shape torch.Size([64, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 1, 1]).
        size mismatch for layers.0.1.conv1.weight: copying a param with shape torch.Size([64, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 256, 1, 1]).
        size mismatch for layers.1.0.conv1.weight: copying a param with shape torch.Size([128, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 256, 1, 1]).
        size mismatch for layers.1.0.downsample.0.weight: copying a param with shape torch.Size([128, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 256, 1, 1]).
        size mismatch for layers.1.0.downsample.1.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for layers.1.0.downsample.1.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for layers.1.0.downsample.1.running_mean: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for layers.1.0.downsample.1.running_var: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for layers.1.1.conv1.weight: copying a param with shape torch.Size([128, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 512, 1, 1]).
        size mismatch for layers.2.0.conv1.weight: copying a param with shape torch.Size([256, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 512, 1, 1]).
        size mismatch for layers.2.0.downsample.0.weight: copying a param with shape torch.Size([256, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([1024, 512, 1, 1]).
        size mismatch for layers.2.0.downsample.1.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for layers.2.0.downsample.1.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for layers.2.0.downsample.1.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for layers.2.0.downsample.1.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for layers.2.1.conv1.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 1024, 1, 1]).
        size mismatch for layers.3.0.conv1.weight: copying a param with shape torch.Size([512, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 1024, 1, 1]).
        size mismatch for layers.3.0.downsample.0.weight: copying a param with shape torch.Size([512, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([2048, 1024, 1, 1]).
        size mismatch for layers.3.0.downsample.1.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.3.0.downsample.1.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.3.0.downsample.1.running_mean: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.3.0.downsample.1.running_var: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.3.1.conv1.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 2048, 1, 1]).
Thanks!

**Comment by Auth0rM0rgan** [comment]
@abhigoku10, Do you know how can I solve my problem? what else changes I need to do to be able to train with ResNet34? Thanks!

**Comment by jasonkena** [comment]
Sure! You can just follow the instructions in https://github.com/dbolya/yolact/issues/36

@dbolya I think you should pin https://github.com/dbolya/yolact/issues/36, so many people are asking about it

**Comment by Auth0rM0rgan** [comment]
@jasonkena, I have already done that but still not working :|  I don't want to do finetuning. I want to train the model from scratch with ResNet34 instead of ResNet50 or ResNet101. I have downloaded the ResNet34 pretrained model from PyTorch website and placed it in weights folder. Also I did the changes in the config file but I'm getting mismatch error which I don't know how to slove it. Do I need to do any other changes to be able to train with ResNet34 as a backbone? Thanks

**Comment by jasonkena** [comment]
Yes, the instructions are for https://github.com/dbolya/yolact/issues/36, but they should work for any dimension mismatch due to `state_dict` loading.

**Comment by Auth0rM0rgan** [comment]
I'm able to train the network with ResNet34 by addind `~try-except ` in the backbone.py for this line https://github.com/dbolya/yolact/blob/b97e82d809e5e69dc628930070a44442fd23617a/backbone.py#L154 (#36 is for finetuning).  @dbolya , @jasonkena, What is the reason of getting the size mismatch errors when I change the backbone to anything else than the default? Is it going to impact the performance when I'm ignoring the error with  `~try-except `? Am I doing something wrong?

Thansk!

**Comment by jasonkena** [comment]
No, it should not impact your performance (ignoring the fact that ResNet 34 is smaller than 101).

So when the YOLACT creates a model (before inputting weights), all of these parameters have all of their own dimensions. When you want to load the weights from a file with different dimensions, it will raise an error, and hence the try-except. As I believe @dbolya stated, the weights of the model that cannot be imported from the file will just be randomly initialized.

As for why ResNet 34 is not supported, I bet it has something to do with `'args': ([3, 4, 6, 3],),`. But the code will run anyways just using the `try-except`.

**Comment by Auth0rM0rgan** [comment]
Thanks for the information. So, how can I modify the dimensions to not get this error anymore (not only for ResNet)? I know how to print out the keys pretrained weight file but not the backbone implementation to be able to match the keys between these two.

**Comment by jasonkena** [comment]
You can just try-except it, and let it be, you don't have to worry about the mismatch.

Or, you can lookup the architecture for ResNet 34, and find the `args` in `ResNetBackbone` that matches it.

**Comment by Eleanor456** [comment]
hello, 
I got the same problem, could you give me some suggestion about how to solve this problem?
Thank you!

**Comment by an99990** [comment]
im having this issue when i want to use the trained model. I have a model that i trained on custom dataset. and now i am loading it without success.

Does anyone have an idea ?

```
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Yolact:
	size mismatch for prediction_layers.0.conf_layer.weight: copying a param with shape torch.Size([18, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([243, 256, 3, 3]).
	size mismatch for prediction_layers.0.conf_layer.bias: copying a param with shape torch.Size([18]) from checkpoint, the shape in current model is torch.Size([243]).
	size mismatch for semantic_seg_conv.weight: copying a param with shape torch.Size([5, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 256, 1, 1]).
	size mismatch for semantic_seg_conv.bias: copying a param with shape torch.Size([5]) from checkpoint, the shape in current model is torch.Size([80])
```

**Comment by wsasdsda** [comment]
> im having this issue when i want to use the trained model. I have a model that i trained on custom dataset. and now i am loading it without success.
> 
> Does anyone have an idea ?
> 
> ```
> raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for Yolact:
> 	size mismatch for prediction_layers.0.conf_layer.weight: copying a param with shape torch.Size([18, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([243, 256, 3, 3]).
> 	size mismatch for prediction_layers.0.conf_layer.bias: copying a param with shape torch.Size([18]) from checkpoint, the shape in current model is torch.Size([243]).
> 	size mismatch for semantic_seg_conv.weight: copying a param with shape torch.Size([5, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 256, 1, 1]).
> 	size mismatch for semantic_seg_conv.bias: copying a param with shape torch.Size([5]) from checkpoint, the shape in current model is torch.Size([80])
> ```

Have you fixed this promble?I meet the same error now!
