### ISSUE TITLE
return mask of an specific class 

### ISSUE THREAD

**Issue by gbhgit** [dbolya/yolact#401]
Hi, great work. Yolact is a beautiful technology . How i return only mask of a specific object class. I already know how to retrieve mask using this issue #286, but how can specify to return a mask of a specific class?

**Comment by gbhgit** [comment]
Hello, here how i solved:

    `if args.display_masks and cfg.eval_mask_branch and num_dets_to_consider > 0:
        masks = masks[:num_dets_to_consider, :, :, None]
        nzCount = -1
        for i in range(num_dets_to_consider):
            temp_class_check = cfg.dataset.class_names[classes[i]]
            if temp_class_check == 'person':
                msk = masks[i, :, :, None]
                mask = msk.view(1, masks.shape[1], masks.shape[2], masks.shape[3])
                img_gpu = (mask.sum(dim=0) >= 1).float().expand(-1, -1, 3).contiguous()
                img_numpy_aux = (img_gpu * 255).byte().cpu().numpy()
                img_numpy_aux = cv2.cvtColor(img_numpy_aux, cv2.COLOR_BGR2GRAY)

                if nzCount == -1:
                    nzCount = 0
                    img_numpy = img_numpy_aux
                else:
                    if cv2.countNonZero(img_numpy_aux) > cv2.countNonZero(img_numpy):
                        img_numpy = img_numpy_aux

        img_gpu = (masks.sum(dim=0) >= 1).float().expand(-1, -1, 3).contiguous()
    else:
        img_gpu *= 0`

**Comment by gbhgit** [comment]
Thanks for the great work done in this repository.

**Comment by Marwen-Bhj** [comment]
I want the background to be green and the detections to remains as RGB whaat should I change ?

**Comment by gbhgit** [comment]
hello, after change the code this according to my above answer you only need to get the output image and the input image and do:

`aux = cv2.multiply(mask_output, input_image_RGB)
`

Than case red, green and blue values of a pixel is equal to 0 change the green value to 255.

**Comment by kimhyuenjun** [comment]
This code is a great result. I have a question, can I ask a question?

If there are multiple objects in a photo, I want to save the return mask of a specific class of each object separately. What should I do?

**Comment by gbhgit** [comment]
You can follow my solution in [https://github.com/dbolya/yolact/issues/401#issuecomment-605087169](link), and line below explain how to get a specific class:
`if temp_class_check == 'person':`

**Comment by kimhyuenjun** [comment]
Your code used to run successfully. Thank you

What I want to do is to individually return and save the mask if there are multiple objects in the photo.

For example, if there are 2 dogs in the picture, you want to save each of the 2 masks.

**Comment by xI-820815641** [comment]
> Your code used to run successfully. Thank you
> 
> What I want to do is to individually return and save the mask if there are multiple objects in the photo.
> 
> For example, if there are 2 dogs in the picture, you want to save each of the 2 masks.

Hello, have you solved this problem yet？
