### ISSUE TITLE
how to use your scripts to generate my own anchor sizes and scales?

### ISSUE THREAD

**Issue by noobgrow** [dbolya/yolact#41]
Dear Sir:
     I have some problem to understand your cluster_bbox_sizes.py, optimize_bboxes.py and bbox_recall.py. I really want use them to set the parameters: scales aspect_ratios and conv_sizes more reasonable.
 Could you please explain a little of what these means? Thanks a lot!

I use the default paras as the yolact_base.cfg does, and test the scripts on a dataset
`scales = [ [24],[48],[96],[192],[384] ]
aspect_ratios = [ [[1, 1/sqrt(2), sqrt(2)]] ]*5
conv_sizes = [(69, 69), (35, 35), (18, 18), (9, 9),(5,5)]
`
here are the results:
from: cluster
`0.062 (18) aspect ratios:
        17.71 (8)
        5.23 (8)
        109.76 (2)

0.146 (70) aspect ratios:
        4.39 (34)
        2.26 (30)
        0.65 (6)

0.241 (125) aspect ratios:
        1.12 (103)
        0.23 (21)
        0.00 (1)
`

from optimize_bbox:

`(Iteration 9) Aspect Ratios: [[[19.03, 0.55, 1.13]], [[13.94, 13.64, 14.24]], [[13.94, 13.64, 14.24]], [[13.94, 13.64, 14.24]], [[13.94, 13.64, 14.24]]]

scales = [[17.53], [60.94], [108.94], [204.94], [396.94]]

aspect_ratios = [[[19.03, 0.55, 1.13]], [[13.94, 13.64, 14.24]], [[13.94, 13.64, 14.24]], [[13.94, 13.64, 14.24]], [[13.94, 13.64, 14.24]]]
`

from  bbox_recall:

`Total recall: 33.80

small recall: 0.00
medium recall: 0.00
large recall: 46.75
`

Thanks a lot! It's a bit hard for me >o<

**Comment by dbolya** [comment]
`optimize_bbox` was a test that unfortunately never ended up working (instead of clustering scales and aspect ratios, how about we try to directly optimize the recall?) The scales and aspect ratios it produces result in much worse performance.

`cluster_bbox_sizes` is the standard approach, but it hasn't been updated for a very long time so is completely broken (it looks like it's suggesting aspect ratios of 17.7 and 109.6 which are a little on the absurd side).

I can update `cluster_bbox_sizes` if you want me to, but I should probably get rid of `optimize_bbox`.

**Comment by noobgrow** [comment]
Yes please, thanks for your kindness and quick reply, and how can I have different length-width ratio prior box? right now setting 'aspect_ratios = [ [[1, 1/sqrt(2), sqrt(2)]] ]*5  ' is just the square prior box right? 

Secondly, could u provide the script of ploting the P-R image? I want to learn it from your fantastic work.

Besides, Can I regard your network when using the darknet backbone and yolo loss as an enhanced YOLO by adding a mask branch and protonet?

**Comment by dbolya** [comment]
Actually those aren't square (at least well they're not supposed to be). Aspect ratio means the ratio between width and height. So an aspect ratio of sqrt(2) means that the width is sqrt(2) times the height (i.e., w/h = sqrt(2)). I realized I had a bug while implementing this (see #19) which resulted in the width and height set to the same number (equal to what the width should have been). For paper reproducability reasons, I'm keeping the bug in until we release v1.1, but if you want to fix it yourself, change this line:
https://github.com/dbolya/yolact/blob/ad167c0a72169b68a0e68ea7bcd0e6b0b9e53834/yolact.py#L266
to:
```scale / ar / cfg.max_size```

Then by P-R you mean the precision-recall curve? I don't have a script to plot that, but you can find the precisions and recalls here if you want to plot them yourself:
https://github.com/dbolya/yolact/blob/ad167c0a72169b68a0e68ea7bcd0e6b0b9e53834/eval.py#L498

And go ahead and try to implement YOLACT in YOLO if you'd like. Let me know if you get some good results!

Also, I've updated the clustering script. To use, run `python scripts/save_bboxes.py` from the root YOLACT directory, which will save a numpy array of all the bounding boxes in the 2017 COCO training set. Once you have that run `python scripts/cluster_bbox_sizes.py` and it'll output 5 suggested bounding box scales, along with 3 aspect ratios for each scale. To use those scales and aspect ratios, simply replace
https://github.com/dbolya/yolact/blob/fd84079b53e2325b5bb451a0029736f20cbee0ed/data/config.py#L590
with the scales it gives and 
https://github.com/dbolya/yolact/blob/fd84079b53e2325b5bb451a0029736f20cbee0ed/data/config.py#L589
with the aspect ratios (`[ [[scale1_ar1, scale1_ar2, scale1_ar3]], [[scale2_ar1, scale2_ar2, scale2_ar3]], etc. ]`)

**Comment by noobgrow** [comment]
thank you! I'll try it!

**Comment by shoutOutYangJie** [comment]
After I read your conversations, I am curious about what is the function of   "pred_scales".  I though it is calculated by receptived field, because different layer has different receptive field.   P3 is shallow layer so it has the scale of "24".    So am I wrong?  should it be calculated by "cluster_bbox_sizes.py".  I also want to apply this amazing work on my own dataset, so i want to prepare the bbox label.

**Comment by WangweiDamon** [comment]
@dbolya 
Hello, I have some problems about the 'pred_scales' and 'pred_aspect_ratios' of my own custom dataset.
When I use the "scripts/save_bboxes.py" and "scripts/cluster_bbox_sizes.py",  and its output 5 suggested bounding box scales, along with 3 aspect ratios for each scale,just as follows:
66.809 (11494) aspect ratios:
	0.24 (11469)
	11.71 (23)
	46.02 (2)

132.674 (16558) aspect ratios:
	0.44 (11681)
	1.26 (4290)
	3.41 (587)

190.558 (20370) aspect ratios:
	0.62 (10948)
	1.50 (7223)
	2.96 (2199)

244.376 (18492) aspect ratios:
	0.70 (7798)
	1.39 (6981)
	2.35 (3713)

313.797 (8148) aspect ratios:
	1.24 (3485)
	0.78 (2890)
	1.79 (1773)

,So how to choose the final 'pred_scales' and 'pred_aspect_ratios' of my own custom dataset?
I choosed  'pred_scales':  [[66], [132], [190], [244], [314]], 
                  'pred_aspect_ratios': [ [[0.24, 11.71, 46.02]], [[0.44, 1.26, 3.41]], [[0.62, 1.50, 2.96]], [[0.70, 1.39, 2.35]], [[1.24, 0.78, 1.79]] ],  and make the   'use_square_anchors': False,
But it seems get worse than your original choice which means  'pred_aspect_ratios': [ [[1, 1/2, 2]] ]*5,
        'pred_scales': [[24], [48], [96], [192], [384]],  'use_square_anchors': True    Could you tell me why?   Thank you so so much!

**Comment by WangweiDamon** [comment]
@dbolya When I try "instances_train2017.json",  the 5 suggested bounding box scales, along with 3 aspect ratios for each scale just as follows:
54.112 (132798) aspect ratios:
	4.03 (123821)
	107.64 (6696)
	277.87 (2281)
141.556 (183815) aspect ratios:
	0.83 (146943)
	4.93 (29795)
	12.59 (7077)
221.548 (202083) aspect ratios:
	0.74 (131522)
	2.16 (52024)
	4.44 (18537)
301.444 (176328) aspect ratios:
	0.76 (86264)
	1.52 (61630)
	2.54 (28434)
395.099 (95228) aspect ratios:
	1.24 (38894)
	0.83 (36110)
	1.74 (20224)

it seems different from your original choice?   Could explain why you choose  'pred_aspect_ratios': [ [[1, 1/2, 2]] ]*5,
'pred_scales': [[24], [48], [96], [192], [384]], 'use_square_anchors': True ?  Thank you so much.

**Comment by dbolya** [comment]
Sorry for the delay, we didn't cluster our anchor boxes. We just used the standard 1, 1/2, 2 aspect ratios and modified the 32...512 scales slightly since our image size is smaller than what is standard.

I also don't recommend using different scales and aspect ratios for different pred layers because the same prediction head is on every FPN layer, meaning you're asking the same head to acclimate to wildly different anchors. That script was from when we were still using SSD, and that had an individual prediction head per layer.

**Comment by shoutOutYangJie** [comment]
Will you release your yolact++?





------------------ Original ------------------

**Comment by dbolya** [comment]
I released it around 15 minutes ago ;^ )
