### ISSUE TITLE
How to map ids to names

### ISSUE THREAD

**Issue by Harut0726** [dbolya/yolact#418]
I run eval.py with --output_coco_json flag on **unlabeled** data and generate json file like this:
```python 
[{"image_id": 131, "category_id": 1, "segmentation": {"size": [720, 1280], "counts": "nl_3h0ae0<E9I6J5I7G:I6L5K5L3M3M4L3M3M3N2M4M2M4M2N2M3N2N2N2N3M2N2N2M3N2N2N2N1O2O1N1O2 ... etc ...]
```
I wan't to know what this "image_id" means and how to map it to the real name of the image file.

**Comment by Harut0726** [comment]
Sorry, solved.

**Comment by nguyenhoaiphuong0710** [comment]
@Harut0726 Can u tell me how to map image_id to real name image? Thanks.
