### ISSUE TITLE
Transfer Learning

### ISSUE THREAD

**Issue by mrtechnoo** [dbolya/yolact#436]
I am trying to train my model on custom data. 
i want to train only final layer

**Comment by Maxinho96** [comment]
You must check #36 and and #334.
In my fork I have done it and added `--only_last_layer` argument to `train.py`: https://github.com/Maxinho96/yolact

**Comment by rkishore** [comment]
@Maxinho96, can you share the train command you used?

**Comment by Maxinho96** [comment]
> @Maxinho96, can you share the train command you used?
Something like this:

```
!python train.py \
--save_folder="your/checkpoints/folder" \
--log_folder="your/logs/folder" \
--config=yolact_plus_resnet50_config \
--resume=weights/yolact_plus_resnet50_54_800000.pth \
--validation_iter=500 \
--save_interval=500 \
--start_iter=0 \
--batch_size=8 \
--lr=1e-5 \
--momentum=0.9 \
--decay=5e-4 \
--gamma=0.1
```

**Comment by mrtechnoo** [comment]
thanks @Maxinho96  i am closing this issue
