### ISSUE TITLE
a very very very strange problem on windows

### ISSUE THREAD

**Issue by zhuqiang00099** [dbolya/yolact#45]
I think thers is something incompatible with windows  in yolact.py

run the eval.py says cuda unkown error, the error locates at 'torch.set_default_tensor_type('torch.cuda.FloatTensor')'. It looks like cuda init unsuccessfully. 

I try to put  'torch.set_default_tensor_type('torch.cuda.FloatTensor')'  from top line to down,like this:
```python
#try1
import torch
torch.set_default_tensor_type('torch.cuda.FloatTensor')
from data import COCODetection, get_label_map, MEANS, COLORS
...

#try2
import torch
...
torch.set_default_tensor_type('torch.cuda.FloatTensor')
from yolact import Yolact
...

```
then I find that put it before 'from yolact import Yolact' works, otherwise failed. 

Now, at the begin of yolact.py, write as follow:
```python
import torch
torch.set_default_tensor_type('torch.cuda.FloatTensor')
from data import COCODetection, get_label_map, MEANS, COLORS
...
```

**Comment by dbolya** [comment]
Hmm that is pretty weird indeed. I do most of my testing on Win10 so it's probably not solely a Windows issue. Not to mention, importing Yolact should not instantiate any tensors so changing the default tensor type before importing should have no effect (key word I guess there is **should**). Maybe it has to do with your environment?

What's your Pytorch, CUDA, and Python versions? Are you on the latest commit? And when you say "run the eval.py says cuda unkown error, the error locates at...", do you mean line 975 in `eval.py`?

**Comment by zhuqiang00099** [comment]
@dbolya 
- try both pytorch  cu90-1.0.1 and cu90-1.1.0. by the way, I would like to try cu100-1.1.0,but failed when install...
- python version is 3.6.
- clone the project today...
- run the eval.py in two ways
   1. use cmd, like
      ```shell
      python eval.py --video 'test.mp4' ......
      ```
   2. use pycharm, edit the default args' value, then right click,then run..

**Comment by zhuqiang00099** [comment]
haha... try another way, edit the yolact.py  as follows to make jit disable, then works.
```python
use_jit = torch.cuda.device_count() <= 1
if not use_jit:
    print('Multiple GPUs detected! Turning off JIT.')
use_jit = False
ScriptModuleWrapper = torch.jit.ScriptModule if use_jit else nn.Module
script_method_wrapper = torch.jit.script_method if use_jit else lambda fn, _rcn=None: fn
```

**Comment by dbolya** [comment]
Okay it looks like this is a known Pytorch issue (https://github.com/pytorch/pytorch/issues/17108) on windows with some Nvidia drivers for Pytorch 1.0.1 and above.

I think the problem is actually with that piece of code there, which would be affected by the above issue. Can you revert your changes and pull my latest commit to see if that workaround fixed this?

**Comment by zhuqiang00099** [comment]
@dbolya  it works...hahah  you're pretty good... thanks a lot..   xiexie dashen

**Comment by dbolya** [comment]
Good to hear! Yeah Pytorch doesn't test as much as it potentially should on Windows.
