### ISSUE TITLE
How to tune the code so as to get results only for say persons and car classes? 

### ISSUE THREAD

**Issue by PareshKamble** [dbolya/yolact#453]
Hello @dbolya,
Yours is an amazing piece of work.
However, in my application, I need detection and segmentation only on a few classes like say **person** and **car**. Can you please let me know where to tune the code so as to get the desired results?
Thanking you in anticipation!

**Comment by Param2302** [comment]
Hello @PareshKamble. Did you find a solution to your issue? If yes, it would be great if you could share it!

**Comment by PareshKamble** [comment]
Hi @Param2302 ,
Say, if I want only **person** and **car** class and filter out the rest of the classes.
Kindly follow the below given steps:
1) From **data/config.py** **line# 31** **COCO_CLASSES**, find out the class index of **person** and **car** classes which are 0 and 2 resp. You may also directly search in **COCO_LABEL_MAP** dictionary but, remember, you need to subtract 1 from the value (class index like **_class_index-1_**) and not the key of the dict.
2) Add the below given lines at **line# 57** of **layers/output_utils.py**. 
```
boxes = torch.cat((boxes[classes==0], boxes[classes==2]),dim=0)
scores = torch.cat((scores[classes==0], scores[classes==2]),dim=0)
masks = torch.cat((masks[classes==0], masks[classes==2]),dim=0)
classes = torch.cat((classes[classes==0], classes[classes==2]),dim=0)
```
**classes** should come at the end. It is important.
Remember, if you need more classes, go on adding it in `boxes = torch.cat((boxes[classes==0], boxes[classes==2], boxes[classes==12], ...),dim=0)`. Similarly, do it for scores, masks and classes.

**Optional:** If you get any error saying that boxes, scores, masks or classes are empty,
then wrap the code between line# 58 - 120 in **layers/output_utils.py** by an if condition ```if classes.nelement()!=0:```, just to let the code run even if the input image does not have the desired classes. 
**_Note:_** I do not claim this is the only way. There may be a better one.

**Comment by Marwen-Bhj** [comment]
@PareshKamble  getting this error following your solution : 
```
Traceback (most recent call last):
  File "./yolact/eval.py", line 1105, in <module>
    evaluate(net, dataset)
  File "./yolact/eval.py", line 885, in evaluate
    evalimages(net, inp, out)
  File "./yolact/eval.py", line 623, in evalimages
    evalimage(net, path, out_path)
  File "./yolact/eval.py", line 600, in evalimage
    img_numpy = prep_display(preds, frame, None, None, undo_transform=False)
  File "./yolact/eval.py", line 151, in prep_display
    score_threshold   = args.score_threshold)
  File "/content/yolact/layers/output_utils.py", line 57, in postprocess
    boxes = torch.cat((boxes[classes==0]),dim=0)
TypeError: cat() received an invalid combination of arguments - got (Tensor, dim=int), but expected one of:
 * (tuple of Tensors tensors, name dim, Tensor out)
 * (tuple of Tensors tensors, int dim, Tensor out)
```

**Comment by PareshKamble** [comment]
@Marwen-Bhj what is the version of pytorch you are using?

**Comment by PareshKamble** [comment]
Hi @areebsyed,
This seems to be altogether different RuntimeError.
I am not aware of this yet.
I suggest you to check the shapes of masks and boxes and see if its crop function is working fine for a few cases.
All the best!

**Comment by areebsyed** [comment]
> Hi @areebsyed,
> This seems to be altogether different RuntimeError.
> I am not aware of this yet.
> I suggest you to check the shapes of masks and boxes and see if its crop function is working fine for a few cases.
> All the best!

Hi just figured out the issue; your solution above works for me on images having persons and cars only for example. But when there is a frame with none of the specifically selected classes, then it gives out the error I wrote above and as following:

`Traceback (most recent call last):
  File "eval.py", line 1105, in <module>
    evaluate(net, dataset)
  File "eval.py", line 881, in evaluate
    evalimage(net, args.image)
  File "eval.py", line 600, in evalimage
    img_numpy = prep_display(preds, frame, None, None, undo_transform=False)
  File "eval.py", line 151, in prep_display
    score_threshold   = args.score_threshold)
  File "/home/user/Documents/yolact/layers/output_utils.py", line 79, in postprocess
    masks = crop(masks, boxes)
RuntimeError: strides[cur - 1] == sizes[cur] * strides[cur] INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1573049310284/work/torch/csrc/jit/fuser/executor.cpp:175, please report a bug to PyTorch. 
The above operation failed in interpreter, with the following stack trace:`

**Comment by PareshKamble** [comment]
@areebsyed I suggest use a try catch to evade the issue.

**Comment by areebsyed** [comment]
> @areebsyed I suggest use a try catch to evade the issue.

@PareshKamble thankyou so much for your concern and quick replies.

I found the solution. It may also interest you!

https://github.com/dbolya/yolact/issues/218#issuecomment-577963416

**Comment by PareshKamble** [comment]
@areebsyed Thank you.
The solution is interesting and simple.

**Comment by wafaer** [comment]
> Hi @Param2302 , Say, if I want only **person** and **car** class and filter out the rest of the classes. Kindly follow the below given steps:
> 
> 1. From **data/config.py** **line# 31** **COCO_CLASSES**, find out the class index of **person** and **car** classes which are 0 and 2 resp. You may also directly search in **COCO_LABEL_MAP** dictionary but, remember, you need to subtract 1 from the value (class index like **_class_index-1_**) and not the key of the dict.
> 2. Add the below given lines at **line# 57** of **layers/output_utils.py**.
> 
> ```
> boxes = torch.cat((boxes[classes==0], boxes[classes==2]),dim=0)
> scores = torch.cat((scores[classes==0], scores[classes==2]),dim=0)
> masks = torch.cat((masks[classes==0], masks[classes==2]),dim=0)
> classes = torch.cat((classes[classes==0], classes[classes==2]),dim=0)
> ```
> 
> **classes** should come at the end. It is important. Remember, if you need more classes, go on adding it in `boxes = torch.cat((boxes[classes==0], boxes[classes==2], boxes[classes==12], ...),dim=0)`. Similarly, do it for scores, masks and classes.
> 
> **Optional:** If you get any error saying that boxes, scores, masks or classes are empty, then wrap the code between line# 58 - 120 in **layers/output_utils.py** by an if condition `if classes.nelement()!=0:`, just to let the code run even if the input image does not have the desired classes. **_Note:_** I do not claim this is the only way. There may be a better one.
> 
> Hope this helps you!
@PareshKamble，Hi, I am getting this error using your method
Traceback (most recent call last):
  File "/home/hermione/src/yolact-mask/eval_mask.py", line 1115, in <module>
    evaluate(net, dataset)
  File "/home/hermione/src/yolact-mask/eval_mask.py", line 895, in evaluate
    evalimages(net, inp, out)
  File "/home/hermione/src/yolact-mask/eval_mask.py", line 633, in evalimages
    evalimage(net, path, out_path)
  File "/home/hermione/src/yolact-mask/eval_mask.py", line 610, in evalimage
    img_numpy = prep_display(preds, frame, None, None, undo_transform=False)
  File "/home/hermione/src/yolact-mask/eval_mask.py", line 157, in prep_display
    idx = t[1].argsort(0, descending=True)[:args.top_k]
TypeError: 'NoneType' object is not subscriptable

**Comment by PareshKamble** [comment]
Hi @wafaer ,
It appears you are not getting anything in `t` variable.
Please check the output of `t`.

**Comment by wafaer** [comment]
> Hi @wafaer , It appears you are not getting anything in `t` variable. Please check the output of `t`.
@PareshKamble，Thank you very much for your reply, because I am a beginner in semantic segmentation, and I need to study the error report slowly. I use yolact to detect people and cars in the video. For frames with no people and cars, the pixel value is 0. In response to what you said, If you get any error saying that boxes, scores, masks or classes are empty, then wrap the code between line# 58 - 120 in layers/output_utils.py by an if condition if classes.nelement()!= 0:, I put if classes.nelement()!=0: in front of 58-120 and this error occurs. If you are interested, can you tell me the specific ideas, thank you very much.

**Comment by PareshKamble** [comment]
Dear @wafaer you may also try solution suggested by @areebsyed [here](https://github.com/dbolya/yolact/issues/218#issuecomment-577963416).

**Comment by wafaer** [comment]
> 
@PareshKamble，Thank you for your reply again, I'm very sorry to bother you.  I used the suggestion you found for me, and added [cur_scores[1] *= 0]to the line yolact/layers/functions/detection.py  83, the previous error still occurs。I am in output_utills.py, Add 
     boxes = torch.cat((boxes[classes==0], boxes[classes==2]), dim=0) after line py56
     scores = torch.cat((scores[classes==0], scores[classes==2]), dim=0)
     masks = torch.cat((masks[classes==0], masks[classes==2]), dim=0)
     classes = torch.cat((classes[classes==0], classes[classes==2]), dim=0) to achieve only detection of people and cars, what do you have for my modification and the result I want Suggestions?

**Comment by PareshKamble** [comment]
Dear @wafaer 
Sincere apologies, but I do not have any solution on this at the moment.
