### ISSUE TITLE
Segment every pixel in an image

### ISSUE THREAD

**Issue by jdonovanCS** [dbolya/yolact#485]
I found myself recently wanting to use YOLACT to segment every pixel in an image into a category. As of right now, I have trained a model, and I can visualize the segmentations through the instructions from the readme. I know that yolact is constructing more segmentations and bounding boxes than are being displayed on the screen. I'm wondering the best way to use these segmentations to produce an image where every pixel is assigned a category.

Any suggestions or thoughts on this are welcome. I'll be exploring the code to see if I can figure this out myself.

Also, if this is a duplicate issue, please close and link to previous issue.

Thank you!

**Comment by jdonovanCS** [comment]
Is the best way to use postprocess in layers.output_utils.py to get the masks? I can then use those with their confidence values to compute a category for every pixel.

**Comment by abhigoku10** [comment]
@jdonovanCS to segment every pixel in an image we should have labels right , currently yolact ++ is able to segment most of the object class very effectively provided annotations for it . So your intent can you elaborate it !!!. I am trying to add multi-task learning for yolact so that we can have a classification of the whole scene

**Comment by jdonovanCS** [comment]
I want to label every pixel in the input image into a category. Specifically, I am doing material classification, so I want to label every pixel into a material category whether that is sky, fabric, wood, foliage, etc. I have 23 material categories. I trained resnet50-fpn with yolact on segmentation masks that I have for these materials. When testing, it creates boxes and masks for foreground materials, but I want to take the maximum confidence material prediction for each pixel in the image to produce an image where every pixel has been assigned a category.

**Comment by SharifElfouly** [comment]
Hey @jdonovanCS , you need a model for semantic segmentation not for instance segmentation.

**Comment by jdonovanCS** [comment]
@SharifElfouly , delayed response to this, but indeed you are correct.
