### ISSUE TITLE
Mask annotation (RLE), mask mAP = 0

### ISSUE THREAD

**Issue by edwardnguyen1705** [dbolya/yolact#488]
Dear @dte ,
The mask annotation of my dataset is in RLE format. I follow the guideline how to train on a custom dataset, and everything seems to be wright except the mask mAP that is always zero. Here is the log of some first iterations:

![Screen Shot 2020-07-21 at 19 19 59](https://user-images.githubusercontent.com/7928673/88054526-ba02f180-cb87-11ea-8c94-f3259c70b37e.png)

Do you have any suggestions?
Thank you!

**Comment by davodogster** [comment]
@edwardnguyen1705  Hi can the model train successfully with the RLE format? Uncompressed RLE?

**Comment by edwardnguyen1705** [comment]
@davodogster you can take a look at this [mmdetection](https://github.com/open-mmlab/mmdetection/tree/master/configs/yolact) repo. If your data is not in `RLE` format, you can convert by [encode](https://github.com/dbolya/yolact/blob/57b8f2d95e62e2e649b382f516ab41f949b57239/eval.py#L322).
