### ISSUE TITLE
'max_size' or 'mask_size'?

### ISSUE THREAD

**Issue by Wilbur529** [dbolya/yolact#49]
Hi, i think you may want to use cfg.max_size, should it be?
https://github.com/dbolya/yolact/blob/d04c948f3426d4f77d0d1421b1b46b1a5127b7cd/layers/functions/detection.py#L188
https://github.com/dbolya/yolact/blob/d04c948f3426d4f77d0d1421b1b46b1a5127b7cd/layers/functions/detection.py#L189

**Comment by dbolya** [comment]
That's correct, thanks for pointing it out. I pushed a fix, but it looks like it doesn't make much of a difference overall (with 400 images, +0.1 box mAP, -0.1 mask mAP, I'm sure it'd equalize over more images though).
