### ISSUE TITLE
training loss type "I"

### ISSUE THREAD

**Issue by amaanda** [dbolya/yolact#491]
hello! first of all, thanks for sharing your work with us.
i have a question concerning the training losses. there is a loss key on yolact/layers/module: https://github.com/dbolya/yolact/blob/530415ff8a3f8f97b8deb58508ea74c84ea147b2/layers/modules/multibox_loss.py#L196:

however, i can't find the explanation for all the training losses in that key. to be more specific, i don't know what `"I"` means.
https://github.com/dbolya/yolact/blob/b97e82d809e5e69dc628930070a44442fd23617a/train.py#L120

could someone help me clarify this? 
thanks!

**Comment by sainatarajan** [comment]
Take a look at this: 
https://github.com/dbolya/yolact/blob/530415ff8a3f8f97b8deb58508ea74c84ea147b2/layers/modules/multibox_loss.py#L196

**Comment by sainatarajan** [comment]
I think it refers to Instance Segmentation discriminative loss.

**Comment by amaanda** [comment]
thanks!

**Comment by artes14** [comment]
`# Mask IoU Loss
        if cfg.use_maskiou and maskiou_targets is not None:
            losses['I'] = self.mask_iou_loss(net, maskiou_targets)`

in layers>modules>multibox_loss.py says it's mask IoU Loss
