### ISSUE TITLE
size mismatch for maskiou_net.maskiou_net.10.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([9]

### ISSUE THREAD

**Issue by carlsummer** [dbolya/yolact#492]
(yolact) [deploy@localhost yolact]$ python train.py  --config=yolact_coco_custom_config --resume=weights/yolact_plus_resnet50_54_800000.pth
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Resuming training, loading weights/yolact_plus_resnet50_54_800000.pth...
Traceback (most recent call last):
  File "train.py", line 504, in <module>
    train()
  File "train.py", line 207, in train
    yolact_net.load_weights(args.resume)
  File "/home/deploy/study-workspace/yolact/yolact/yolact.py", line 490, in load_weights
    self.load_state_dict(state_dict)
  File "/home/deploy/anaconda3/envs/yolact/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Yolact:
        size mismatch for maskiou_net.maskiou_net.10.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([9]).
        size mismatch for maskiou_net.maskiou_net.10.weight: copying a param with shape torch.Size([80, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([9, 128, 1, 1]).
        size mismatch for prediction_layers.0.conf_layer.weight: copying a param with shape torch.Size([729, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([90, 256, 3, 3]).
        size mismatch for prediction_layers.0.conf_layer.bias: copying a param with shape torch.Size([729]) from checkpoint, the shape in current model is torch.Size([90]).
        size mismatch for semantic_seg_conv.weight: copying a param with shape torch.Size([80, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([9, 256, 1, 1]).
        size mismatch for semantic_seg_conv.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([9]).
(yolact) [deploy@localhost yolact]$

**Comment by DEncounter** [comment]
I encountered the same problem, have you solved your problem？

**Comment by carlsummer** [comment]
solved

**Comment by carlsummer** [comment]
config file nc

**Comment by NTS-wen** [comment]
?

**Comment by cGeiger2** [comment]
Hi @carlsummer , could you explain how you solved this issue? Thank you very much!
