### ISSUE TITLE
How to change the color of masks ?

### ISSUE THREAD

**Issue by eastplainzhang** [dbolya/yolact#499]
Excuse me, this is a novice question. There is only one class in my project. When I eval on image, different instances in this class will have masks of different color. However, when  I eval video, the masks of different instances of the same class are of the same color. How to make different instances have different color masks when evaling video.
Thanks !

**Comment by eastplainzhang** [comment]
OK, I've found a method and got the right results.
In eval.py 👍 
In line 139
def prep_display(dets_out, img, h, w, undo_transform=True, class_color=False, mask_alpha=0.45, fps_str=''):
and line 716
return prep_display(preds, frame, None, None, undo_transform=False, class_color=True, fps_str=fps_str)
Set class_color to False

Hope this method can help people who have the same problem.

**Comment by wangshuo2020** [comment]
> OK, I've found a method and got the right results.
> In eval.py 👍
> In line 139
> def prep_display(dets_out, img, h, w, undo_transform=True, class_color=False, mask_alpha=0.45, fps_str=''):
> and line 716
> return prep_display(preds, frame, None, None, undo_transform=False, class_color=True, fps_str=fps_str)
> Set class_color to False
> 
> Hope this method can help people who have the same problem.
~~~
Do you know how to specify the color of the mask? What should I do if I want to specify the color of the mask as black?In other words, the instance becomes black after processing.

**Comment by wangshuo2020** [comment]
> OK, I've found a method and got the right results.
> In eval.py 👍
> In line 139
> def prep_display(dets_out, img, h, w, undo_transform=True, class_color=False, mask_alpha=0.45, fps_str=''):
> and line 716
> return prep_display(preds, frame, None, None, undo_transform=False, class_color=True, fps_str=fps_str)
> Set class_color to False
> 
> Hope this method can help people who have the same problem.

Do you know how to specify the color of the mask? What should I do if I want to specify the color of the mask as black?In other words, the instance becomes black after processing.
