### ISSUE TITLE
missing in close object (while small objects still can detect)

### ISSUE THREAD

**Issue by jinfagang** [dbolya/yolact#5]
Here is a result :

![image](https://user-images.githubusercontent.com/21303438/55777453-8c00b780-5ad2-11e9-8e94-387838fca608.png)

in a video sequence, the close object always miss detect, while the behind smaller object can segment out... but models trained on yolov3 detection only, can predict very precisely on this video..
what could be the reason

**Comment by jinfagang** [comment]
![image](https://user-images.githubusercontent.com/21303438/55777581-e437b980-5ad2-11e9-80af-4edf65c17c34.png)

**Comment by jinfagang** [comment]
the person bigger were missed while the bag still can segment out.....

**Comment by dbolya** [comment]
The default top_k is set to 5, so it will just show the 5 highest detections. Add the command-line arguments
```
--top_k=20 --score_threshold=0.25
```
or something of that nature.

We are also currently working on improving the confidence scores so that better masks will receive higher scores similar to msrcnn.

**Comment by jinfagang** [comment]
@dbolya Thank u for your information!
