### ISSUE TITLE
Incorrect check for "target.shape" in coco.py when running custom dataset

### ISSUE THREAD

**Issue by rileypsmith** [dbolya/yolact#508]
**Steps to Reproduce**
1. Create Coco-style JSON file for custom dataset with blank annotations (i.e. no ground truth). For example: `{"images":[{some image here}], "annotations":[]}`
2. Register dataset in ./data/config.py in the style of coco2017_testdev_dataset per [this comment](https://github.com/dbolya/yolact/issues/230#issuecomment-560542964) by @dbolya . For example:
```
    sample_dataset = dataset_base.copy({
        'name': 'Sample Dataset',
        'valid_images': './data/<img_folder>',
        'valid_info': './data/<dataset_json_file>'
        'has_gt': False,
        'label_map': COCO_LABEL_MAP
    })
```
3. Evaluate YOLACT on sample dataset and output Coco JSON file:
```
python eval.py --trained_model=weights/yolact_base_54_800000.pth --output_coco_json --dataset=sample_dataset
```

**Current Behavior**
YOLACT throws an error in ./data/coco.py:

**Expected Behavior**
YOLACT should run on the custom dataset and produce a JSON file with its annotations (predictions) for masks and bounding boxes.

**Relevant Logs**
The error YOLACT is producing:
```
Traceback (most recent call last):
  File "eval.py", line 1105, in <module>
    evaluate(net, dataset)
  File "eval.py", line 936, in evaluate
    img, gt, gt_masks, h, w, num_crowd = dataset.pull_item(image_idx)
  File "/home/rpsmith/2020/Video_Compression/yolact/data/coco.py", line 172, in pull_item
    if target.shape[0] == 0:
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Other Comment**
I managed to debug this code for my own use. It seems that in yolact/data/coco.py since `self.has_gt=False` we are setting `target=[]` in line 117. It also seems by default that `self.transform` is not None, but since `len(target)==0` this directs us to line 170 which sets `target=None`. The error then comes in line 172 from calling `target.shape` when target is in fact `None`. I fixed this by adding one line just ahead of line 172 to check `if target is not None:`. In other words, the fix that worked for me was to rewrite lines 172-174 as the following:
```
    if target is not None:
        if target.shape[0] == 0:
            print('Warning: Augmentation output an example with no ground truth. Resampling...')
            return self.pull_item(random.randint(0, len(self.ids)-1))
```

**Reported By**
rileypsmith

**Comment by downhiller** [comment]
I discovered exactly the same thing yesterday, and after much hair-pulling and googling and reading through the script opted just to comment those 3 lines out.

**Comment by downhiller** [comment]
dbolya is already aware, and said he'd issue a fix back in March.  Hopefully he'll take this as a friendly reminder rather than an annoying nag 😁

https://github.com/dbolya/yolact/issues/375

👍

**Comment by rileypsmith** [comment]
Glad to hear the issue is already noted. Don't mean to nag, just wanted to mention this in case it had not been caught yet! I'll close the issue, thanks!

**Comment by jtsilverio** [comment]
For anyone intersted, this issue was apparently not yet fixed on the main branch. I am still getting 'NoneType' object has no attribute 'shape'' when trying to generate a json file from a custom test dataset.
