### ISSUE TITLE
preserve_aspect_ratio question 

### ISSUE THREAD

**Issue by andyhahaha** [dbolya/yolact#51]
I am training on cityscapes, so I want to preserver the ratio.(1024, 2048)
However, after turn on preserve ratio, loss keep decrease but the visualization of bounding box position always wrong. 

And I find this line use max_size both at width and height. 
I think it should be b_w, b_h = (int(cfg.max_size / r_w * w), int(cfg.min_size / r_h * h)).
or directly b_w, b_h =w, h
I don't understand the comment # A hack to scale the bboxes to the right size
I wonder is this a bug or some trick?
https://github.com/dbolya/yolact/blob/5dd130db81ba73d0bf9b4fc3df263481a7639f11/layers/output_utils.py#L68

Thanks

**Comment by dbolya** [comment]
So currently `perseve_aspect_ratio` is not supported and I don't plan on supporting it in its current state (since I plan on completely rewriting it, and I plan v1.1 to preserve aspect ratio by default). I suggest just not using it for now. What it's doing right now is just padding everything to be square, which is actually worse than simply squishing everything.

**Comment by andyhahaha** [comment]
Thanks.
I am looking forward to v1.1. It is a nice work.
When will it release?

I also found another bug. Just share for somebody need perseve_aspect_ratio feature now.
https://github.com/dbolya/yolact/blob/5dd130db81ba73d0bf9b4fc3df263481a7639f11/layers/output_utils.py#L100
proto_data has shape (h, w, mask_dim), so it sure undo the padding as followL
masks = masks[:, :int(r_h/cfg.max_size*proto_data.size(0)), :int(r_w/cfg.max_size*proto_data.size(1))]

**Comment by dbolya** [comment]
Thanks for the fix!

I should hopefully be able to release v1.1 in the coming month. I wanted it to come out this month, but I'm finding less and less time to work on YOLACT.

I'll also leave this issue open until I implement preserve_aspect_ratio properly.

**Comment by shoutOutYangJie** [comment]
> So currently `perseve_aspect_ratio` is not supported and I don't intend to support it in its current state (since I plan on completely rewriting it; v1.1 will have preserve aspect ratio by default). I suggest just not using it for now. What it's doing right now is just padding everything to be square and then scaling down to 550x550, which is actually worse than simply squishing everything.

so when will you finish your v1.1 version?   you just give me a approximate date. thanks you.

**Comment by shoutOutYangJie** [comment]
> _Hahaha_ I might not be doing a small version update anymore since none of the things I tried worked out, and I'm not at UC Davis anymore. So I think it'll be a while till YOLACT gets a major update.

OK, i appreciate your works. Your work gives me a idea. I hope this idea can be a paper.

**Comment by dbolya** [comment]
This was fixed in v1.1 (it happened lol).
