### ISSUE TITLE
can not evaluate？

### ISSUE THREAD

**Issue by lifeiwen** [dbolya/yolact#52]
my evaluate environment is：
pytorch1.0.1 cuda9.0
but i have error
(torch1.0.1) lf@110:~/Semantic segmentation/yolact$ python eval.py --trained_model=weights/yolact_im700_54_800000.pth --score_threshold=0.3 --top_k=100 --image=my_image.jpg
Config not specified. Parsed yolact_im700_config from the file name.

Loading model... Done.
Traceback (most recent call last):
  File "eval.py", line 1020, in <module>
    evaluate(net, dataset)
  File "eval.py", line 797, in evaluate
    evalimage(net, args.image)
  File "eval.py", line 561, in evalimage
    frame = torch.from_numpy(cv2.imread(path)).cuda().float()
TypeError: expected np.ndarray (got NoneType)

**Comment by dbolya** [comment]
That means the image could not be loaded correctly. Verify that the path is correct. In your case there should be `my_image.jpg` in the same directory as `eval.py`.

**Comment by lifeiwen** [comment]
thanks i forget the path @dbolya
