### ISSUE TITLE
mAP bigger than 1?

### ISSUE THREAD

**Issue by cijiezheng** [dbolya/yolact#526]
![Screen Shot 2020-09-14 at 8 46 22 PM](https://user-images.githubusercontent.com/26666431/93090186-f60d8b00-f6ce-11ea-8916-61ffced06a43.png)
why in my custom train, the mAP > 1?

**Comment by cijiezheng** [comment]
Computing validation mAP (this may take a while)...


Calculating mAP...

       |  all  |  .50  |  .55  |  .60  |  .65  |  .70  |  .75  |  .80  |  .85  |  .90  |  .95  |
-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
   box |  1.72 |  4.05 |  3.58 |  3.08 |  2.50 |  1.91 |  1.25 |  0.59 |  0.15 |  0.04 |  0.00 |
  mask |  1.63 |  3.65 |  3.16 |  2.75 |  2.32 |  1.88 |  1.25 |  0.92 |  0.32 |  0.04 |  0.00 |
-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+

**Comment by suchiz** [comment]
It is in %. So your model is bad for the moment.

**Comment by cijiezheng** [comment]
> It is in %. So your model is bad for the moment.

thanks！
