### ISSUE TITLE
YOLACT/YOLACT++

### ISSUE THREAD

**Issue by swhan0329** [dbolya/yolact#547]
I appreciate your amazing research.
I have one question.

How can I distinguish the YOLACT, the YOLACT++ version when I download and run the code?
If I want to run the YOLACT model, what should I do from this repository?
Also if I want to run the YOLACT++ model, should I just run the current version?

If you know anything, please let me know.
Thank you, again.

**Comment by suchiz** [comment]
It is all based on the config you use. You can change it using the flag --config= . And see the details in data/config.py

**Comment by swhan0329** [comment]
@suchiz 
Thank you for your rely 👍
