### ISSUE TITLE
when run eval.py on other dataset:  IndexError: list index out of range

### ISSUE THREAD

**Issue by yingjunshi** [dbolya/yolact#552]
Traceback (most recent call last):
  File "/home/data/text_detect/yolact_project/yolact/eval.py", line 1118, in <module>
    evaluate(net, dataset)
  File "/home/data/text_detect/yolact_project/yolact/eval.py", line 958, in evaluate
    prep_metrics(ap_data, preds, img, gt, gt_masks, h, w, num_crowd, dataset.ids[image_idx], detections)
  File "/home/data/text_detect/yolact_project/yolact/eval.py", line 470, in prep_metrics
    ap_obj = ap_data[iou_type][iouIdx][_class]
IndexError: list index out of range

it's because the category_id begin with 1. for dataset with three categories,the third dimension of ap_data has three(from 0 to 2included) .but  _class is in [0,1,2,3,].
for _class in set(classes + gt_classes):     eval.py
gt_classes has zero (the transform during dataload made category_id 0  into 0.28)

**Comment by vahidaidrivers** [comment]
I faced this error 
    ap_obj = ap_data[iou_type][iouIdx][_class]
IndexError: list index out of range

However,  the category_id and class_id begin with 1. 
"categories": [
        {
            "supercategory": null,
            "id": 1,
            "name": "helmet"
        },
        {
            "supercategory": null,
            "id": 2,
            "name": "no_helmet"
        }, 

Could you advise?

**Comment by VbsmRobotic** [comment]
I have faced the same error 
ap_obj = ap_data[iou_type][iouIdx][_class]
IndexError: list index out of range

however, the category_id and class_id begin with 1. 

"categories": [
        {
            "supercategory": null,
            "id": 1,
            "name": "helmet"
        },
        {
            "supercategory": null,
            "id": 2,
            "name": "no_helmet"
        },

Could you please advise?
