### ISSUE TITLE
About the "@" syntax used in code ?

### ISSUE THREAD

**Issue by gachiemchiep** [dbolya/yolact#559]
Hello @dbolya 
Thank you for your great contribution. 

Inside the source code, I found some places where you use the "@" syntax such as:

```bash
        cos_sim = coeffs_norm @ coeffs_norm.t()
        pred_masks = proto_masks @ proto_coef.t()
        intersection = masks_a @ masks_b.t()
        masks = proto_data @ masks.t()
```

Would you mind give me a quick explanation about this syntax?

**Comment by tlind** [comment]
The @ operator performs matrix multiplication, see https://www.python.org/dev/peps/pep-0465/

**Comment by gachiemchiep** [comment]
@tlind Thank you
