### ISSUE TITLE
the warning of inf

### ISSUE THREAD

**Issue by andeyeluguo** [dbolya/yolact#56]
when I try to finetune the model with the command:
"python ../../train.py --config=yolact_base_config --no_jit --resume=../../weights/yolact_base_54_800000.pth  --batch_size=32"

it shows the instructions:
"Warning: Moving average ignored a value of inf"

I think this is an error, because the inf value is here.

How did that happen?

**Comment by dbolya** [comment]
Is the loss still going down? There might be like 2-4 "inf" iterations in an epoch because of a bad detection in COCO or something going wrong with data augmentation. If the loss is still going down (or at least not exploding), then you can safely ignore those messages.

**Comment by andeyeluguo** [comment]
[  0]       0 || B: 1.490 | C: 1.823 | M: 2.191 | S: 0.236 | T: 5.741 || ETA: 0:00:00 || timer: 29.275
[  0]      10 || B: 1.347 | C: 1.971 | M: 2.307 | S: 0.451 | T: 6.076 || ETA: 15:08:58 || timer: 1.314
[  0]      20 || B: 1.385 | C: 1.966 | M: 2.366 | S: 0.454 | T: 6.171 || ETA: 14:43:59 || timer: 1.370
[  0]      30 || B: 1.401 | C: 1.959 | M: 2.389 | S: 0.433 | T: 6.184 || ETA: 14:36:31 || timer: 1.283
[  0]      40 || B: 1.423 | C: 2.002 | M: 2.413 | S: 0.440 | T: 6.278 || ETA: 14:29:37 || timer: 1.321
[  0]      50 || B: 1.416 | C: 1.981 | M: 2.415 | S: 0.425 | T: 6.237 || ETA: 14:27:20 || timer: 1.359
[  0]      60 || B: 1.449 | C: 1.997 | M: 2.464 | S: 0.417 | T: 6.327 || ETA: 14:25:43 || timer: 1.246
[  0]      70 || B: 1.460 | C: 1.990 | M: 2.480 | S: 0.404 | T: 6.335 || ETA: 14:25:12 || timer: 1.307
[  0]      80 || B: 1.475 | C: 2.007 | M: 2.492 | S: 0.405 | T: 6.379 || ETA: 14:26:20 || timer: 1.253
[  0]      90 || B: 1.472 | C: 2.004 | M: 2.487 | S: 0.410 | T: 6.373 || ETA: 14:22:49 || timer: 1.230
[  0]     100 || B: 1.476 | C: 2.008 | M: 2.492 | S: 0.408 | T: 6.383 || ETA: 14:21:18 || timer: 1.331
[  0]     110 || B: 1.502 | C: 2.021 | M: 2.527 | S: 0.399 | T: 6.448 || ETA: 14:21:41 || timer: 1.287



and then it becomes


[  3]   12330 || B: 1.631 | C: 2.266 | M: 2.637 | S: 0.415 | T: 6.949 || ETA: 9:33:54 || timer: 1.256
[  3]   12340 || B: 1.634 | C: 2.262 | M: 2.647 | S: 0.419 | T: 6.961 || ETA: 9:33:47 || timer: 1.183
[  3]   12350 || B: 1.613 | C: 2.251 | M: 2.614 | S: 0.420 | T: 6.899 || ETA: 9:33:39 || timer: 1.177
[  3]   12360 || B: 1.607 | C: 2.240 | M: 2.600 | S: 0.430 | T: 6.877 || ETA: 9:33:22 || timer: 1.287
[  3]   12370 || B: 1.606 | C: 2.233 | M: 2.609 | S: 0.436 | T: 6.884 || ETA: 9:33:19 || timer: 1.405
[  3]   12380 || B: 1.608 | C: 2.238 | M: 2.613 | S: 0.440 | T: 6.898 || ETA: 9:33:11 || timer: 1.213
[  3]   12390 || B: 1.616 | C: 2.234 | M: 2.605 | S: 0.437 | T: 6.892 || ETA: 9:33:05 || timer: 1.394
[  3]   12400 || B: 1.618 | C: 2.228 | M: 2.598 | S: 0.430 | T: 6.874 || ETA: 9:32:50 || timer: 1.211
Warning: Moving average ignored a value of inf
Warning: Moving average ignored a value of inf
[  3]   12410 || B: 1.619 | C: 2.235 | M: 2.603 | S: 0.430 | T: 6.887 || ETA: 9:32:44 || timer: 1.211
[  3]   12420 || B: 1.614 | C: 2.230 | M: 2.598 | S: 0.434 | T: 6.875 || ETA: 9:32:28 || timer: 1.187



it seems that the loss increases?

**Comment by dbolya** [comment]
Nope, that's fine. Loss will naturally fluctuate because of data augmentation and harder / easier training examples (especially when you're fine-tuning from an already fully trained model).

If the loss blows up to infinity, you will know because the training will just crash, but what you see there is just data augmentation spitting out a bad training example or something similar.

**Comment by andeyeluguo** [comment]
when I want to debug the code 
I write a command "pdb..set_trace()"
int the 165 line of the file  augmentations.py
it raises the error



> /home/zhaodz/algorithm/yolact/utils/augmentations.py(168)__call__()
-> if self.resize_gt:
(Pdb)
Traceback (most recent call last):
  File "../../train.py", line 374, in <module>
    train()
  File "../../train.py", line 211, in train
    for datum in data_loader:
  File "/home/zhaodz/program/anaconda3/envs/AutoDeepLab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/zhaodz/program/anaconda3/envs/AutoDeepLab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
bdb.BdbQuit: Traceback (most recent call last):

Does it because the more one worker is working ?

**Comment by dbolya** [comment]
Yeah you're not going to be able to do any standard exception handling and callback stuff without upsetting the multiprocessing. Either set `--num_workers=0` or use some other method of debugging (such as `code.interact`).

**Comment by lcf000000** [comment]
I met the same warning, nan and inf warning.  but Loss has been exploding. When I turn off the data augmentation option, everything is fine. How can I solve this problem? Or have any ideas for troubleshooting

`[  0]    7860 || B: 20381994142686931931996316762112.000 | C: 1450343373374326503135973998592.000 | M: 1831.892 | S: 401324281.028 | T: 21832337516061260686932104445952.000 || ETA: 20:27:56 || timer: 0.341
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
[  0]    7870 || B: 20381994142686931931996316762112.000 | C: 1450343373374326503135973998592.000 | M: 1720.711 | S: 401324281.028 | T: 21832337516061260686932104445952.000 || ETA: 20:24:34 || timer: 0.367
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
[  0]    7880 || B: 20381994142686931931996316762112.000 | C: 1450343373374326503135973998592.000 | M: 1795.391 | S: 401324281.028 | T: 21832337516061260686932104445952.000 || ETA: 20:26:03 || timer: 0.339
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
[  0]    7890 || B: 20381994142686931931996316762112.000 | C: 1450343373374326503135973998592.000 | M: 1785.494 | S: 401324281.028 | T: 21832337516061260686932104445952.000 || ETA: 20:23:17 || timer: 0.340
`

**Comment by dbolya** [comment]
@lcf000000 Have you tried the troubleshooting steps in #42? I remember you have a batch size of 4 but you're using 3 GPUs. I recommend to always have the batch size a multiple of the number of GPUs. Then, probably most importantly l, your batch size is 4 which is too small for batch norm so follow the steps in #42 to freeze batch norm (remind me if those instructions aren't in that thread)
