### ISSUE TITLE
Aspect Ratio

### ISSUE THREAD

**Issue by Ruwen14** [dbolya/yolact#563]
Hi,

does Yolact handles different aspect ratio in the training data(In my case 16:9)?

If not, do i have to resize my data and label it from scratch or does yolact also scale the annotations accordingly ?

thanks in advance

**Comment by areebsyed** [comment]
@Ruwen14 you dont have to resize. Yolact does everything itself.

**Comment by Ruwen14** [comment]
Thanks!
