### ISSUE TITLE
About the experiment results

### ISSUE THREAD

**Issue by guantinglin** [dbolya/yolact#57]
Hi, 
Just a short question.
Is the "mAP" reported the box ap or mask ap?

**Comment by guantinglin** [comment]
and how to get box ap and mask ap at the same time?

**Comment by dbolya** [comment]
The mAP reported on the Github readme and in the paper are mask mAP. However, all my scripts output both at once so all you need to do is run an eval command; e.g.,
```python eval.py --trained_model=weights/yolact_base_54_800000.pth```
After it finishes it'll print something like this:
```
       |  all  |  .50  |  .55  |  .60  |  .65  |  .70  |  .75  |  .80  |  .85  |  .90  |  .95  |
-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
   box | 32.54 | 53.04 | 50.75 | 47.78 | 44.29 | 40.24 | 34.68 | 27.60 | 18.27 |  7.90 |  0.84 |
  mask | 29.83 | 48.30 | 45.91 | 43.19 | 39.85 | 35.83 | 31.31 | 25.32 | 17.91 |  9.07 |  1.59 |
-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
```
where the `all` column specifies the standard COCO mAP, and the rest specify the AP for each IoU threshold.

**Comment by guantinglin** [comment]
Okay, thanks for your detailed answer:)

**Comment by harrybolingot** [comment]
> The mAP reported on the Github readme and in the paper are mask mAP. However, all my scripts output both at once so all you need to do is run an eval command; e.g.,
> `python eval.py --trained_model=weights/yolact_base_54_800000.pth`
> After it finishes it'll print something like this:
> 
> ```
>        |  all  |  .50  |  .55  |  .60  |  .65  |  .70  |  .75  |  .80  |  .85  |  .90  |  .95  |
> -------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
>    box | 32.54 | 53.04 | 50.75 | 47.78 | 44.29 | 40.24 | 34.68 | 27.60 | 18.27 |  7.90 |  0.84 |
>   mask | 29.83 | 48.30 | 45.91 | 43.19 | 39.85 | 35.83 | 31.31 | 25.32 | 17.91 |  9.07 |  1.59 |
> -------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
> ```
> 
> where the `all` column specifies the standard COCO mAP, and the rest specify the AP for each IoU threshold.

Is there a way to calculate the overall IoU of all classes for all images in a separate test/predict dataset?

**Comment by dbolya** [comment]
@harrybolingot Since that seems very specific for your use case, you'll have to implement that yourself. Computing just IoU shouldn't be too hard though. You can look at `prep_metrics` in `eval.py` for reference.
