### ISSUE TITLE
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

### ISSUE THREAD

**Issue by qingweihk** [dbolya/yolact#589]
when use yolact++,there is an error:
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

any help?thanks

**Comment by sdimantsd** [comment]
what command do you used?
what PC?

**Comment by qingweihk** [comment]
> what command do you used?
> what PC?

Thanks:
The command  that I use are as following the readme:
cd external/DCNv2
python setup.py build develop

And I run the code on google colab virtual environment.

**Comment by sdimantsd** [comment]
I don't think it will work on google colab.
This error mean nvcc file is missing. this file is part of NVIDIA cuda so you need a NVIDIA GPU for it. 
Did google colab have it?

**Comment by qingweihk** [comment]
> I don't think it will work on google colab.
> This error mean nvcc file is missing. this file is part of NVIDIA cuda so you need a NVIDIA GPU for it.
> Did google colab have it?

Yes. Thanks, I have figure out it by switch torch1.7 to torch1.5.1.
