### ISSUE TITLE
Bug in eval.py

### ISSUE THREAD

**Issue by txytju** [dbolya/yolact#6]
Is this line a bug? why is there a data type in function defination?
https://github.com/dbolya/yolact/blob/dev/eval.py#L244

**Comment by dbolya** [comment]
Those are Python3 type annotations ([https://docs.python.org/3/library/typing.html](https://docs.python.org/3/library/typing.html)) introduced in python 3.5.

I use them time to time to tell my IDE what types things are for auto-completion. See this comment:
https://github.com/dbolya/yolact/blob/dev/eval.py#L441
