### ISSUE TITLE
dataset file

### ISSUE THREAD

**Issue by GittersYang** [dbolya/yolact#60]
![2019-06-10 19-35-20屏幕截图](https://user-images.githubusercontent.com/44436506/59193205-7fbed680-8bb7-11e9-8251-f19e48180fc9.png)
![2019-06-10 19-35-33屏幕截图](https://user-images.githubusercontent.com/44436506/59193207-80576d00-8bb7-11e9-94be-09c6892057dc.png)

**Is this a dataset file pair? Why is it wrong: it can't find the image file**

**Comment by dbolya** [comment]
Hmm did you use the included script to download the dataset or did you download it yourself?

Regardless, you can probably fix this by moving the contents of each test2017, train2017, and val2017 folders into their parent folder (images). That's what the script does.

**Comment by GittersYang** [comment]
ok， I have solved this problem. But,when I am running this command"python eval.py --trained_model=weights/yolact_base_54_800000.pth --score_threshold=0.3 --top_k=100 --display", I have a bug：
![无标题](https://user-images.githubusercontent.com/44436506/59237886-7755b280-8c2e-11e9-968e-d19aeca470fb.png)


Thank you for your reply

**Comment by dbolya** [comment]
Oh whoops, it looks like I made a typo. Pull the latest commit and that should be fixed.

**Comment by GittersYang** [comment]
oh my friends,Your suggestion is valid.
what's more, if someone meet the issue of  the qt's version , you can upgrade it by"conda upgrade qt".

thanks
