### ISSUE TITLE
Calculate mAP on custom dataset

### ISSUE THREAD

**Issue by AdamGoris** [dbolya/yolact#615]
I have my own custom dataset that I wish to calculate mAP and f1 score for. How can I achieve this?
i.e. have ground truth annotations and AI output annotations as input, and mAP as output.

**Comment by oulfik** [comment]
Do you mean to validate your image output (boxes & masks)? I think you can achieve that with this toolbox: [Link](https://github.com/rafaelpadilla/review_object_detection_metrics#metrics). I haven't tried it yet but I can give you some feedback once I have.
