### ISSUE TITLE
Training Humans

### ISSUE THREAD

**Issue by Tomhouxin** [dbolya/yolact#62]
I know this can only train humans, but would it be unfriendly to the network, after all, there is no need to classify

**Comment by dbolya** [comment]
¯\_(ツ)_/¯

It would probably do even better than when training on the entirety of COCO, since it can use all 32 prototypes for just people.

**Comment by Tomhouxin** [comment]
Thank you very much for your reply. It is true in theory, but the model can still be large

**Comment by dbolya** [comment]
We do a looot of data augmentation so I think as long as you have enough training data (e.g., COCO but only humans) I think it'd be fine. Give it a shot.

**Comment by dbolya** [comment]
Since this has been open so long, I'm going to close it. Feel free to reopen if you have any updates.

**Comment by areebsyed** [comment]
HI I want to detect persons only. With everything remaining the same what should I do to nullify all the other classes from being detected but persons only. I understand I wouldnt have to make a custom config for this. I tried to change yolact/layers/output_utils.py but it gives out error when theres a frame with no person.
