### ISSUE TITLE
How to add optimized anchors?

### ISSUE THREAD

**Issue by jcarlosangelesc** [dbolya/yolact#624]
First of all, thanks for the amazing work!

I would like to optimize the anchors for my specific dataset. I used the code in [https://github.com/martinzlocha/anchor-optimization](https://github.com/martinzlocha/anchor-optimization) to generate the new set of scales and aspect ratios and got the following results:

Ratios: [0.267, 0.555, 1.0, 1.803, 3.746]
Scales: [0.548, 0.777, 0.983, 1.227, 1.385, 1.747]

I would like to update`'pred_scales'` and `'pred_aspect_ratios'` in `config.py` to my new values but I don't fully understand how to put them properly. I checked the other backbone configurations as example but I still don't get it. Can someone explain what's the format of these parameters, please?

Sorry if this is a trivial question, I'm relatively new to this topic. Thanks in advance.

**Comment by Theangelkk** [comment]
Hello jcarlosangelesc , 
Did you manage to optimize the anchors on your custom dataset, updating the parameters "pred_scales" and "pred_aspect_ratios"??

Thanks in advance.
