### ISSUE TITLE
Config file for yolact_im700_54_800000.pth

### ISSUE THREAD

**Issue by piseabhijeet** [dbolya/yolact#637]
Hi @dbolya 

Where can i get the config file for the pre-trained model **_yolact_im700_54_800000.pth_** ?

I want to use this model for transfer learning.

Thanks

**Comment by surgavur** [comment]
Hello, I just used that model myself and maybe I can answer that: in data/config.py, line 715

**Comment by piseabhijeet** [comment]
Hi @surgavur 

Thank you for the comment. It helps :)
