### ISSUE TITLE
YOLACT and cuda 10.1

### ISSUE THREAD

**Issue by sdimantsd** [dbolya/yolact#66]
Hi, thanks for you'r amazing work!
When i tray to evaluate i get the following error:
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or director

libcudart.so.10.0 is realy missing becuse libcudart.so.10.**1** is installed.
Can i run yolact with cuda 10.1?

thx

**Comment by dbolya** [comment]
That sounds like a CUDA / Pytorch installation problem, not a YOLACT problem. Maybe [this thread](https://github.com/rusty1s/pytorch_geometric/issues/114) would be helpful?

You probably have to install a different version of Pytorch or install CUDA 10.0 instead.

**Comment by sdimantsd** [comment]
Thank!!!
I forgot install torchvision :-\

**Comment by sdimantsd** [comment]
Thanks!
