### ISSUE TITLE
Assigning two classes into one classs with label map

### ISSUE THREAD

**Issue by ProVival** [dbolya/yolact#665]
Hi i created a dataset to train yolact and i have 
`
'class_names': ('right', 'left', 'straight', 'vertical')`
what i need to do is i want to combine right and left classes, so it will be something like:
`'class_names': ('right_and_left', 'straight', 'vertical')`
is there any way to do this with by using label_map ? I cannot create the coco_annotations.json from scratch because it takes like 10+ hours. Thanks so much

**Comment by RhysMcK** [comment]
Did you find a solution to this?

**Comment by ProVival** [comment]
> Did you find a solution to this?

I did but i can't remember now :/ i think it was something like using same number for two classes on label map?
