### ISSUE TITLE
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'

### ISSUE THREAD

**Issue by menkeyi** [dbolya/yolact#676]
(yolact-env) root@ai:~/yolact# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:17_PST_2019
Cuda compilation tools, release 10.1, V10.1.105

1、conda env create -f environment.yml
2、sh data/scripts/COCO_test.sh     
3、sh data/scripts/COCO.sh

4、’download:
       resnet101_reducedfc.pth

(yolact-env) root@ai:~/yolact# python train.py --config=yolact_base_config
loading annotations into memory...
Done (t=16.68s)
creating index...
index created!
loading annotations into memory...
Done (t=2.17s)
creating index...
index created!
/root/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/jit/_recursive.py:222: UserWarning: 'lat_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
/root/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/jit/_recursive.py:222: UserWarning: 'pred_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
/root/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/jit/_recursive.py:222: UserWarning: 'downsample_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
Initializing weights...
/root/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448265233/work/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Begin training!

Traceback (most recent call last):
  File "train.py", line 504, in <module>
    train()
  File "train.py", line 270, in train
    for datum in data_loader:
  File "/root/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/root/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/root/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 944, in __init__
    self._reset(loader, first_iter=True)
  File "/root/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 975, in _reset
    self._try_put_index()
  File "/root/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1209, in _try_put_index
    index = self._next_index()
  File "/root/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 512, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/root/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 226, in __iter__
    for idx in self.sampler:
  File "/root/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 124, in __iter__
    yield from torch.randperm(n, generator=generator).tolist()
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'

Do I need to change the configuration in environment.yml?

**Comment by menkeyi** [comment]
resolved

**Comment by Kracozebr** [comment]
The same issue while trying training in google colab. How did you resolved that?

**Comment by dky123456** [comment]
The same issue while trying training in my own dataset. How did you resolved that?

**Comment by Kracozebr** [comment]
Not yet. I think it's smth with dataset annotations/config file. What I've done I dowlnload a small part of coco dataset (several classes and about 100 images for training and 20 for validating) and tried to train. And it works.  So try to understand config file and to check annotation format

**Comment by AdvancedStyle** [comment]
I'm having the same issue, did anyone solve it?
