### ISSUE TITLE
Error in masks = masks.reshape(-1, height, width)

### ISSUE THREAD

**Issue by felipetobars** [dbolya/yolact#687]
Hi, I previously trained a dataset where the images were not all the same size, they all ranged from 950 to 1000 in both height and width and I had no problem. Now I am using images with larger sizes (between 1000 and 1200 both in height and width) and it is showing me a problem with the reshaping of the masks. I've already spent quite a bit of time on labeling so it would be helpful to know if anyone knows if there is any way to fix it without having to change the dataset. The error is as follows:

Resuming training, loading weights/yolact_im700_54_800000.pth...
Ignoring "Error(s) in loading state_dict for Yolact:
	size mismatch for prediction_layers.0.conf_layer.weight: copying a param with shape torch.Size([243, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([33, 256, 3, 3]).
	size mismatch for prediction_layers.0.conf_layer.bias: copying a param with shape torch.Size([243]) from checkpoint, the shape in current model is torch.Size([33]).
	size mismatch for semantic_seg_conv.weight: copying a param with shape torch.Size([80, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([10, 256, 1, 1]).
	size mismatch for semantic_seg_conv.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([10])."
Begin training!

Traceback (most recent call last):
  File "train.py", line 504, in <module>
    train()
  File "train.py", line 270, in train
    for datum in data_loader:
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/yolact/data/coco.py", line 94, in __getitem__
    im, gt, masks, h, w, num_crowds = self.pull_item(index)
  File "/root/yolact/data/coco.py", line 150, in pull_item
    masks = masks.reshape(-1, height, width)
ValueError: cannot reshape array of size 9138360 into shape (841,866)

**Comment by MHasanlou1** [comment]
> Hi, I previously trained a dataset where the images were not all the same size, they all ranged from 950 to 1000 in both height and width and I had no problem. Now I am using images with larger sizes (between 1000 and 1200 both in height and width) and it is showing me a problem with the reshaping of the masks. I've already spent quite a bit of time on labeling so it would be helpful to know if anyone knows if there is any way to fix it without having to change the dataset. The error is as follows:
> 
> Resuming training, loading weights/yolact_im700_54_800000.pth... Ignoring "Error(s) in loading state_dict for Yolact: size mismatch for prediction_layers.0.conf_layer.weight: copying a param with shape torch.Size([243, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([33, 256, 3, 3]). size mismatch for prediction_layers.0.conf_layer.bias: copying a param with shape torch.Size([243]) from checkpoint, the shape in current model is torch.Size([33]). size mismatch for semantic_seg_conv.weight: copying a param with shape torch.Size([80, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([10, 256, 1, 1]). size mismatch for semantic_seg_conv.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([10])." Begin training!
> 
> Traceback (most recent call last): File "train.py", line 504, in train() File "train.py", line 270, in train for datum in data_loader: File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 435, in **next** data = self._next_data() File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 475, in _next_data data = self._dataset_fetcher.fetch(index) # may raise StopIteration File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/root/yolact/data/coco.py", line 94, in **getitem** im, gt, masks, h, w, num_crowds = self.pull_item(index) File "/root/yolact/data/coco.py", line 150, in pull_item masks = masks.reshape(-1, height, width) ValueError: cannot reshape array of size 9138360 into shape (841,866)

I have same poroblem. did you solve it?

**Comment by felipetobars** [comment]
@MHasanlou1  I found out that the problem came from the COCO JSON files with the annotations. I made the skins using VGG Image Annotation and noticed that the COCO JSON format you export the annotations in is not correct. The image_id saves them as text and they must be integers, in addition, the points of the masks must be saved as a list of lists. You can check your JSON files to verify that they are in the correct format (I leave a picture of how the annotations are with the segmentation).

![image](https://user-images.githubusercontent.com/55366335/145114706-5cb53964-8a15-4622-aa49-f93c99ee02c7.png)

**Comment by nesi73** [comment]
I have the same problem but my JSON files are in the correct format
