### ISSUE TITLE
AttributeError: 'str' object has no attribute 'grad_fn'

### ISSUE THREAD

**Issue by SampleXi** [dbolya/yolact#69]
when i try to create visualizations of PyTorch execution graphs and traces,I met this issue.
`from graphviz import Digraph
import torch
from torch.autograd import Variable

```
def make_dot(vars, params = None):
    """ Produces Graphviz representation of PyTorch autograd graph
    Blue nodes are the Variables that require grad, orange are Tensors
    saved for backward in torch.autograd.Function
    Args:
        var: output Variable
        params: dict of (name, Variable) to add names to node that
            require grad (TODO: make optional)
    """
    if params is not None:
        assert isinstance(params.values()[0], Variable)
        param_map = {id(v): k for k, v in params.items()}

    node_attr = dict(style='filled',
                     shape='box',
                     align='left',
                     fontsize='12',
                     ranksep='0.1',
                     height='0.2')
    dot = Digraph(node_attr=node_attr, graph_attr=dict(size="12,12"))
    seen = set()

    def size_to_str(size):
        return '('+(', ').join(['%d' % v for v in size])+')'

    def add_nodes(var):
        if var not in seen:
            if torch.is_tensor(var):
                dot.node(str(id(var)), size_to_str(var.size()), fillcolor='orange')
            elif hasattr(var, 'variable'):
                u = var.variable
                name = param_map[id(u)] if params is not None else ''
                node_name = '%s\n %s' % (name, size_to_str(u.size()))
                dot.node(str(id(var)), node_name, fillcolor='lightblue')
            else:
                dot.node(str(id(var)), str(type(var).__name__))
            seen.add(var)
            if hasattr(var, 'next_functions'):
                for u in var.next_functions:
                    if u[0] is not None:
                        dot.edge(str(id(u[0])), str(id(var)))
                        add_nodes(u[0])
            if hasattr(var, 'saved_tensors'):
                for t in var.saved_tensors:
                    dot.edge(str(id(t)), str(id(var)))
                    add_nodes(t)
    for var in vars:
        add_nodes(var.grad_fn)
    return dot

from torch.autograd import Variable
from yolact import Yolact

if __name__ == '__main__':
    from datetime import datetime
    t0 = datetime.now()
    x = Variable(torch.ones(1,3,550,550))
    model = Yolact()
    output0 = model(x)
    t1 = datetime.now()
    print('taking {} secondes'.format(t1 - t0))
    g = make_dot((output0))
    g.view()`
```
`Traceback (most recent call last):
  File "D:/interest/yolact/Net_visiable.py", line 71, in <module>
    g = make_dot((output0))
  File "D:/interest/yolact/Net_visiable.py", line 53, in make_dot
    add_nodes(var.grad_fn)
AttributeError: 'str' object has no attribute 'grad_fn'`

How to solve this problem?

**Comment by dbolya** [comment]
This is not the place to ask for help debugging somebody else's code.

Nevertheless, the error message points to
```
for var in vars:
    add_nodes(var.grad_fn)
```
and says that `var` doesn't have a `grad_fn`. If you check why that is, you'd notice that `vars` (the output of `Yolact`) is a dictionary and not a tuple or list as the loop expects (when `vars` is a dictionary this loops over the keys and not the values). Thus, to fix it you should loop over the values by changing the loop to
```
for var in vars.values():
    add_nodes(var.grad_fn)
```

**Comment by SampleXi** [comment]
> This is not the place to ask for help debugging somebody else's code.
> 
> Nevertheless, the error message points to
> 
> ```
> for var in vars:
>     add_nodes(var.grad_fn)
> ```
> 
> and says that `var` doesn't have a `grad_fn`. If you check why that is, you'd notice that `vars` (the output of `Yolact`) is a dictionary and not a tuple or list as the loop expects (when `vars` is a dictionary this loops over the keys and not the values). Thus, to fix it you should loop over the values by changing the loop to
> 
> ```
> for var in vars.values():
>     add_nodes(var.grad_fn)
> ```

Thank you very much,I am sorry to ask about this question there, but I didn't find a button to remove this issue, could you please help to remove it.

**Comment by dbolya** [comment]
It's fine, I can just close it. I'll keep this up because it might help somebody in the future.
