### ISSUE TITLE
Training with custom data

### ISSUE THREAD

**Issue by Amit12690** [dbolya/yolact#70]
I have few images where I have to segment  2 kinds of flowers . I wish to achieve it using Yoloact. However  I am very confused with how to prepare my dataset suitable for training . Can anyone please help me with the following : 

- Any annotation tool for labelling and getting the annotations in coco format 

- How to proceed once I have the annotated data ? 

Sorry if this is a very basic question . I have just started looking in to instance segmentation , so confused

**Comment by dbolya** [comment]
I'm not very familiar with preparing instance segmentation data as I've just been using COCO this whole time, but I've heard good things about [LabelMe](http://labelme.csail.mit.edu/Release3.0/). Once you have the LabelMe annotations then you can use [labelme2coco](https://github.com/wkentaro/labelme/blob/master/examples/instance_segmentation/labelme2coco.py) to convert it to coco annotations and then proceed with the custom dataset instructions in my readme.

I haven't use either of those tools though--I've just heard about others using them.

**Comment by Amit12690** [comment]
Thanks a lot @dbolya . I will try labelme.

**Comment by abhigoku10** [comment]
@Amit12690  as dbolya suggested , you can use that it will work since i have used the same approach for annotation and training

**Comment by Amit12690** [comment]
@abhigoku10 @dbolya  Thanks for the advice. Labelme is so easy to use. I am trying it on a sample dataset. Will update once I get training to work

**Comment by Amit12690** [comment]
@dbolya @abhigoku10  I think my training has made progress , thanks a lot for your valuable suggestions. Labelme  and  labelme2coco.py work perfectly to create the dataset. For anyone who is planning to finetune/train the model on a custom dataset , please follow following steps : 

- Download and install Labelme (https://github.com/wkentaro/labelme)
- Label using polygon labelling option provided (The repo has nice tutorials)
- A json file will be created for each image labelled

**Comment by abhigoku10** [comment]
@Amit12690  nice work in sharing the steps .!!!

**Comment by dbolya** [comment]
Thanks @Amit12690 for the steps! I've referenced your post in the readme for future reference, and I'll close the issue for now.

**Comment by imvisibleman** [comment]
hi， @Amit12690  Can you train the source code?

**Comment by imvisibleman** [comment]
I have encountered some problems and hope to get your help.

**Comment by abhigoku10** [comment]
@imvisibleman  what is the problem ur facing pls share the errors

**Comment by imvisibleman** [comment]
I am a high school student, so my code understanding ability is not very strong, but I am very interested in yolact. Just like yoloV3, after I finished the data annotation, I don't know how to train my data.

**Comment by imvisibleman** [comment]
@abhigoku10 Can you help me?

**Comment by imvisibleman** [comment]
Is the Train.py code running directly?

**Comment by imvisibleman** [comment]
I don't know how to set the parameters.

**Comment by abhigoku10** [comment]
@imvisibleman  suggest you to look into the readme file where he has mentioned how data should be provided and even @Amit12690  has laid down the step beautifully

**Comment by hjm1990818** [comment]
@Amit12690 
Hi, I want to use Yolact to train my custom dataset, unfortunately, I meet an error that I cannot solve, could you please send your email address to me?
I want to show you more details with screen shot.
Looking forward to hearing from you. thank you very much in advance~

**Comment by niliuxi** [comment]
I have got the json file now, what do I need to modify to train my data?Looking forward to your reply

**Comment by niliuxi** [comment]
When using the labelme to mark the mask, suppose I only have a person category, but there are two people in the picture. Are the category names all personal, or person1, person2? I am using the second one, but found that this will make my category id 2.ask for advice, look forward to your reply

**Comment by niliuxi** [comment]
@Amit12690 When you use labelme for annotation, if there are two people in the picture, are they labeled as person-1, person-2 or both person?

**Comment by qingqinghu1026** [comment]
@Amit12690 I annotated my dataset with lamebe, which is to generate a JSON file for each picture, but in the code, "train_images": "path_to train_images", "train_info": "path_to train_annotation", which should be a JSON file generated by all pictures. Please ask how to do this?

**Comment by Zhang-O** [comment]
@Amit12690  why are you so intelligence!

**Comment by Zhang-O** [comment]
@Amit12690  why are you so intelligence!

**Comment by Zhang-O** [comment]
> @dbolya @abhigoku10 I think my training has made progress , thanks a lot for your valuable suggestions. Labelme and labelme2coco.py work perfectly to create the dataset. For anyone who is planning to finetune/train the model on a custom dataset , please follow following steps :
> 
> * Download and install Labelme (https://github.com/wkentaro/labelme)
> * Label using polygon labelling option provided (The repo has nice tutorials)
> * A json file will be created for each image labelled
> * Now use create a label.txt   (Example : https://github.com/wkentaro/labelme/blob/master/examples/instance_segmentation/labels.txt)
> * To generate coco style json  :  ./labelme2coco.py <labelled_data_folder>  <out_folder> --labels labels.txt
>   More details : https://github.com/wkentaro/labelme/tree/master/examples/instance_segmentation
> 
> Done! The dataset is created. Now proceed with the instruction in the yolact repo on custom training

I am confused with how I should annotate more than one objects of same class  in an img?For instance with cat, should it be cat_1, cat_2, cat_3and so on , or cat_0, cat_1, cat_2, and so on , or just cat, cat, cat,cat ,and so on?  I choose the last method mentioned above, and the result is bad in my own dataset which the model predict all img with only one instance, but img contains more than one instance indeed.

**Comment by infinityp913** [comment]
Hi @Amit12690 and @dbolya , I'm trying to use a custom dataset that has annotations in .npy. To create the COCO style annotatiosn can I just do this step in @Amit12690 's answer?

>     * ./labelme2coco.py <labelled_data_folder>  <out_folder> --labels labels.txt

Or is this just for converting labelme annotations to COCO annotations. If so, how could I do it for my dataset?

**Comment by ApoorvaOjha** [comment]
> @dbolya @abhigoku10 I think my training has made progress , thanks a lot for your valuable suggestions. Labelme and labelme2coco.py work perfectly to create the dataset. For anyone who is planning to finetune/train the model on a custom dataset , please follow following steps :
> 
> * Download and install Labelme (https://github.com/wkentaro/labelme)
> * Label using polygon labelling option provided (The repo has nice tutorials)
> * A json file will be created for each image labelled
> * Now use create a label.txt   (Example : https://github.com/wkentaro/labelme/blob/master/examples/instance_segmentation/labels.txt)
> * To generate coco style json  :  ./labelme2coco.py <labelled_data_folder>  <out_folder> --labels labels.txt
>   More details : https://github.com/wkentaro/labelme/tree/master/examples/instance_segmentation
> 
> Done! The dataset is created. Now proceed with the instruction in the yolact repo on custom training

Hey, I am not able to convert labeltococo as it needs pycocotools, whose installation is giving building error. i have installed cython also.

**Comment by ynma-hanvo** [comment]
hi,  guys, what will be the min number of custom images needed ,  to retrain a   resnet101 for instance segmentation of 10 classes?

**Comment by Mayuresh999** [comment]
II got this error while training on a custom dataset... I've already done changing necessary things in config.py what is the solution for this?

/content/yolact
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Initializing weights...
Begin training!

Traceback (most recent call last):
  File "./train.py", line 504, in <module>
    train()
  File "./train.py", line 270, in train
    for datum in data_loader:
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/yolact/data/coco.py", line 94, in __getitem__
    im, gt, masks, h, w, num_crowds = self.pull_item(index)
  File "/content/yolact/data/coco.py", line 148, in pull_item
    masks = [self.coco.annToMask(obj).reshape(-1) for obj in target]
  File "/content/yolact/data/coco.py", line 148, in <listcomp>
    masks = [self.coco.annToMask(obj).reshape(-1) for obj in target]
  File "/usr/local/lib/python3.7/dist-packages/pycocotools/coco.py", line 442, in annToMask
    rle = self.annToRLE(ann)
  File "/usr/local/lib/python3.7/dist-packages/pycocotools/coco.py", line 427, in annToRLE
    rles = maskUtils.frPyObjects(segm, h, w)
  File "pycocotools/_mask.pyx", line 293, in pycocotools._mask.frPyObjects
IndexError: list index out of range

**Comment by aravindsairam** [comment]
> II got this error while training on a custom dataset... I've already done changing necessary things in config.py what is the solution for this?
> 
> /content/yolact loading annotations into memory... Done (t=0.01s) creating index... index created! loading annotations into memory... Done (t=0.00s) creating index... index created! Initializing weights... Begin training!
> 
> Traceback (most recent call last): File "./train.py", line 504, in train() File "./train.py", line 270, in train for datum in data_loader: File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 345, in **next** data = self._next_data() File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data return self._process_data(data) File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data data.reraise() File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 394, in reraise raise self.exc_type(msg) IndexError: Caught IndexError in DataLoader worker process 0. Original Traceback (most recent call last): File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop data = fetcher.fetch(index) File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/content/yolact/data/coco.py", line 94, in **getitem** im, gt, masks, h, w, num_crowds = self.pull_item(index) File "/content/yolact/data/coco.py", line 148, in pull_item masks = [self.coco.annToMask(obj).reshape(-1) for obj in target] File "/content/yolact/data/coco.py", line 148, in masks = [self.coco.annToMask(obj).reshape(-1) for obj in target] File "/usr/local/lib/python3.7/dist-packages/pycocotools/coco.py", line 442, in annToMask rle = self.annToRLE(ann) File "/usr/local/lib/python3.7/dist-packages/pycocotools/coco.py", line 427, in annToRLE rles = maskUtils.frPyObjects(segm, h, w) File "pycocotools/_mask.pyx", line 293, in pycocotools._mask.frPyObjects IndexError: list index out of range

This is happened because of empty segmentation list. Please make sure you do not have empty segmentation mask.
