### ISSUE TITLE
is there any example code for yolact postprocess when infer with nvidia tensorrt?

### ISSUE THREAD

**Issue by jcyhcs** [dbolya/yolact#708]
hi,professor:
i have convert pth model to nvidia tensorrt engine successful, but i don't know how wiritten the postprocess code when infer with tensorrt, (in c++ code), so , can anyone give me an example code? PLEASE! HELP!

**Comment by minhnvl** [comment]
Could you show me the code or method that can convert Yolact model into TensorRT model?  Thank you so much !
