### ISSUE TITLE
training error (unexpected stop)

### ISSUE THREAD

**Issue by Ives-king** [dbolya/yolact#711]
![image](https://user-images.githubusercontent.com/95950765/145662710-c84ccdcf-bb42-45e4-a16d-8969e54a888d.png)

When I finished training the second epoch for verification calculation, the error message displayed TypeError:'NoneType' object is not iterable. There was no problem in the previous training, no parameters were changed, it was very inexplicable.

**Comment by Ives-king** [comment]
[  2]    1430 || B: 1.040 | C: 1.251 | M: 1.208 | S: 0.016 | T: 3.516 || ETA: 9 days, 15:54:30 || timer: 0.610
[  2]    1440 || B: 1.089 | C: 1.301 | M: 1.209 | S: 0.017 | T: 3.615 || ETA: 9 days, 15:46:19 || timer: 0.490
[  2]    1450 || B: 1.096 | C: 1.311 | M: 1.206 | S: 0.017 | T: 3.630 || ETA: 9 days, 15:30:58 || timer: 0.529
[  2]    1460 || B: 1.115 | C: 1.316 | M: 1.189 | S: 0.016 | T: 3.636 || ETA: 9 days, 15:20:33 || timer: 0.502
[  2]    1470 || B: 1.100 | C: 1.315 | M: 1.187 | S: 0.016 | T: 3.618 || ETA: 9 days, 15:02:54 || timer: 0.536
[  2]    1480 || B: 1.080 | C: 1.257 | M: 1.157 | S: 0.016 | T: 3.510 || ETA: 9 days, 14:55:00 || timer: 0.469
[  2]    1490 || B: 1.096 | C: 1.299 | M: 1.175 | S: 0.017 | T: 3.587 || ETA: 9 days, 14:51:36 || timer: 0.501
Traceback (most recent call last):
  File "D:/y/XM_TEST1/yolact/train.py", line 505, in <module>
    train()
  File "D:/y/XM_TEST1/yolact/train.py", line 372, in train
    compute_validation_map(epoch, iteration, yolact_net, val_dataset, log if args.log else None)
  File "D:/y/XM_TEST1/yolact/train.py", line 497, in compute_validation_map
    log.log('val', val_info, elapsed=(end - start), epoch=epoch, iter=iteration)
  File "D:\y\XM_TEST1\yolact\utils\logger.py", line 111, in log
    kwdargs.update(data)
TypeError: 'NoneType' object is not iterable

Computing validation mAP (this may take a while)...

Done.

Process finished with exit code 1

**Comment by Ives-king** [comment]
训练集的问题，没按步骤进行json转coco。现在好了

**Comment by Moriarty0112** [comment]
你好，我的数据转换是对的但还是报这个错误，你知道是什么原因吗
