### ISSUE TITLE
Same colour for different instance 

### ISSUE THREAD

**Issue by shivani21998** [dbolya/yolact#712]
I have three doubts maybe someone can help me out.
1. In videos, The mask for different objects of the same class are of the same color. What changes do I need to make in the code to output different mask colors for different instances of same class.
2.  In my output, only the first letter of the class label is displayed.
3.  I trained my model only on images and annotations of giraffe from coco dataset but the final MAP score did not cross 10map. Why is the map score so low. ( Trained for approximately 2000 train images and 184 validation images.)
![Capture](https://user-images.githubusercontent.com/29472727/145758719-4e3227da-5c1d-4b42-95a5-f415b593ef22.JPG)
![Capture2](https://user-images.githubusercontent.com/29472727/145758732-070fa83f-1c43-4998-a686-ae7c1e71c294.JPG)
![Capture2](https://user-images.githubusercontent.com/29472727/145759004-742f2045-893a-49e0-bd6a-9115c6dcd3a3.JPG)

My configuration: 
my_resnet50_config = yolact_resnet50_config.copy({
    'name': 'my_dataset',
    # Dataset stuff
    'dataset': my_dataset,
    'num_classes': len(my_dataset.class_names) + 1,

    # Image Size
    'max_size': 550,
})
And i trained using 'yolact_plus_resnet50_54_800000.pth' pre-trained weights.

**Comment by vijay180396** [comment]
i think its simple you can change color in eval.py if mask is greater than one you can set different color

**Comment by shivani21998** [comment]
> i think its simple you can change color in eval.py if mask is greater than one you can set different color
@vijay180396  Can you please explain in more detail how I can do the same? I'm fairly new and just started working on understanding the code. 
 
vijay180396

**Comment by vijay180396** [comment]
just debug the source code in eval.py it will help you to understand

**Comment by Wong-denis** [comment]
I have the same problem 
@shivani21998 Did you figure out how to set different color for different instances?

**Comment by Wong-denis** [comment]
> I have the same problem @shivani21998 Did you figure out how to set different color for different instances?

solved! see #499
