### ISSUE TITLE
Optimal image size for preserve_aspect_ratio

### ISSUE THREAD

**Issue by Shadercloud** [dbolya/yolact#726]
I don't really understand the comments on the `preserve_aspect_ratio` config.

```
    # Whether or not to preserve aspect ratio when resizing the image.
    # If True, this will resize all images to be max_size^2 pixels in area while keeping aspect ratio.
    # If False, all images are resized to max_size x max_size
    'preserve_aspect_ratio': False,
```

So if all my dataset images are size 1920x1080 what would the optimal settings be `preserve_aspect_ratio` and `max_size` ?

Should it be this (sqroot of 1920x1080)?
```
preserve_aspect_ratio = True
max_size = 1440
```

**Comment by st162053** [comment]
Hi, 
could you please share your result? I am working with 2 datasetets and have a lot of different sizes.
Thank you!
