### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by Kangzf1996** [dbolya/yolact#77]
Hello, I've met a problem when I run the codes. Could you help me? Thank you!
My pytorch version is 1.0.1, cuda=9.0 ,python version is 3.6.

Loading model... Done.
Traceback (most recent call last):
  File "eval.py", line 1020, in <module>
    evaluate(net, dataset)
  File "eval.py", line 797, in evaluate
    evalimage(net, args.image)
  File "eval.py", line 565, in evalimage
    img_numpy = prep_display(preds, frame, None, None, undo_transform=False)
  File "eval.py", line 142, in prep_display
    score_threshold   = args.score_threshold)
  File "/home/travail/yolact/layers/output_utils.py", line 87, in postprocess
    masks = torch.matmul(proto_data, masks.t())
RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1549628766161/work/aten/src/THC/THCBlas.cu:258

**Comment by dbolya** [comment]
Are you on a 20 series graphics card? Those require a minimum of CUDA 10.

**Comment by Kangzf1996** [comment]
> Are you on a 20 series graphics card? Those require a minimum of CUDA 10.

ohhh, yes. I forget that. Thank you! @dbolya

**Comment by dbolya** [comment]
No problem, if you have any other issues feel free to let me know.
