### ISSUE TITLE
ImportError: cannot import name 'OrderedDict' from 'typing'

### ISSUE THREAD

**Issue by rajuptvs** [dbolya/yolact#794]
First of all, amazing repo, and thanks for sharing the repo,

When trying to run eval.py on my windows system, got the following error
 
![image](https://user-images.githubusercontent.com/48201939/201481288-da8d5aef-89c1-4981-a91b-77dc341d23f8.png)

This has been resolved by changing the import from: <br>
![image](https://user-images.githubusercontent.com/48201939/201481308-9f0e1cad-34c7-40aa-82a8-d8dd0f947446.png)
<br>
to:
<br>
![image](https://user-images.githubusercontent.com/48201939/201481326-36f3bf91-606f-465a-a9b4-03acc08c0faa.png)

Is there any way that this change can be pushed or marked as a solution, for anyone who faced the same issue as me?

Thanks in advance

**Comment by rajuptvs** [comment]
Hey yes, I was able to solve that by replacing the following in the maxvit.py file 

Before : 
from typing import Any, Callable, List, Optional, OrderedDict, Sequence, Tuple

After:
from typing import Any, Callable, List, Optional, Sequence, Tuple
from collections import OrderedDict

**Comment by Ckq-Sugar** [comment]
ok,thanks

**Comment by bhavani2619** [comment]
> First of all, amazing repo, and thanks for sharing the repo,
> 
> When trying to run eval.py on my windows system, got the following error
> 
> ![image](https://user-images.githubusercontent.com/48201939/201481288-da8d5aef-89c1-4981-a91b-77dc341d23f8.png)
> 
> This has been resolved by changing the import from: ![image](https://user-images.githubusercontent.com/48201939/201481308-9f0e1cad-34c7-40aa-82a8-d8dd0f947446.png) to: ![image](https://user-images.githubusercontent.com/48201939/201481326-36f3bf91-606f-465a-a9b4-03acc08c0faa.png)
> 
> Is there any way that this change can be pushed or marked as a solution, for anyone who faced the same issue as me?
> 
> Thanks in advance

can u share how this was done
