### ISSUE TITLE
How to skip corrupt frames in video?

### ISSUE THREAD

**Issue by aidoshacks** [dbolya/yolact#80]
When running eval I get the following error midway of processing a video. I also get this error at the end of a video which makes me think that the error is triggered when the code can't find a valid frame: 

python eval.py --trained_model=weights/yolact_base_54_800000.pth --score_threshold=0.3 --top_k=100 --video_multiframe=2 --video=data/G0010151.mp4:results/output.mp4
Config not specified. Parsed yolact_base_config from the file name.

Loading model... Done.
Processing Frames  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░     22 /   9000 ( 0.24%)     7.32 fps        Traceback (most recent call last):
  File "eval.py", line 1020, in <module>
    evaluate(net, dataset)
  File "eval.py", line 806, in evaluate
    savevideo(net, inp, out)
  File "eval.py", line 765, in savevideo
    frame = torch.Tensor(vid.read()[1]).float().cuda()
TypeError: new(): data must be a sequence (got NoneType)

I feel like some frames are just corrupt in my video. How would I go about implementing code to skip frames?

Thanks in advance!

**Comment by dbolya** [comment]
Hmm that's weird. It's probably best to see if you can fix your video, but if you want to try to skip frames you can change
```python
frame = torch.Tensor(vid.read()[1]).float().cuda()
```
to
```python
frame = vid.read()[1]
if frame is None:
    continue
frame = torch.from_numpy(frame).cuda().float()
```

Also I'm realizing now that I forgot to apply a speed improvement to `savevideo` (I applied this to your code snippet and pushed the change to master).

**Comment by aidoshacks** [comment]
Awesome thankyou! Closing this as issue is fixed!
