### ISSUE TITLE
Config not specified. Parsed yolact_base_config from the file name.

### ISSUE THREAD

**Issue by lifeiwen** [dbolya/yolact#83]
environment：torch1.0.1
When I want to test a picture，This problem has arisen，how to solve it？thanks

**Comment by dbolya** [comment]
That's not an error... It's just saying that you didn't manually specify a config, so it used the filename to guess the config. I added that for convenience so you didn't have to write `--config=x --trained_model=y` all the time. This is expected behavior.

**Comment by foyez1672** [comment]
![aaa](https://user-images.githubusercontent.com/77295766/105499150-4040f180-5ceb-11eb-94a4-2349d8b334c9.PNG)
How can i solve this error? and could you please tell me how blur specific segmented object ?
