### ISSUE TITLE
I think your work is very good,but your code may be not good

### ISSUE THREAD

**Issue by mshmoon** [dbolya/yolact#84]
Thank you for your work ,but your code is not good for the others research.The style is amazing,

**Comment by dbolya** [comment]
Any tips? This was my first project as an undergraduate, so pointers are much appreciated.

**Comment by mshmoon** [comment]
> Any tips? This was my first project as an undergraduate, so pointers are much appreciated.

I am very sorry for my words，because my boss urge me to modify your code. I am very sorry again.

**Comment by dbolya** [comment]
No worries, let me know if you find any bugs.
