### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by TTXXQ** [dbolya/yolact#847]
I'm trying to download resnet101_reducedfc.pth, but the web page says the file doesn't exist!

**Comment by vinizhang-1** [comment]
I have！

**Comment by krisati** [comment]
here too

**Comment by tcotte** [comment]
Could you share the updated link please ?

**Comment by krisati** [comment]
已收到O(∩_∩)O！！！

**Comment by abandonnnnn** [comment]
可以分享给我吗？谢谢

**Comment by mosu2001** [comment]
腾讯微云上找到了一份，链接放这里了https://share.weiyun.com/5VANajZQ

**Comment by dbolya** [comment]
Hello, I've re-uploaded all the checkpoints to this huggingface collection: https://huggingface.co/collections/dbolya/yolact-2019-models-68bf670f7239d610bc933a10 (including the initial weights) and have updated all the links in the readme to match. Thanks for bringing this up!

**Comment by krisati** [comment]
已收到O(∩_∩)O！！！
