### ISSUE TITLE
Background annotations

### ISSUE THREAD

**Issue by ridasalam** [dbolya/yolact#89]
I would like to add some training samples in my dataset without any object of interest present. How can I adapt the annotations/config for this purpose?

**Comment by dbolya** [comment]
You mean training examples without annotations? Currently I ignore all images without any annotations, because it would take a lot of effort to support empty tensors everywhere (and because the mAP metric doesn't really penalize it).

**Comment by ridasalam** [comment]
Yes, I was also thinking along the same lines as you suggested..

My issue is that I have only one class and there are more false positives than I would like (with good score thresholds).

**Comment by dbolya** [comment]
Oh I see, then yeah probably a background class would be your best option. Maybe add that class to only images without your object of instance? And also just don't include a mask, just a box. That way it won't affect the prototypes (i.e., make the mask empty).

You can then either just ignore that class, or do something where if the score for that class is higher than any of the object of interest detections, you label that image as having no objects of interest.

**Comment by ridasalam** [comment]
So, in a coco-style annptation:
        'segmentation': **[]**,
        'iscrowd': is_crowd,
        'image_id': image_id,
        'category_id': category_id,
        'id': annotation_id,
        'bbox': **x,y as 0,0 and width and height of the total image**,
        'area': **0??**,

**Comment by dbolya** [comment]
`bbox` and `area` are correct, but the segmentation should still be in the RLE format. So it should just be
```
'segmentation: {
   'size': [h, w],
   'counts': LEB128_compressed([w*h])
}
```

The LEB128 compression is a bit tricky, so best to just use pycocotools to convert an all zero tensor to an RLE like for any other annotation.

**Comment by ridasalam** [comment]
My segmentation is in the polygon format though. Does it make a difference?

**Comment by dbolya** [comment]
Oh no, they're interchangeable (it selects which one to decode automatically). I'm not sure if an empty polygon turns into an empty mask or if it throws an error. If it's easier for you to do an empty polygon, you can try that first.

**Comment by ridasalam** [comment]
How do you currently treat the background? When we add an extra class in config, I mean?

**Comment by dbolya** [comment]
During eval, the network predicts the number of classes + 1 (the extra class in the config) and softmax over that dimension. After that, we just cut out that extra class and return that as the class predictions. If the network produces a high score for the background class, then because of softmax, the rest of the classes will have their scores reduced (hopefully) below the score threshold.

When you add this fake detection, since it's not a true background class you should add it as a separate class entirely (so your dataset would have 2 classes: "object of interest" and "no object of interest", and then config would nave a `num_classes` of 3).

**Comment by ridasalam** [comment]
Hmm. I'm just concerned that the network might learn the "no object of interest" class as full images that don't have the "object of interest". But that's not what I mean by false positives. For me the false positives occurs in images with  "object of interest" where things in the background are also taken as  "object of interest".

**Comment by dbolya** [comment]
Hmm, that might be the case. I'm not sure what else you could do that wouldn't require annotating another class though. You could maybe try increasing the negative to positive ratio of OHEM? Currently it's 3 neg : 1 pos, but increasing that would make false positives more damaging.

You can change that setting here:
https://github.com/dbolya/yolact/blob/f46dc4385a41ed1f2df6716ecf6084081afcbec6/train.py#L172

**Comment by ridasalam** [comment]
What about annotating all "no object of interest" pixels as a new class in all training samples? In that case, it will be a complete scene segmentation.

**Comment by dbolya** [comment]
Oh yeah that might work. That's probably the best option.

**Comment by ridasalam** [comment]
Ok, I realised there's a problem when there is a hole in the background class (due to the presence of a person). COCO style annotations cannot handle holes in polygons.

Do you have an alternative style of providing the mask? Instead of generating them from annotations, perhaps giving them as pngs?

**Comment by dbolya** [comment]
Then use the RLE format. You can use pycocotools to convert a 2d tensor into an RLE, so it can handle arbitrary annotations (all it is is an array with alternating numbers of 0's and 1's. So [10, 20, 30] would be 10 0's followed by 20 1's then followed again by 30 0's finally reshaped into the saved size, though coco does some extra compression on top of this).

**Comment by ridasalam** [comment]
That worked, thanks!
