### ISSUE TITLE
hello,I meet a problem.

### ISSUE THREAD

**Issue by mshmoon** [dbolya/yolact#90]
I train your model  coco dataset.I find the location of (h,w) can not be prediction very well.So  I want to change location loss by weight,but I do not know which loss belong to the (h,w)

**Comment by abhigoku10** [comment]
@mshmoon can you elaborate your issues which your currently facing , even i am also slightly facing it

**Comment by dbolya** [comment]
The branch that controls that is the box branch. The setting you're looking for is `'bbox_alpha'`.

**Comment by dbolya** [comment]
Since this has been open so long, I'm going to close it. Feel free to reopen if you have any updates.
