### ISSUE TITLE
Model Optimization !!!!

### ISSUE THREAD

**Issue by abhigoku10** [dbolya/yolact#91]
@dbolya currently all the models which is trained is in the range of 100-200 MB , do u have any thoughts on optimisation of the model using quantization or pruning which shall yield more fps

**Comment by dbolya** [comment]
No idea. You're welcomed to try it, but I doubt you'd be able to increase FPS much without deleting entire layers (which would reduce performance). Though, I'm not too well versed in pruning models.

**Comment by abhigoku10** [comment]
@dbolya sure i shall look try it out and update you on that

**Comment by andeyeluguo** [comment]
@abhigoku10 you can try mixed precision training as the mmdetection.

**Comment by abhigoku10** [comment]
@andeyeluguo  are you referring to this paper https://arxiv.org/pdf/1906.07155v1.pdf  implementation

**Comment by abhigoku10** [comment]
@andeyeluguo hi the mmdetection u suggested doesnot optimise the model , do u have any other method which i can do the model reduction

**Comment by dbolya** [comment]
Since this has been open so long, I'm going to close it. Feel free to reopen if you have any updates.
