### ISSUE TITLE
get features for each object

### ISSUE THREAD

**Issue by sdimantsd** [dbolya/yolact#93]
Hi, thanks for you'r job!!!

There is an option to get a list of features for each object in the image?
Even features that mean nothin to humen eye, but if the features consistent with to the object.

I mean to somthing like in AlexNet that predict only one object per image, the layer at the top of the network is actually a features for the image, or in AlexNet is features of the object.
there is something similar in you network?

Thanks!

**Comment by dbolya** [comment]
There kinda is:

For bounding boxes, mask coefficients, and class prediction, the 3x3 area of features around each pixel in the last layers of our backbone (similar to the layer at the top of AlexNet that you mentioned) becomes the features for one anchor box (so there are ~19k anchor boxes in total that if predicted as positive turn into a detection). You can find those layers in the prediction head class in `yolact.py`. This part is the same as any other object detector (with the mask coefficients added in a similar way).

Then YOLACT also has prototype features for masks, which you can visualize in a kind of hacky way if you follow #82.

If you haven't already, I recommend you read [our paper](https://arxiv.org/abs/1904.02689), [SSD](https://arxiv.org/abs/1512.02325), and [RetinaNet](https://arxiv.org/abs/1708.02002) (the original object detectors we've based our network on) to get an understanding of how the features are used.

**Comment by sdimantsd** [comment]
Thanks! i will look into it!

**Comment by sdimantsd** [comment]
Hi, you writed:
> You can find those layers in the prediction head class in yolact.py

I can't find a class named somthing like "prediction head", i think i didn't understood you. can you explain where to find it?

**Comment by sdimantsd** [comment]
OK, im not shure but i think i found it.
it's in line 530 in yolact.py --> outs = self.backbone(x) ?
outs is the matrix from the backbone?

If so, how can i found the matrix for each object?
Do i need to project each object in the original image to the last layer and "take" each pixel in the object mask in the last layer as me features?

If no, can you please explain how to do it?

Thanks!!!

**Comment by dbolya** [comment]
Nah, you want the code in PredictionHead. Specifically:
https://github.com/dbolya/yolact/blob/f46dc4385a41ed1f2df6716ecf6084081afcbec6/yolact.py#L211

This is a size `[batch_size, feature_size, conv_h, conv_w]` tensor of features as the last layer before mask coefficient prediction. You can see above the same for the other branches. If you wanted to extract, say, the features for the anchors in the (1, 1) position (1 down, 1 right from the top left), you could go:
```python
mask_x[batch, :, 0:3, 0:3]
```

In general, it would be:
```python
mask_x[batch, :, y-1:y+2, x-1:x+2]
```

Though note that objects on the border (e.g., (0, 0)) require padding so you might want to pad it beforehand (which changes the math a little).

**Comment by sdimantsd** [comment]
OK, thanks.
I guess that (conv_h, conv_w) is not equal to (img_h, img_w). am i right?
If so, should I drop the original image onto mask_x to find the features of each pixel in the original image?

**Comment by dbolya** [comment]
It isn't the original image size, yeah. And dropping the original image onto mask_x won't exactly work either because there are 5 prediction heads, each with a different conv size. All those heads are then merged together into one long list of 19k possible detection locations, and then each is individually considered for confidence / NMS.

So if you want to see the features that fed into a particular detection, you'll have to track that detection back through NMS and that merge to get the prediction head and x,y it came from. If you're instead just wondering what the features look like (and don't care about matching features to detections), you can just map the image size onto that conv_h and conv_w though. If you're doing that, I'd also recommend doing the same for all 5 prediction heads (they get progressively smaller in conv size, so there might be some interesting patterns).

If you haven't already, I really do recommend you read the SSD paper I linked above. It explains all of this in detail (since it was the one to popularize this multiple prediction head approach).

**Comment by dbolya** [comment]
Since this has been open so long, I'm going to close it. Feel free to reopen if you have any updates.

**Comment by andreazuna89** [comment]
> It isn't the original image size, yeah. And dropping the original image onto mask_x won't exactly work either because there are 5 prediction heads, each with a different conv size. All those heads are then merged together into one long list of 19k possible detection locations, and then each is individually considered for confidence / NMS.
> 
> So if you want to see the features that fed into a particular detection, you'll have to track that detection back through NMS and that merge to get the prediction head and x,y it came from. If you're instead just wondering what the features look like (and don't care about matching features to detections), you can just map the image size onto that conv_h and conv_w though. If you're doing that, I'd also recommend doing the same for all 5 prediction heads (they get progressively smaller in conv size, so there might be some interesting patterns).
> 
> If you haven't already, I really do recommend you read the SSD paper I linked above. It explains all of this in detail (since it was the one to popularize this multiple prediction head approach).

Dear dbolya,
first of all congrats for your great work and code. I am interested in identifying the features for the specific detected objects. The following is what I have done: I have the segmentation masks for each objects at the original image resolution; I resize the masks to the spatial features dimensions (e.g. 69x69 if I consider the first feature head); I take the corresponding features at the 1s location of the mask; I finally average the features at those locations to get a feature vector of 256 dimensions. Does this procedure make sense to you? Are those features the real ones associated to the detected objects? I could probably also do the same for the other 4 heads to get an improved representation.  

Thanks a lot!
