### ISSUE TITLE
RuntimeError: copy_if failed to synchronize: device-side assert triggered

### ISSUE THREAD

**Issue by lkj1114889770** [dbolya/yolact#97]
File "train.py", line 343, in <module>
```
    train()
  File "train.py", line 251, in train
    losses = criterion(out, wrapper, wrapper.make_mask())
  File "/home/see/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 494, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/see/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/see/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 494, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/see/yolact/layers/modules/multibox_loss.py", line 163, in forward
    losses.update(self.lincomb_mask_loss(pos, idx_t, loc_data, mask_data, priors, proto_data, masks, gt_box_t, inst_data))
  File "/home/see/yolact/layers/modules/multibox_loss.py", line 474, in lincomb_mask_loss
    pos_idx_t = idx_t[idx, cur_pos]
RuntimeError: copy_if failed to synchronize: device-side assert triggered
```
I got the following problem when I just replace the backbone with efficientNet , can you help me , thanks.

**Comment by dbolya** [comment]
Uhh a failure to synchronize usually means there's a NaN or an Inf somewhere where there shouldn't be. Have you checked that your implementation of the network works with random weights?

**Comment by lkj1114889770** [comment]
@dbolya I Initialize weights from the pre-trained model, and the problem arose after 5 epochs,.

**Comment by dbolya** [comment]
What did the loss look like before the assert was triggered?

**Comment by lkj1114889770** [comment]
@dbolya Emm,i have reduced the learning rate to train the model again, and the previous output can't bee seen in the virtual terminal. It should takes a while to get the loss before the exception. But I remember it seems to be normal like:
[  0]    8450 || B: 7.316 | C: 6.130 | M: 4.865 | S: 1.274 | T: 19.585 || ETA: 4 days, 2:15:20 || timer: 0.432

**Comment by dbolya** [comment]
Hmm, that loss looks normal. You might want to log the console output by piping it to a file and try again. Even the master branch with Resnet-101 has a potential for the loss to blow up within the first epoch on COCO for some seeds (for weights not part of the backbone). If it doesn't happen in that first epoch, it usually doesn't happen for the rest of training, but you mentioned this happened on epoch 5? Was that on COCO? If this is indeed the issue, then reducing lr will probably help.

Also, does this happen every time you've tried to train it? Maybe you just got unlucky with the random weights. It's just that it's weird to have a runtime error a full 5 epochs in.

**Comment by abhigoku10** [comment]
@lkj1114889770 its good idea to use efficient net , can you share the implementation may be i would be able to lend some support on this

**Comment by lkj1114889770** [comment]
@abhigoku10 I put the code in [https://github.com/lkj1114889770/yolAct_efficientNet](https://github.com/lkj1114889770/yolAct_efficientNet). EfficientNet implementation is based on the work by [https://github.com/lukemelas/EfficientNet-PyTorch](https://github.com/lukemelas/EfficientNet-PyTorch). I have trained the model with the backbone of efficientnet-b0, and get a poor performance. And the train for 'efficientnet-b4' is under way. But i think it may still have some problems in my code,

**Comment by abhigoku10** [comment]
@lkj1114889770  thanks for sharing the source code i shall have look into it !!!

**Comment by dbolya** [comment]
Since this has been open so long, I'm going to close it. Feel free to reopen if you have any updates.
