### ISSUE TITLE
Issue while running  eval.py 

### ISSUE THREAD

**Issue by phoebe0920** [dbolya/yolact#99]
Excuse me . Can you help me  solve this problem? when l run  python eval.py  --trained_model=weights/yolact_resnet50_54_800000.pth 
it appears this following problem. 
`
Traceback (most recent call last):
  File "eval.py", line 1020, in <module>
    evaluate(net, dataset)
  File "eval.py", line 800, in evaluate
    inp, out = args.images.split(':')
ValueError: not enough values to unpack (expected 2, got 1)
`

**Comment by dbolya** [comment]
Is that your full command? That error looks like the command line argument `--images` was set to something. To use images you need to go `--images=input_folder/:output_folder/` (hence the complaint about `split(':')`)

**Comment by phoebe0920** [comment]
thanks.

**Comment by Tiuuuuu** [comment]
python eval.py --trained_model=weights/yolact_base_1428_10000.pth --score_threshold=0.15 --top_k=15 --images=data/coco/images/test:results/ --config=yolact_base_config --display
like this
